### PR TITLE
Add device and os options to caching profiles

### PR DESCRIPTION
**Pull request by mollyIV**
Resolves https://github.com/tuist/tuist/issues/2191

### Short description 📝

This pull request is adding **two new  optional parameters** to a caching profile: 
* device
* os 

```swift
let config = Config(
    cache: .cache(profiles: [
        .profile(
          name: "Simulator", 
          configuration: "Debug", 
          device: "iPhone 11 Pro",  // <-- new parameter
          os: "15.0" // <-- new parameter
        )
    ])
)
```

The motivation behind adding these params is described in details in [this issue](https://github.com/tuist/tuist/issues/2191).

### Checklist ✅

- [x] The code architecture and patterns are consistent with the rest of the codebase.
- [x] The changes have been tested following the [documented guidelines](https://docs.tuist.io/contributors/testing-strategy/).
- [x] The `CHANGELOG.md` has been updated to reflect the changes. In case of a breaking change, it's been flagged as such.
- [x] In case the PR introduces changes that affect users, the documentation has been updated.

### CODE REVIEW

**Comment by mollyIV** [comment]
Hello @danyf90 @fortmarek 👋 

Thanks for asking questions and sharing thoughts. 

> 1. does the problem affects also caching with xcframeworks? if not, we would be invalidating cache for no reason when changing device

 XCFramework are not affected by os and device values, because when creating an XCFramework platform’s generic run destination is being provided. For example: 

```
xcodebuild archive \
...
-destination destination="generic/platform=iOS Simulator" \
...
```

> 2. I am not sure having the info in the cache profile is the right thing. 

I highly recommend reading [the conversation from the pull request that introduced caching profiles](https://github.com/tuist/tuist/pull/2221). Initially we wanted to simply add the CLI parameters, however, we dropped this idea due to: 

* commands parity - if a user warmed up cache with given parameters, he / she would need to use exact  same arguments for other command that leverage caching, for instance `focus`
* caching profiles offer nicer end user experience and API 

> Considering all the combinations, potentially you might need A LOT of device/iOS combinations, and I don't think it's scalable to create a scheme for each of them. What about having such information as CLI argument?

Do you have a real life use case when you'd need that many profiles? Please note `os` and `device` params are optional. 

> You can do a for loop in Swift to create more of them - but I think the main point of having a profile is to codify the arguments, so it's easier to reuse the cache as the whole team knows which profiles they can use.

100 % 👍

**Comment by danyf90** [comment]
Regarding this concern

> The issue with passing arguments is that you'll have to pass them every time to tuist focus as well which may become tedious quite quickly.

I don't see much difference as in any case you will have to pass either the cache profile or the device and OS to both argument, but I see the advantages of using a cache profile, especially if we implement autocompletion

**Comment by mollyIV** [comment]
> do you think you could edit some fixture to include this? I think for cache-related and user-facing changes, it'd be a good idea to make sure the feature works in an acceptance test as well.

@fortmarek I have been thinking about adding acceptance tests to this feature, however, that'd mean tying it up with particular device and OS. Not sure if we wanna do that, because it would introduce implicit dependency - updating Xcode version that acceptance tests are executed on would require the change in acceptance test. Thoughts?

**Comment by danyf90** [comment]
> > do you think you could edit some fixture to include this? I think for cache-related and user-facing changes, it'd be a good idea to make sure the feature works in an acceptance test as well.
> 
> 
> 
> @fortmarek I have been thinking about adding acceptance tests to this feature, however, that'd mean tying it up with particular device and OS. Not sure if we wanna do that, because it would introduce implicit dependency - updating Xcode version that acceptance tests are executed on would require the change in acceptance test. Thoughts? 

Updating acceptance tests also requires changes to other fixtures, e.g. to rebuild some precompiled frameworks, so I think it's not a problem to add this

**Pull request merged**
