### PR TITLE
Stringsdict support

### PR DESCRIPTION
**Pull request by fortmarek**
# Short description 📝

Swiftgen now supports generating accessors for `stringsdict`. We should make that possible, too

### Solution 📦

Add `stringsdict` to the list of possible string files

### CODE REVIEW

**Review by laxmorek — APPROVED** [review]
🎉

**Review by kwridan — COMMENTED** [review]
Nice to see more supported resources 👍 

Looks like the plist Bool is being interpreted as an integer again :/ - I recall this was previously fixed in https://github.com/tuist/tuist/issues/1784

Screenshot 2020-11-04 at 07 33 44

**Comment by fortmarek** [comment]
Thanks for the feedback @kwridan! Are you sure you have run with the latest version? Because the issue of interpreting booelans as integers should have been fixed in `SwiftGen` and when I run it now via Xcode, it looks like the following: 
image

**Comment by kwridan** [comment]
I checkout out this branch 😅 - oddly when I did `swift build` it updated `Package.resolved`

```diff
diff --git a/Package.resolved b/Package.resolved
index d8aa0f24..da166509 100644
--- a/Package.resolved
+++ b/Package.resolved
@@ -15,8 +15,8 @@
         "repositoryURL": "https://github.com/IBM-Swift/BlueSignals",
         "state": {
           "branch": null,
-          "revision": "1f6c49e186c8a4eeef87ba14f2f97b8646559d13",
-          "version": "1.0.200"
+          "revision": "b7331c8bef913f5f8b3cffa6ecfcce679f7c2531",
+          "version": "1.0.21"
         }
       },
       {
@@ -51,8 +51,8 @@
         "repositoryURL": "https://github.com/krzyzanowskim/CryptoSwift",
         "state": {
           "branch": null,
-          "revision": "af1b58fc569bfde777462349b9f7314b61762be0",
-          "version": "1.3.2"
+          "revision": "39f08ac5269361a50c08ce1e2f41989bfc4b1ec8",
+          "version": "1.3.1"
         }
       },
       {
@@ -78,8 +78,8 @@
         "repositoryURL": "https://github.com/tid-kijyun/Kanna.git",
         "state": {
           "branch": null,
-          "revision": "4a80ebe93b6966d5083394fcaaaff57a2fcec935",
-          "version": "5.2.3"
+          "revision": "609367a2cd84827a33383cf7923cb4fe8f69ee0a",
+          "version": "5.2.2"
         }
       },
       {
@@ -87,8 +87,8 @@
         "repositoryURL": "https://github.com/kishikawakatsumi/KeychainAccess.git",
         "state": {
           "branch": null,
-          "revision": "654d52d30f3dd4592e944c3e0bccb53178c992f6",
-          "version": "4.2.1"
+          "revision": "3d0ea2c0806791abcc5d7f0d9f62f1cfd4a7264d",
+          "version": "4.2.0"
         }
       },
       {
@@ -127,21 +127,12 @@
           "version": "0.9.1"
         }
       },
-      {
-        "package": "Stencil",
-        "repositoryURL": "https://github.com/stencilproject/Stencil.git",
-        "state": {
-          "branch": null,
-          "revision": "94197b3adbbf926348ad8765476a158aa4e54f8a",
-          "version": "0.14.0"
-        }
-      },
       {
         "package": "StencilSwiftKit",
         "repositoryURL": "https://github.com/fortmarek/StencilSwiftKit.git",
         "state": {
           "branch": "stable",
-          "revision": "99ac008eb7026e40af7fc882d5788f5de6eda47e",
+          "revision": "33cf26bc68f3aced91cb810bc0a4e5ce445a140f",
           "version": null
         }
       },
@@ -195,7 +186,7 @@
         "repositoryURL": "https://github.com/fortmarek/SwiftGen",
         "state": {
           "branch": "stable",
-          "revision": "ef8d6b186a03622cec8d228b18f0e2b3bb20b81c",
+          "revision": "db5c510ab89be880b5d7f9d6d43a19faa5f172de",
           "version": null
         }
       },
@@ -231,8 +222,8 @@
         "repositoryURL": "https://github.com/jpsim/Yams.git",
         "state": {
           "branch": null,
-          "revision": "88caa2e6fffdbef2e91c2022d038576062042907",
-          "version": "4.0.0"
+          "revision": "81a65c4069c28011ee432f2858ba0de49b086677",
+          "version": "3.0.1"
         }
       },
       {
```

I wonder, could this be a side effect of using a branch instead of explicitly specifying a version for `SwiftGen` in the package manifest? - will wipe my `.build` folder and try again.

**Review by kwridan — APPROVED** [review]
A clean build did the trick 👍

**Review by pepibumur — APPROVED** [review]

**Pull request merged**
