### PR TITLE
Add `--skip-cache` parameter to `tuist test`

### PR DESCRIPTION
**Pull request by olejnjak**
### Short description 📝

Add `--skip-cache` parameter to `tuist test` so we have explicit option to run all tests without using caching.

Maybe I would rather discuss how to test it as I don't get failed tests when I use `skipCache = true` as default in `TestServiceTests.testRun(...)`. Any ideas?

### Checklist ✅

- [x] The code architecture and patterns are consistent with the rest of the codebase.
- [ ] The changes have been tested following the [documented guidelines](https://docs.tuist.io/contributors/testing-strategy/).
- [x] The `CHANGELOG.md` has been updated to reflect the changes. In case of a breaking change, it's been flagged as such.
- [x] In case the PR introduces changes that affect users, the documentation has been updated.

### CODE REVIEW

**Comment by adellibovi** [comment]
Hi @olejnjak,
Thanks for opening this PR,
I wonder what's your use case behind this? Is it because you are having issue with the caching? Or you need to execute all of them for other reasons?

**Comment by olejnjak** [comment]
Well not with the caching itself, but for some products we wanna present code coverage stats, so for PR jobs we want to use caching obviously, but for deploy jobs we want to run all tests so we get real code coverage stats.

**Comment by adellibovi** [comment]
Got it, maybe `--all` or `--all-tests` works better? I feel like `--ignore-cache` exposes an implementation details rather then describe user's intent. @fortmarek since you've implemented selective tests, what do you think?

**Comment by danyf90** [comment]
If we want to go for "cache" something, we should probably use `--no-cache` as for `tuist focus`

**Comment by olejnjak** [comment]
We have been discussing it briefly in https://github.com/tuist/tuist/pull/3177#pullrequestreview-708311104, but I think keeping it consistent with `focus --no-cache` would make sense.

**Comment by fortmarek** [comment]
> Got it, maybe --all or --all-tests works better? I feel like --skip-cache exposes an implementation details rather then describe user's intent

Yeah, I agree. I like `--all-tests` probably a little bit better. I was also wondering if we could just clean the tests cache if you run `tuist test --clean`. However, that'd mean you wouldn't be able to clean Xcode artifacts without cleaning tuist artifacts. It'd make for a cleaner API, however. Would you expect a cache for tests to be cleaned with the `--clean` flag?

**Comment by olejnjak** [comment]
I renamed `TestCommand` argument and kept the naming in `TestService` as for user I think it makes sense to use `--all-tests` and implementation-wise I think the `skipCache` seems to be more descriptive. Agree?

**Comment by fortmarek** [comment]
> And for the --clean argument I would expect all build artifacts to be cleared so probably removing respective artifacts from tuist cache would make sense.

If we decided that clean would also clean the cache, we wouldn't need an extra argument? It'd be nice to limit the amount of options this command has.

**Comment by olejnjak** [comment]
Okay, will try to do that.

**Comment by fortmarek** [comment]
> Okay, will try to do that.

You'll have to find the test artifacts directory location for the specific project and then just delete it.

I'd also appreciate @danyf90 and @adellibovi feedback here about what would their expectations be and if that behavior makes sense to them.

**Comment by danyf90** [comment]
What would --clean do differently with respect to running tuist clean before tuist test?
If the behavior would be the same I would keep using the separate commands

**Comment by fortmarek** [comment]
>  If the behavior would be the same I would keep using the separate commands

It'd clean only the artifacts relevant to the test at hand. `tuist clean` will delete _everything_ which is not something user probably wants to do in this case.

**Comment by adellibovi** [comment]
> > Okay, will try to do that.
> 
> 
> 
> You'll have to find the test artifacts directory location for the specific project and then just delete it.
> 
> 
> 
> I'd also appreciate @danyf90 and @adellibovi feedback here about what would their expectations be and if that behavior makes sense to them.

I would say that it does make sense for me as well to clean _all_ build related artifacts including Tuist test cache. We would follow what is expected from Xcode clean command on a Tuist level.

**Comment by fortmarek** [comment]
@olejnjak seems like there is support for this behavior, so if you wanted to implement it, it'd be great 🚀

**Pull request closed without merging**
