### PR TITLE
feat: ruby update 3.0.2

### PR DESCRIPTION
**Pull request by apps4everyone**
Short description 📝
I'm updating the Ruby version required by the repository to the latest available Ruby version, 3.0.2. As part of this, I added ruby "3.0.2" to require developers to do bundle install with that version of Ruby, otherwise the installation fails.

### CODE REVIEW

**Comment by apps4everyone** [comment]
@pepibumur can we update to latest 3.0.2? thx

**Review by pepibumur — CHANGES_REQUESTED** [review]
Hey @apps4everyone. Unfortunately, this PR requires some work to be accepted:
- It lacks context and the motivation behind doing this update.
- It's half-done. If you search for 3.0.1 you'll notice there are some more references to the Ruby version.

Also going forward, I'd kindly ask you to be more mindful about the communication. We are devoting our free time to the project and pushing a half-way done PR and asking people to finish it for you might make people on the other side they have the obligation to do it for you.

**Comment by apps4everyone** [comment]
> Hey @apps4everyone. Unfortunately, this PR requires some work to be accepted:
> 
> * It lacks context and the motivation behind doing this update.
> * It's half-done. If you search for 3.0.1 you'll notice there are some more references to the Ruby version.
> 
> Also going forward, I'd kindly ask you to be more mindful about the communication. We are devoting our free time to the project and pushing a half-way done PR and asking people to finish it for you might make people on the other side they have the obligation to do it for you.

hey, @pepibumur sorry but was not aware that there was more to do. I was only using ./fourier format swift --fix and this was working with my changes. Updated now.

**Comment by apps4everyone** [comment]
tested ./fourier test tuist acceptance projects/tuist/features/build.feature
4 scenarios (2 undefined, 2 passed)
37 steps (11 skipped, 3 undefined, 23 passed)
3m12.662s
don't know why this is failing on CI

**Comment by pepibumur** [comment]
> Library not loaded: /Users/runner/hostedtoolcache/Ruby/3.0.1/x64/lib/libruby.3.0.dylib (LoadError)

It's failing to dynamically load a library. By looking at the error it seems that it's trying to load the invalid version of Ruby's dynamic library.

**Comment by pepibumur** [comment]
I'll open a PR with the update.

**Pull request closed without merging**
