### PR TITLE
Fixed rendering of generated `Info.plist` in Xcode

### PR DESCRIPTION
**Pull request by mikchmie**
Resolves https://github.com/tuist/tuist/issues/4492
Request for comments document (if applies):

### Short description 📝

Xcode properly recognizes `Info.plist` files when they include `-Info` suffix in their names.
This PR changes file name format from `TargetName.plist` to `TargetName-Info.plist`.

### How to test the changes locally 🧐

See reproduction steps and expected result in the linked issue.

### Checklist ✅

- [x] The code architecture and patterns are consistent with the rest of the codebase.
- [x] The changes have been tested following the [documented guidelines](https://docs.tuist.io/contributors/testing-strategy/).
- [x] The PR includes the label `changelog:added`, `changelog:fixed`, or `changelog:changed`, whenever it should be included in the “Added”, “Fixed” or “Changed” section of the CHANGELOG. Note: when included in the CHANGELOG, the title of the PR will be used as entry, please make sure it is clear and suitable.
- [x] In case the PR introduces changes that affect users, the documentation has been updated.
- [x] In case the PR introduces changes that affect how the cache artifact is generated starting from the `TuistGraph.Target`, the `Constants.cacheVersion` has been updated.

### CODE REVIEW

**Review by danyf90 — APPROVED** [review]
I think you might need to update some acceptance tests, let's se what CI says 🚀

**Review by adellibovi — APPROVED** [review]
Thanks @mikchmie :) Let's make sure we follow the check list as well, for example to introduce this improvement in the changelog

**Comment by danyf90** [comment]
> I wanted to add a `changelog:changed` label, but I don't see such option. I guess I don't have permissions to do that.

You mean you don't see the label at all or you can't add it?

BTW I have added it and updated the PR title to be more "changelog-oriented"

**Comment by mikchmie** [comment]
Looks like some jobs failed due to network issues. Could someone run them again?

**Pull request merged**
