### PR TITLE
Add support for symbolset resources in default resource synthesizer

### PR DESCRIPTION
**Pull request by danyf90**
Resolves https://github.com/tuist/tuist/issues/5450

### Short description 📝

> Describe here the purpose of your PR.

### How to test the changes locally 🧐

> Include a set of steps for the reviewer to test the changes locally (see [the documentation](https://docs.tuist.io/contributors/testing-strategy) for reference).

### Contributor checklist ✅

- [ ] The code has been linted using run `make lint-fix`
- [ ] The change is tested via unit testing or acceptance testing, or both
- [ ] The title of the PR is formulated in a way that is usable as a changelog entry
- [ ] In case the PR introduces changes that affect users, the documentation has been updated

### Reviewer checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase
- [ ] Reviewer has checked that, if needed, the PR includes the label `changelog:added`, `changelog:fixed`, or `changelog:changed`, and the title is usable as a changelog entry

### CODE REVIEW

**Comment by danyf90** [comment]
@Hotzenplotz1337 Could you please try if this fixes your issue?

You can try by running from this branch:
```
swift run tuist generate --path=<path-to-your-project>
```

**Review by fortmarek — APPROVED** [review]

**Comment by Thirdeyebind** [comment]
Civil rights. Education. Privacy. The right to know and understand your own legal matters even if it causes people to stop and reconsider THEIR ACTIONS- is absolutely necessary.

Sent from my iPhone

On Oct 12, 2023, at 11:09 PM, Denis R. ***@***.***> wrote:

﻿

I can verify it resolves the problem

[image]<https://user-images.githubusercontent.com/630532/274810711-01be92a2-7923-4561-8367-091d410eb7d7.png>

Thanks for your fast response on this! Great job

**Review by pepicrft — APPROVED** [review]

**Comment by Hotzenplotz1337** [comment]
Thank you a lot guys for the fast fix, great job!

**Comment by acosmicflamingo** [comment]
@ramden can you verify if the problem reappears if your .xcassets directory contains only symbol images? I'm seeing on my end that the functionality below "Implementation Details" is completely missing when I only have symbol images:

```swift
// swiftlint:disable all
// swift-format-ignore-file
// swiftformat:disable all
// Generated using tuist — https://github.com/tuist/tuist

#if os(macOS)
  import AppKit
#elseif os(iOS)
  import UIKit
#elseif os(tvOS) || os(watchOS)
  import UIKit
#endif
#if canImport(SwiftUI)
  import SwiftUI
#endif

// swiftlint:disable superfluous_disable_command file_length implicit_return

// MARK: - Asset Catalogs

// swiftlint:disable identifier_name line_length nesting type_body_length type_name
public enum HomeFeatureAsset {
  public static let goBack = HomeFeatureImages(name: "GoBack")
  public static let symbol = HomeFeatureImages(name: "Symbol")
}
// swiftlint:enable identifier_name line_length nesting type_body_length type_name

// MARK: - Implementation Details

// swiftlint:enable all
// swiftformat:enable all

```

However, it all seems to work if I have at least 1 non-symbol asset in my .xcassets folder: 
```swift
// swiftlint:disable all
// swift-format-ignore-file
// swiftformat:disable all
// Generated using tuist — https://github.com/tuist/tuist

#if os(macOS)
  import AppKit
#elseif os(iOS)
  import UIKit
#elseif os(tvOS) || os(watchOS)
  import UIKit
#endif
#if canImport(SwiftUI)
  import SwiftUI
#endif

// swiftlint:disable superfluous_disable_command file_length implicit_return

// MARK: - Asset Catalogs

// swiftlint:disable identifier_name line_length nesting type_body_length type_name
public enum HomeFeatureAsset {
  public static let clapper = HomeFeatureImages(name: "Clapper")
  public static let goBack = HomeFeatureImages(name: "GoBack")
  public static let symbol = HomeFeatureImages(name: "Symbol")
}
// swiftlint:enable identifier_name line_length nesting type_body_length type_name

// MARK: - Implementation Details

public struct HomeFeatureImages {
  public fileprivate(set) var name: String

  #if os(macOS)
  public typealias Image = NSImage
  #elseif os(iOS) || os(tvOS) || os(watchOS)
  public typealias Image = UIImage
  #endif

  public var image: Image {
    let bundle = HomeFeatureResources.bundle
    #if os(iOS) || os(tvOS)
    let image = Image(named: name, in: bundle, compatibleWith: nil)
    #elseif os(macOS)
    let image = bundle.image(forResource: NSImage.Name(name))
    #elseif os(watchOS)
    let image = Image(named: name)
    #endif
    guard let result = image else {
      fatalError("Unable to load image asset named \(name).")
    }
    return result
  }

  #if canImport(SwiftUI)
  @available(iOS 13.0, tvOS 13.0, watchOS 6.0, macOS 10.15, *)
  public var swiftUIImage: SwiftUI.Image {
    SwiftUI.Image(asset: self)
  }
  #endif
}

public extension HomeFeatureImages.Image {
  @available(macOS, deprecated,
    message: "This initializer is unsafe on macOS, please use the HomeFeatureImages.image property")
  convenience init?(asset: HomeFeatureImages) {
    #if os(iOS) || os(tvOS)
    let bundle = HomeFeatureResources.bundle
    self.init(named: asset.name, in: bundle, compatibleWith: nil)
    #elseif os(macOS)
    self.init(named: NSImage.Name(asset.name))
    #elseif os(watchOS)
    self.init(named: asset.name)
    #endif
  }
}

#if canImport(SwiftUI)
@available(iOS 13.0, tvOS 13.0, watchOS 6.0, macOS 10.15, *)
public extension SwiftUI.Image {
  init(asset: HomeFeatureImages) {
    let bundle = HomeFeatureResources.bundle
    self.init(asset.name, bundle: bundle)
  }

  init(asset: HomeFeatureImages, label: Text) {
    let bundle = HomeFeatureResources.bundle
    self.init(asset.name, bundle: bundle, label: label)
  }

  init(decorative asset: HomeFeatureImages) {
    let bundle = HomeFeatureResources.bundle
    self.init(decorative: asset.name, bundle: bundle)
  }
}
#endif

// swiftlint:enable all
// swiftformat:enable all

```

**Pull request merged**
