### PR TITLE
Update dependencies.md

### PR DESCRIPTION
**Pull request by sonuvryahoo**
### Added a preposition(in) to the docs. 📝

> I think a grammatical error had crept in.

### Checklist
- ✅ The code architecture and patterns are consistent with the rest of the codebase.
- ✅ The changes have been tested following the [documented guidelines](https://docs.tuist.io/contributors/testing-strategy/).
- ✅ The `CHANGELOG.md` has been updated to reflect the changes. In case of a breaking change, it's been flagged as such.
- ✅ In case the PR introduces changes that affect users, the documentation has been updated.

### CODE REVIEW

**Review by fortmarek — APPROVED** [review]

**Comment by fortmarek** [comment]
Thanks, appreciated!

**Comment by fortmarek** [comment]
The pipeline is not green, could you try to rebase from `main` and/or re-run the checks? 🙏

**Comment by pepibumur** [comment]
@all-contributors add @sonuvryahoo for typo

**Comment by pepibumur** [comment]
@all-contributor add @sonuvryahoo for doc

**Comment by pepibumur** [comment]
@fortmarek considering they are documentation changes, I think it's safe to merge even with red CI.

**Pull request merged**
