### PR TITLE
fix: Making build cache continue on error's

### PR DESCRIPTION
**Pull request by apps4everyone**
Resolves https://github.com/tuist/tuist/issues/YYY
Request for comments document (if applies):

### Short description 📝

Making build cache continue on error's

### Checklist ✅

- [x] The code architecture and patterns are consistent with the rest of the codebase.
- [x] The changes have been tested following the [documented guidelines](https://docs.tuist.io/contributors/testing-strategy/).
- [x] The `CHANGELOG.md` has been updated to reflect the changes. In case of a breaking change, it's been flagged as such.
- [x] In case the PR introduces changes that affect users, the documentation has been updated.

### CODE REVIEW

**Comment by pepibumur** [comment]
Thanks for bringing this up @apps4everyone. I'm a bit inclined towards not allowing this because we'd allow warming the cache using as a source a project that is not valid, considering as an invalid project a project where not all its components compile successfully. If you don't mind sharing more about your use-case, we might be able to provide a different solution, for example, warming the cache with only a subset of the modules.

**Comment by apps4everyone** [comment]
> Thanks for bringing this up @apps4everyone. I'm a bit inclined towards not allowing this because we'd allow warming the cache using as a source a project that is not valid, considering as an invalid project a project where not all its components compile successfully. If you don't mind sharing more about your use-case, we might be able to provide a different solution, for example, warming the cache with only a subset of the modules.

the project can still be valid, only one module is not compiling to XCFramework but as normal framework target, so only cache is failing...

my use error is a a external vendor lib inside our module is not compiled with the same swift version:

failed to build module ‘XYZ’ from its module interface; the compiler that produced it, ’Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)’, may have used features that aren’t supported by this compiler, ’Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)

**Comment by fortmarek** [comment]
> the project can still be valid, only one module is not compiling to XCFramework but as normal framework target, so only cache is failing...

as a workaround, you can use `tuist cache` without `--xcframeworks` flag? 

I am also inclined not to skip these errors because we cannot be sure if `tuist cache`'s output is actually correct if we merged this PR.

**Comment by apps4everyone** [comment]
> > the project can still be valid, only one module is not compiling to XCFramework but as normal framework target, so only cache is failing...
> 
> as a workaround, you can use `tuist cache` without `--xcframeworks` flag?
> 
> I am also inclined not to skip these errors because we cannot be sure if `tuist cache`'s output is actually correct if we merged this PR.

have to use XCFrameworks to use them as binaryTargets mentioned here:
https://github.com/tuist/tuist/pull/2888

**Comment by apps4everyone** [comment]
> > > the project can still be valid, only one module is not compiling to XCFramework but as normal framework target, so only cache is failing...
> > 
> > 
> > as a workaround, you can use `tuist cache` without `--xcframeworks` flag?
> > I am also inclined not to skip these errors because we cannot be sure if `tuist cache`'s output is actually correct if we merged this PR.
> 
> have to use XCFrameworks to use them as binaryTargets mentioned here:
> #2888

Currently also all Targets are build in the Cache folder until the error throws, right? So tuist focus is till using the successful generated ones? 

What if you have a tree like this:

     	Main Target
   Target A    Target B
   
 And A is failing? B can still be cached right? So my idea was to continue and only build Target A from source...
 
Maybe a opt in bool `continueOnError` would help both? And we could document the expected behaviour?

**Pull request closed without merging**
