### PR TITLE
[Cache] Remove unneeded `BUILD_LIBRARY_FOR_DISTRIBUTION` setting when caching

### PR DESCRIPTION
**Pull request by danyf90**
Resolves https://github.com/tuist/tuist/issues/2635

Request for comments document (if applies):

### Short description 📝

Enabling swift evolution makes some builds fail

### Checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase.
- [ ] The changes have been tested following the [documented guidelines](https://docs.tuist.io/contributors/testing-strategy/).
- [ ] The `CHANGELOG.md` has been updated to reflect the changes. In case of a breaking change, it's been flagged as such.
- [ ] In case the PR introduces changes that affect users, the documentation has been updated.

### CODE REVIEW

**Review by mstfy — APPROVED** [review]
Looks good 🥳

**Review by pepibumur — APPROVED** [review]

**Comment by sisoje** [comment]
what if i want BUILD_LIBRARY_FOR_DISTRIBUTION ?

**Comment by danyf90** [comment]
> what if i want BUILD_LIBRARY_FOR_DISTRIBUTION ?

Caching is for development, so it's not supported right now

**Comment by sisoje** [comment]
this should be configurable and not enforced by someones opinion

can I set it to "yes" by giving it extra `xcarg` somehow?

**Comment by danyf90** [comment]
> this should be configurable and not enforced by someones opinion

It's not someone's opinion, it's just that in its current form it doesn't work for release.
If you want to contribute and fix that, feel free to do it

**Pull request merged**
