### PR TITLE
Update generators to use the traverser

### PR DESCRIPTION
**Pull request by pepibumur**
### Short description 📝
Continuing with the migration to `ValueGraph`, I'm updating all the components that are involved in the generation of the Xcode project to take a `GraphTraversing` instead of a `Graph` instance.

Note that the loading and the mapping loads a `Graph`, and we turn it into a `ValueGraph` that we use then to initialize the `ValueGraphTraverser`. Also, I have accommodated the tests to the change, but they still depend on `Graph`. In a follow-up PR I plan to update them to initialize a `ValueGraph` directly, instead of creating a `Graph` and then turning it into a `ValueGraph`.

### CODE REVIEW

**Review by laxmorek — APPROVED** [review]

**Comment by kwridan** [comment]
I've pushed a small PR #2111 that fixes one of the failures caught by the acceptance tests here.

**Comment by kwridan** [comment]
Will point our generator tool (which depends on `TuistGenerator`) to this branch and run its test suite against it to see if there are any other bits we missed.

**Comment by pepibumur** [comment]
> Will point our generator tool (which depends on TuistGenerator) to this branch and run its test suite against it to see if there are any other bits we missed.

That'd be great. Let me know how that goes.

**Comment by kwridan** [comment]
All tests passes! 🎉

Spotted a small diff in the generated projects with `targetDependencies` within the `.pbxproj` where the order was slightly different in some our projects but as long as it stable (which it is) it's fine.

**Comment by pepibumur** [comment]
> Spotted a small diff in the generated projects with dependencies within the .pbxproj where the order was slightly different in some our projects but as long as it stable (which it is) it's fine.

That's awesome! I spotted where the issue might be so I pushed a commit fixing it.

**Pull request merged**
