### PR TITLE
Update `swift-argument-parser`: `.upToNextMajor(from: "0.4.3")` -> `.upToNextMajor(from: "1.0.0")`.

### PR DESCRIPTION
**Pull request by laxmorek**
Update `swift-argument-parser`: `.upToNextMajor(from: "0.4.3")` -> `.upToNextMajor(from: "1.0.0")`.

Release notes: https://github.com/apple/swift-argument-parser/releases/tag/1.0.0

Is it worth to mention in the changelog? 🤔

### CODE REVIEW

**Review by danyf90 — APPROVED** [review]
Remember to update also the other Package.resolved!

**Comment by laxmorek** [comment]
I updated the `Dependencies.swift` file and called updating using the `tuist dependencies update`. As a side effect a few other dependencies were updated too. Is it ok to push it with this PR?

**Comment by danyf90** [comment]
tuist dependencies fetch was enough to avoid updating the others :)
If you have updated them here you also need the same for the main replaced file

**Comment by laxmorek** [comment]
It should be correct now 🤞

**Review by fortmarek — APPROVED** [review]
Could you also put this in the changelog? Otherwise, I think we are good to merge this 🎉

**Review by danyf90 — APPROVED** [review]

**Pull request merged**
