### PR TITLE
Support for `xpc` product type on `macOS`

### PR DESCRIPTION
**Pull request by serejahh**
### Short description 📝

1. Added `xpc` product type
2. Updated linting for `xpc`
3. Added a fixture project 

XPC is a kinda CLI, but cannot be run directly in Xcode.

#### Tests

🙏 Let me know if I need to add some unit tests

### How to test the changes locally 🧐

Run `tuist generate` for _macos_app_with_xpc_ project 

### Contributor checklist ✅

- [ ] The code has been linted using run `./fourier lint tuist --fix`
- [ ] The change is tested via unit testing or acceptance testing, or both
- [ ] The title of the PR is formulated in a way that is usable as a changelog entry
- [ ] In case the PR introduces changes that affect users, the documentation has been updated

### Reviewer checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase
- [ ] Contributors have checked that, if needed, the PR includes the label `changelog:added`, `changelog:fixed`, or `changelog:changed`, and the title is usable as a changelog entry

### CODE REVIEW

**Review by danyf90 — APPROVED** [review]

**Comment by serejahh** [comment]
Having a look at failed tests

**Review by kwridan — COMMENTED** [review]
Thanks for adding this @serejahh 

For completeness, we'll need to generate the appropriate build phase to support installing the XPC service without needing to rely on a custom script for anyone needing to adopt this.

Xcode adds the following builds phase:
xpc-buildphase

```
/* Begin PBXCopyFilesBuildPhase section */
		FBFAC4A829B7245B001B9867 /* Embed XPC Services */ = {
			isa = PBXCopyFilesBuildPhase;
			buildActionMask = 2147483647;
			dstPath = "$(CONTENTS_FOLDER_PATH)/XPCServices";
			dstSubfolderSpec = 16;
			files = (
				FBFAC4A429B7245B001B9867 /* MyXPCService.xpc in Embed XPC Services */,
			);
			name = "Embed XPC Services";
			runOnlyForDeploymentPostprocessing = 0;
		};
/* End PBXCopyFilesBuildPhase section */
```

**Comment by serejahh** [comment]
@kwridan Could you guide me to the correct way to add it? I tried to add it within copy phases, but it doesn't help. Do I need to extend the generate phases in the tuist?

**Comment by kwridan** [comment]
Ya, my thinking was extending `BuildPhaseGenerator` to cater for this use case when applicable.

**Review by kwridan — APPROVED** [review]
Awesome, thank you for the update @serejahh 👍 

It will now work out of the box without needing any custom scripts and is much closer to how Xcode sets this up 🎉

**Comment by danyf90** [comment]
@serejahh could you please fix the linting? 🙏

**Comment by serejahh** [comment]
Thanks for fixing that!

**Pull request merged**
