### PR TITLE
Fix swiftlint issues and make sure it runs on CI

### PR DESCRIPTION
**Pull request by pepibumur**
Resolves https://github.com/tuist/tuist/issues/212

### Short description 📝
This PR fixes all the issues reported by Swiftlint and adds two Rake tasks to run the linter and correct the issues.

### CODE REVIEW

**Comment by pepibumur** [comment]
I think the reason why you didn't see anything reported on your PRs is that Danger didn't run because CircleCI didn't pass the GitHub token. Let's see if we get the report on this PR.

**Comment by kwridan** [comment]
Running it locally I still get a few violations actually

```
Done linting! Found 31 violations, 0 serious in 141 files.
```

**Comment by ollieatkinson** [comment]
> Running it locally I still get a few violations actually
> 
> ```
> Done linting! Found 31 violations, 0 serious in 141 files.
> ```

What version of swiftlint are you running ?

**Comment by pepibumur** [comment]
> Running it locally I still get a few violations actually

That's weird. Maybe we are using different version of swiftlint @kwridan. I'm using the version 0.30.1, which one are you using?

> Looks good! It's just a suggestion but maybe we could try to be "warning free" :) by treating all violations as errors? Warnings return 0 code and would pass CI. Little tweaks to `.swiftlint.yml` file should fix it. What do you think?

I like the idea of being more strict when it comes to code style. Warnings tend to be ignored because it doesn't prevent the work from being merged into master. I'll update the configuration accordingly. Thanks for the idea @marciniwanicki

**Comment by kwridan** [comment]
currently running 0.30.1 

```
$ swiftlint version
0.30.1
```

The issues it flagged are warnings as opposed to errors

**Comment by pepibumur** [comment]
I've updated the PR to run swiftlint with the `--strict` flag. CI is happy about the changes so I'm merging this one 😛

**Pull request merged**
