### PR TITLE
Swift 5 support

### PR DESCRIPTION
**Pull request by pepibumur**
Resolves https://github.com/tuist/tuist/issues/316

### Short description 📝
Adds support for Swift 5

### Implementation 👩‍💻👨‍💻
- [x] Update xcodeproj dependency *(which has been renamed to XcodeProj)*
- [x] Fix a failing test.
- [x] Change references to Swift 4.2.1 to Swift 5
- [x] Don't error if both, the local and remote versions of Swift are greater or equal than 5.0.

### CODE REVIEW

**Comment by ollieatkinson** [comment]
Do we need to update SwiftPM to the latest branch which includes swift 5.0?

**Comment by ollieatkinson** [comment]
`Constants.swiftVersion` needs changing to 5.0

**Comment by ollieatkinson** [comment]
Do we need to update `swift-tools-version` to `5.0` inside of `Package.swift` ?

**Comment by ollieatkinson** [comment]
We need to remove `--static-swift-stdlib` from Makefile `package-release`

```sh
$ swift build --static-swift-stdlib
warning: Swift compiler no longer supports statically linking the Swift libraries. They're included in the OS by default starting with macOS Mojave 10.14.4 beta 3. For macOS Mojave 10.14.3 and earlier, there's an optional Swift library package that can be downloaded from "More Downloads" for Apple Developers at https://developer.apple.com/download/more/
```

**Comment by ollieatkinson** [comment]
```sh
$ bundle exec rake features
```

The above command is failing on CI when building the App scheme.

It's failing because of this error:

```sh
$ xcodebuild -scheme App -workspace fixtures/ios_app_with_custom_workspace/Workspace.xcworkspace clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
Build settings from command line:
    CODE_SIGN_IDENTITY =
    CODE_SIGNING_REQUIRED = NO

note: Using new build system

** CLEAN SUCCEEDED ** [0.146 sec]

note: Using new build system
note: Planning build
note: Constructing build description
Build system information
error: An empty identity is not valid when signing a binary for the product type 'Application'. (in target 'App')

** BUILD FAILED **
```

Looks like we need to add this flag when executing xcodebuild:

```
CODE_SIGNING_ALLOWED=NO
```

**Comment by kwridan** [comment]
The last remaining error within the fixtures is 

```
Then tuist generates reports error "❌ Error: Manifest not found at path ${ARG_PATH}"             # features/step_definitions/shared/tuist.rb:17
      --- expected
      +++ actual
      @@ -1 +1 @@
      -"❌ Error: Manifest not found at path /var/folders/1b/gl7yt7ds26vcyr1pkgld6l040000gn/T/d20190406-21702-1usrw2x"
      +"[1/1] Linking ./.build/x86_64-apple-macosx/debug/tuist"
       (Minitest::Assertion)
      ./features/step_definitions/shared/tuist.rb:21:in `/tuist generates reports error "(.+)"/'
      features/generate.feature:32:in `Then tuist generates reports error "❌ Error: Manifest not found at path ${ARG_PATH}"'
```

Seems the `swift run` call for that test is triggering a rebuild (only on CI) and resulting in the output not purely being the error message.

**Comment by pepibumur** [comment]
🤔 why does it expect `${ARG_PATH}` instead of the actual path?

**Comment by kwridan** [comment]
Reading through the release notes we could use `swift test` to gather coverage data now:

> The swift test command can generate code coverage data in a standard format suitable for consumption by other code coverage tools using the flag --enable-code-coverage. The generated code coverage data is available inside <build-dir>/<configuration>/codecov. (44567442)

**Comment by pepibumur** [comment]
> Reading through the release notes we could use swift test to gather coverage data now:

Good point. Then we don't need to generate the project and run the tests on it anymore. That was the only reason why we generated the project before running the tests.

**Comment by freak4pc** [comment]
Does this actually work? I was just experimenting with `tuist` but getting a 

```
No local versions available. Installing the latest version 0.13.0
Verifying the Swift version is compatible with your version 5.0
❌ Error: Found 5.0 Swift version but expected 4.2.1
```

**Comment by ollieatkinson** [comment]
@freak4pc 0.13.0 does not contain the fix for Swift 5, you can point to master by running:

```sh
tuist local master
```

Then running your command again. 
If you want to wait, then Swift 5 support will be available in the next release of tuist 0.14.0.

**Comment by freak4pc** [comment]
Doesn't seem to work for me. I'll try building with `swift -c release` locally. 

image

**Comment by kwridan** [comment]
> Doesn't seem to work for me. I'll try building with `swift -c release` locally.
> 
> image

Good catch, `TuistEnvKit` (component responsible for updates) may need an update for Swift 5 too. Created an issue for it.

**Pull request merged**
