### PR TITLE
Fix the test host path on macOS

### LINKED ISSUE #2033: Wrong TEST_HOST on macOS
**Describe the bug**
Wrong test host is generated on macOS

**To Reproduce**

1. `git clone git@github.com:akargona/CombineMarbles.git`
2. `tuist generate`
3. `open CombineMarbles.xcodeproj`
4. Run CombineMarblesTests_macos
5. See the error

**Expected behavior**
Error TEST_HOST not found.

**Screenshots**
image
image

**Desktop (please complete the following information):**

- OS: macOS 11.0.1 (20B29)
- Version: 1.24.0

**Additional context**
The support for this was implemented in PR GH-300

### PR DESCRIPTION
**Pull request by ferologics**
Resolves #2033

### Short description 📝
Fixes a bug with test host path on macOS

### Solution 📦
Introduce an if that checks the target platform for macOS that if true appends the missing path components to the test host path.

### Implementation 👩‍💻👨‍💻
- [x] Step 1 - implement it
- [x] Step 2 - make a pr
- [x] Step 3 - add a test for HOST_PATH
- [x] Step 4 - update changelog
- [x] Step 5 - profit 💸

### CODE REVIEW

**Comment by pepibumur** [comment]
@all-contributors add @ferologics for code

**Review by pepibumur — APPROVED** [review]
Thanks for fixing this @ferologics. Would you mind adding a test and updating the CHANGELOG? We can merge afterward if CI is green. By the way, in order to fix the lining issues, you can run:

```bash
bundle install
bundle exec rake style_correct
```

**Comment by ferologics** [comment]
Totally @pepibumur, will update later today/tomorrow with the test and CHANGELOG.

**Comment by ferologics** [comment]
Updated with the test @pepibumur 👍

**Review by pepibumur — APPROVED** [review]

**Pull request merged**
