### PR TITLE
Fix mise exec tuist generate in documentation

### PR DESCRIPTION
**Pull request by HossamYoussof**
### Short description 📝

mise changed [exce command](https://mise.jdx.dev/getting-started.html#_3-using-mise) from `mise x` to **`mise exec --`** or **`mise x --`**,  I selected **`mise exec --`** for readability 

### Contributor checklist ✅

- [ ] The code has been linted using run `mise run lint-fix`
- [ ] The change is tested via unit testing or acceptance testing, or both
- [ ] The title of the PR is formulated in a way that is usable as a changelog entry
- [ ] In case the PR introduces changes that affect users, the documentation has been updated

### Reviewer checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase
- [ ] Reviewer has checked that, if needed, the PR includes the label `changelog:added`, `changelog:fixed`, or `changelog:changed`, and the title is usable as a changelog entry

### CODE REVIEW

**Review by fortmarek — APPROVED** [review]
Thanks for the fix!

**Review by fortmarek — COMMENTED** [review]
Thanks! I believe changes should be limited to the docs files in `en` – otherwise, our localization platform might be confused. We can merge afterwards 🙂

**Review by pepicrft — APPROVED** [review]

**Comment by pepicrft** [comment]
@all-contributors add @HossamYoussof for docs

**Comment by pepicrft** [comment]
Thanks @HossamYoussofhttps for the fix here :).

**Pull request merged**
