### PR TITLE
Reuse HTTP connection when interacting with Tuist Cloud

### PR DESCRIPTION
**Pull request by pepicrft**
### Short description 📝
I'm updating the version of `TuistCloud` to ensure that the HTTP connection is used across all the HTTP requests that are sent to the server when interacting with the caching APIs.

### CODE REVIEW

**Review by fortmarek — APPROVED** [review]
I'd just appreciate if we could wait for the CI to finish. I'm waiting for the CI to pass [here](https://github.com/tuist/tuist/pull/5501) and this will cause a conflict.

In general, updating this file often is going to be slightly painful given how long our CIs take and that it will cause merge conflicts really often.

I wonder if we can specify `main` here which will point to the latest commit in `main` instead of always having to change the commit hash here. It does mean we will pull in newer version of `TuistCloud` without being explicit and ideally, whenever we change something in `tuist/TuistCloud`, we should run the whole set of tests in `tuist/tuist` to make sure we don't merge something invalid there.

**Comment by pepicrft** [comment]
> I'd just appreciate if we could wait for the CI to finish. I'm waiting for the CI to pass https://github.com/tuist/tuist/pull/5501 and this will cause a conflict (and I'd have to re-run it again).

Sure! No need to merge this one in a rush

> In general, updating this file often is going to be slightly painful given how long our CIs take and that it will cause merge conflicts really often.

Indeed, this is something that we can configure to mitigate conflicts. I'll add a configuration for that.

> I wonder if we can specify main here which will point to the latest commit in main instead of always having to change the commit hash here. It does mean we will pull in newer version of TuistCloud without being explicit and ideally, whenever we change something in tuist/TuistCloud, we should run the whole set of tests in tuist/tuist to make sure we don't merge something invalid there.

I'd rather keep it because our release pipeline generates the changelogs for releases with the information from PRs. If we stop opening PRs, and instead use the latest code in `main`, we'll miss all the cloud changes in the release notes. We could solve this by making the release process absorbed additional complexity, but I'm inclined to not do it and instead keep a clean history of changes here, even if PRs reference pieces of code that live elsewhere.

**Review by danyf90 — APPROVED** [review]

**Comment by pepicrft** [comment]
[This](https://github.com/tuist/tuist/pull/5509/files#diff-618cd5b83d62060ba3d027e314a21ceaf75d36067ff820db126642944145393eR4) should remove the inconvenience of having multiple branches updating the version and leading to conflicts in PRs @fortmarek

**Comment by fortmarek** [comment]
Awesome, thanks, Pedro! This should suffice for now 👍

**Pull request merged**
