### PR TITLE
Add configuration option to control location of SPM clones with Xcode native integration

### PR DESCRIPTION
**Pull request by victor-sarda**
Resolves: no issue raised (happy to do so if needed). See the Slack discussion [here](https://tuistapp.slack.com/archives/CCXC295QS/p1683878879654209)

### Short description 📝

I'm basically re-opening this pull request: https://github.com/tuist/tuist/pull/3628
It was closed due to no activity. After asking on Slack, it turns out there's no reason not to implement the change. It seems like other people would use it on projects that don't use `Dependencies.swift`

### How to test the changes locally 🧐

- Create an app using Tuist
- Add one or more package dependencies **without** using Dependencies.swift (with the `packages` parameter in `Project`)
- Set a custom `clonedSourcePackagesDirPath` in the project `Config`
- Run `tuist generate` and observe that the packages are cloned in the custom folder path (`<custom-path>/<workspace-name>`)

### Contributor checklist ✅

- [x] The code has been linted using run `./fourier lint tuist --fix`
- [x] The change is tested via unit testing or acceptance testing, or both
- [x] The title of the PR is formulated in a way that is usable as a changelog entry
- [x] In case the PR introduces changes that affect users, the documentation has been updated

### Reviewer checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase
- [ ] Reviewer has checked that, if needed, the PR includes the label `changelog:added`, `changelog:fixed`, or `changelog:changed`, and the title is usable as a changelog entry

### CODE REVIEW

**Comment by marinofelipe** [comment]
very nice addition for those not yet relying on the `Dependencies.swift`, thanks @victor-sarda 🙇

**Review by danyf90 — APPROVED** [review]

**Comment by askapiernicka** [comment]
it's exactly that I am looking for! Thank you @victor-sarda 👏  
@freak4pc @pepicrft  Could you find time to review this PR? 🙇‍♀️

**Comment by victor-sarda** [comment]
Hey guys, could I have some more eyes on this PR? Thanks 🙏 (cc @pepicrft)

**Comment by pepicrft** [comment]
@all-contributors add @victor-sarda for code

**Review by pepicrft — APPROVED** [review]

**Pull request merged**
