### PR TITLE
Uncomment support for iMessage extensions

### PR DESCRIPTION
**Pull request by olejnjak**
### Short description 📝

Tuist is now unable to generate targets for iMessage extensions, right now we had to use `Product.appExtension` which creates incorrect target and then built product ends without AppIcon which is later on reject when uploading to App Store.

I've found that the support is commented out so I just uncommented it and it seems to work. Would it be possible to uncomment this feature? It is crucial for our project which was migrated to tuist, to submit new app version in near future so it would be nice if this could be resolved.

### Solution 📦

Just uncommented code that already existed.

### Implementation 👩‍💻👨‍💻

Just uncommented code that already existed.

### CODE REVIEW

**Comment by olejnjak** [comment]
Sure no problem, I just wanted to see if it could be merged before spending a bit more time with it 🙂

**Comment by kwridan** [comment]
Thanks for the updates @olejnjak 👍  - I was taking another look and it seems we're missing one key bit - I missed this in the initial review 😞

If we generate a project with the messages extension, it's not being included in the `Embed App Extensions` build phase.

Screenshot 2020-07-01 at 06 30 50

I've pushed a fixture to help us test this out.

**Comment by kwridan** [comment]
Think I found the missing change, just pushed it. Worth a sanity check :)

**Comment by olejnjak** [comment]
Nice catch, but I'm wondering how is it possibe that I've actually seen the extension in freshly installed app. 🤦‍♂️

**Comment by olejnjak** [comment]
Yes, embedded correctly 🙂

**Comment by kwridan** [comment]
Are we good to merge this @olejnjak ?

**Comment by olejnjak** [comment]
Yes 🙂

**Pull request merged**
