### PR TITLE
Change the swift version to 4.2

### PR DESCRIPTION
**Pull request by ollieatkinson**
### Short description 📝

* 4.2.1 is an invalid specification for SWIFT_VERSION.

### Solution 📦

* Change default to to 4.2

### CODE REVIEW

**Comment by pepibumur** [comment]
There are some legit issues on CI @ollieatkinson which might be related to your changes.

**Comment by kwridan** [comment]
Good catch!

The fixtures need a small update: 
`UIApplicationLaunchOptionsKey` > `UIApplication.LaunchOptionsKey`

Worth a rebase on master as the fixtures structure has changed slightly.

**Comment by ollieatkinson** [comment]
@kwridan I have rebased and pushed up the changes. @pepibumur Once CI gives it the green I will merge.

**Comment by pepibumur** [comment]
Go ahead @ollieatkinson

**Pull request merged**
