### PR TITLE
Align ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES with the Xcode default

### PR DESCRIPTION
**Pull request by yungu0010**
Resolves <https://github.com/tuist/tuist/issues/6989>

### Short description 📝
I modified the tuist/XcodeProj file to resolve this issue.

### How to test the changes locally 🧐
1. clone XcodeProj project to use local
2. modified local XcodeProj, see this [pr](https://github.com/tuist/XcodeProj/pull/881)
3. modified Package.swift to use local XcodeProj
4. tested in fixtures/workspace_with_test_locale using `tusit generate`

And I also changed Target init in fixtures/workspace_with_test_locale/Project.swift to tusit4.
Please let me know if there's anything wrong.

### Contributor checklist ✅

- [x] The code has been linted using run `mise run lint-fix`
- [ ] The change is tested via unit testing or acceptance testing, or both
- [ ] The title of the PR is formulated in a way that is usable as a changelog entry
- [ ] In case the PR introduces changes that affect users, the documentation has been updated

### Reviewer checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase
- [ ] Reviewer has checked that, if needed, the PR includes the label `changelog:added`, `changelog:fixed`, or `changelog:changed`, and the title is usable as a changelog entry

### CODE REVIEW

**Review by fortmarek — APPROVED** [review]

**Review by fortmarek — DISMISSED** [review]
you'll need to run `mise run lint-fix` to make the formatter pass before we can merge this

**Comment by yungu0010** [comment]
@fortmarek I fixed code to match with swiftformat, please check again and approve

**Comment by yungu0010** [comment]
@waltflanagan @fortmarek Could I ask you to give approve this PR? I checked lint!

**Review by fortmarek — APPROVED** [review]
Thanks for the contribution, that's really appreciated!

**Comment by fortmarek** [comment]
@all-contributors add @yungu0010 for code

**Pull request merged**
