### PR TITLE
Move tuist to projects/tuist

### PR DESCRIPTION
**Pull request by pepibumur**
### Short description 📝
Like I did with other projects with the goal of keeping the monorepo well organized, I'm moving the main Tuist's project to `projects/tuist`.

### CODE REVIEW

**Review by kwridan — CHANGES_REQUESTED** [review]
If I'm not mistaken, Swift Packages need to reside in the root directory of a repository in order to be used by other packages. This would mean we'd no longer be able to use `TuistGenerator` as a Swift Package dependency, which would be very unfortunate 😞

**Comment by kwridan** [comment]
Seeing Tuist is the main component of the repo, it may be ok to keep in the root while moving other supporting tools and projects to nested folders that are exclusively used by Tuist - is there a strong need to move it?

**Comment by pepibumur** [comment]
Ouuch, good catch. Not strong reason honestly, mostly to keep things tidy. Since this is a breaking change for consumers of the package, I'll close the PR.

**Comment by kwridan** [comment]
Thanks @pepibumur

**Pull request closed without merging**
