### PR TITLE
Locate root directory where Workspace.swift file is located

### PR DESCRIPTION
**Pull request by leszko11**
Resolves https://github.com/tuist/tuist/issues/3880

### Short description 📝

Extends `RootDirectoryLocator` to be able to locate root directory where `Workspace.swift` file is located.

The issue with generating `Manifests.xcodeproj` for workspace with multiple projects, was the result of `locate(from:)` method. When there is no `Tuist` or `.git` directory, this method [returns](https://github.com/tuist/tuist/blob/e3e7862c04f98c47d944590a4445722f8cf474d1/Sources/TuistCore/Utils/RootDirectoryLocator.swift#L40C21-L40C21) `path.parentDirectory` which is outside project root directory

### How to test the changes locally 🧐

- use `workspace_with_multiple_projects` fixture
- call `tuist edit`

### Contributor checklist ✅

- [x] The code has been linted using run `make lint-fix`
- [x] The change is tested via unit testing or acceptance testing, or both
- [x] The title of the PR is formulated in a way that is usable as a changelog entry
- [x] In case the PR introduces changes that affect users, the documentation has been updated

### Reviewer checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase
- [ ] Reviewer has checked that, if needed, the PR includes the label `changelog:added`, `changelog:fixed`, or `changelog:changed`, and the title is usable as a changelog entry

### CODE REVIEW

**Comment by leszko11** [comment]
Now I see, that the same thing is happening to the following structure
```
.
├── Project.swift
└── Targets
    └── App
        ├── Sources
        │   └── AppDelegate.swift
        └── Tests
            └── AppTests.swift
```
Do you guys think this is a good way of fixing it?

**Comment by pepicrft** [comment]
> Do you guys think this is a good way of fixing it?

This is what I was thinking about. What makes the most sense for developers? Both, having `Tuist` and a Git repository should be **optional** in my opinion, hence why I think having a fallback in place is necessary. In terms of precedence, I'd expect the following:

```
Project.swit > Workspace.swift > Tuist > .git
```

Here's the rationale:

- If I'm a subdirectory that contains a `Project.swift`, my intention is very likely to focus on that project, so that should take precedence over a workspace that contains this project.
- If I'm higher in the directory structure, I'd probably want to generate through umbrella structures such as Workspaces or a `Tuist/` project.
- `.git` is a fallback if none of the above mechanisms work.

I wonder if the above would be a breaking change for any of the existing workflows or users' expectations. One thing that I believe is critical is to ensure the behavior is overrideable, which I believe should be via the `--path` flag. When I use that flag as a user I mean: don't traverse, just use whatever you have in this directory.

**Comment by leszko11** [comment]
@pepicrft thanks for your comment 🙏 
So you mean something like [this](https://github.com/tuist/tuist/pull/5499/commits/7e2e991d2dfcb938fa14b5aa4ede789a44f14a0b)?

`tuist edit` has already `--path` argument and `-o` flag as well

**Comment by pepicrft** [comment]
> So you mean something like [this](https://github.com/tuist/tuist/pull/5499/commits/7e2e991d2dfcb938fa14b5aa4ede789a44f14a0b)?

Right. I'd wait to see what @tuist/core thinks about the change. They might be able to point out side effects of this decision that we should be aware of.

**Comment by danyf90** [comment]
LGTM

**Review by pepicrft — APPROVED** [review]

**Comment by pepicrft** [comment]
@leszko11 some unit tests seem to be failing due to the changes :)

**Comment by leszko11** [comment]
@pepicrft And I think it's good they fail! Take a look at `test_locateProjectManifests_returns_all_manifest_no_workspace_given_child_path` test. We have the following structure
```
.
├── Module
│   └── Project.swift
├── Project.swift
└── Tuist
    └── Config.swift
```

In this test, we're calling `locateProjectManifests` at `Module/Project.swift`.
According to what you said earlier:

> If I'm a subdirectory that contains a Project.swift, my intention is very likely to focus on that project, so that should take precedence over a workspace that contains this project.

So only `Module/Project.swift` manifest should be located, but the test expect both manifests

**Comment by leszko11** [comment]
Regarding 2 last failing tests - I,ll take a look on them later today/tomorrow

**Comment by leszko11** [comment]
Using `Project.swift` as a root was not that straightforward. For `tuist edit` command it was working fine, but it was messing up with finding a valid root for `tuist generate` command.
I introduced a new init for `RootDirectoryLocating` protocol, which defines if `Project.swift` file should be used to locate the root.

Please let me know if the introduced changes look good 🙏

**Comment by fortmarek** [comment]
@all-contributors add @leszko11 for code

**Pull request merged**
