### PR TITLE
Add ios app dependency to bundle target

### PR DESCRIPTION
**Pull request by anastasiapast**
Resolves https://github.com/tuist/tuist/issues/5394

### Short description 📝
For correct [EarlGrey](https://github.com/google/EarlGrey/blob/earlgrey2/docs/open-boxing-setup-guide.md) installation we need to add `.bundle` target dependencies description to `GraphLinter.swift` file. 
For now it's just `.app` target.
I've added support for both `.macOS` and `.iOS` bundle 

### Contributor checklist ✅

- [x] The code has been linted using run `./fourier lint tuist --fix`
- [x] The change is tested via unit testing or acceptance testing, or both
- [x] The title of the PR is formulated in a way that is usable as a changelog entry
- [x] In case the PR introduces changes that affect users, the documentation has been updated

### Reviewer checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase
- [ ] Reviewer has checked that, if needed, the PR includes the label `changelog:added`, `changelog:fixed`, or `changelog:changed`, and the title is usable as a changelog entry

### CODE REVIEW

**Comment by danyf90** [comment]
Thanks @anastasiapast, would you mind changing one of the fixtures to make sure this works and continues to work on a real project? 🙏

**Comment by anastasiapast** [comment]
Hi @danyf90, thank you for response. I'm not familiar with structure of the project, could you point me to the fixture where changes should be applied? 🙂

**Comment by danyf90** [comment]
> Hi @danyf90, thank you for response. I'm not familiar with structure of the project, could you point me to the fixture where changes should be applied? 🙂

Sure!
You can enhance [this sample project](https://github.com/tuist/tuist/tree/940a80ef9b4c7a47dbe23debf614fc64eaeff2b6/projects/tuist/fixtures/app_with_spm_dependencies) to include the dependency with which you were having problems.
That project is then generated and built in [our acceptance tests](https://github.com/tuist/tuist/blob/95fe8a6df65317d7339fa1f2b2634799b4372962/projects/tuist/features/dependencies.feature#L11) to make sure it continues to work after any change

**Review by kwridan — CHANGES_REQUESTED** [review]
Thanks @anastasiapast for contributing this.

`bundle` targets depending on applications outside of the EarlGrey use case for `iOS` isn't valid to my knowledge 🤐 

The use of EarlGrey requires a few extra steps which Tuist doesn't support beyond the lint rules:

- Weakly linking targets
- Adding sources to `bundle` targets (especially for iOS)

Both of which aren't supported by tuist 😞

For the moment I'm inclined to not modify the lint rules as it still won't help achieve the desired goal of supporting EarlGrey. We'd need to figure out a alternate mechanism to support some of these use cases that deviate from the standard.

For reference this was brought up in the past https://github.com/tuist/tuist/issues/4640

**Comment by anastasiapast** [comment]
Thank you for the response @kwridan. It's a bit sad to hear that EarlGrey isn't supported by Tuist now, do you have any plans of supporting these features in the future?

**Comment by pepicrft** [comment]
> Thank you for the response @kwridan. It's a bit sad to hear that EarlGrey isn't supported by Tuist now, do you have any plans of supporting these features in the future?

There are some ideas on the table, one of them being exposing some post-generation hook that users can leverage to modify the Xcode project that Tuist would generate. Unfortunately, I can't give estimates around when that'll be implemented.
Until then, I recommend that you wrap the generation through Tuist in your own script and add the target dependency manually using [XcodeProj](https://github.com/tuist/xcodeproj). Here's some pseudo-code to guide you in that effort:

```swift
import XcodeProj

func addDependency(to targetName: String, dependency: String, in projectPath: String) throws {
    // Load the project
    let project = try XcodeProj(path: .init(projectPath))
    let pbxproj = project.pbxproj

    // Find the main target and dependency target
    guard let target = pbxproj.targets(named: targetName).first, let dependencyTarget = pbxproj.targets(named: dependency).first else {
        print("Failed to find the target or its dependency.")
        return
    }

    // Add the dependency
    let targetDependency = PBXTargetDependency(target: dependencyTarget)
    pbxproj.add(object: targetDependency)
    target.dependencies.append(targetDependency)

    // Save the changes back to the xcodeproj
    try project.write(path: .init(projectPath))
}

// Call the function
do {
    try addDependency(to: "YourTargetName", dependency: "YourDependencyTargetName", in: "/path/to/YourProject.xcodeproj")
    print("Dependency added successfully!")
} catch {
    print("An error occurred: \(error)")
}
```

**Pull request closed without merging**
