### PR TITLE
[Fix] Allow static frameworks as dependencies of an appExtension

### PR DESCRIPTION
**Pull request by danyf90**
Resolves https://github.com/tuist/tuist/issues/2523

### Short description 📝

Allows `staticFramework`s to be used as dependency of an `appExtension`

### Checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase.
- [ ] The changes have been tested following the [documented guidelines](https://tuist.io/docs/contribution/testing-strategy/).
- [ ] The `CHANGELOG.md` has been updated to reflect the changes. In case of a breaking change, it's been flagged as such.
- [ ] In case the PR introduces changes that affect users, the documentation has been updated.

### CODE REVIEW

**Comment by danyf90** [comment]
@fortmarek to have a fixture that tests this, can I expand the `ios_app_with_extensions`, or should I create a new one?

**Comment by fortmarek** [comment]
> to have a fixture that tests this, can I expand the ios_app_with_extensions, or should I create a new one?

you can just extend the existing one 🙂

**Comment by danyf90** [comment]
@fortmarek added StaticFramework dependency to ios_app_with_extensions fixture 🤞

**Review by kwridan — APPROVED** [review]
Thanks for the addition @danyf90

**Review by fortmarek — APPROVED** [review]

**Comment by fortmarek** [comment]
please rebase to get rid of the merge conflict, otherwise good to merge 👍

**Pull request merged**
