### PR TITLE
Fix tuist cache warm --xcframeworks of SPM frameworks due to missing macCatalyst availability

### PR DESCRIPTION
**Pull request by MontakOleg**
Resolves https://github.com/tuist/tuist/issues/5230

### Short description 📝

`tuist cache warm --xcframeworks` can't build XCFramework if SPM package does not explicitly specify `macCatalyst` availability. For example, `FirebaseCrashlytics` can't be built by `tuist > 3.18`.

This PR fixes this.

`macCatalyst` should be always available, because platforms in SPM package description can't be used to restrict supported platforms, it only allows customizing the deployment target versions:

>Restricting supported platforms: Some packages are only meant to work on certain platforms. This proposal doesn't provide ability to restrict the list of supported platforms and only allows customizing the deployment target versions. Restricting supported platforms is orthogonal to customizing deployment target and will be explored separately.

https://github.com/apple/swift-evolution/blob/main/proposals/0236-package-manager-platform-deployment-settings.md#future-directions

### How to test the changes locally 🧐

1. Download test project: https://github.com/tuist/tuist/files/11737174/TuistTest.zip
2. Clean cache: `swift run tuist clean --path path/to/downloaded/project`
3. Fetch dependencies: `swift run tuist fetch --path path/to/downloaded/project` // code changes will apply on this step
3. Build xcframework: `swift run tuist cache warm --xcframeworks --path path/to/downloaded/project`

It should successfully build.

### Contributor checklist ✅

- [x] The code has been linted using run `./fourier lint tuist --fix`
- [x] The change is tested via unit testing or acceptance testing, or both
- [x] The title of the PR is formulated in a way that is usable as a changelog entry
- [ ] In case the PR introduces changes that affect users, the documentation has been updated

### Reviewer checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase
- [ ] Reviewer has checked that, if needed, the PR includes the label `changelog:added`, `changelog:fixed`, or `changelog:changed`, and the title is usable as a changelog entry

### CODE REVIEW

**Comment by MontakOleg** [comment]
Why some checks on CI is cancelled? Should we re-run them?

**Comment by MontakOleg** [comment]
CI has failed on unrelated code:
```
  Scenario: The project is an application with templates (ios_app_with_templates)                                                       # projects/tuist/features/scaffold.feature:3
    Given that tuist is available                                                                                                       # projects/tuist/features/step_definitions/shared/tuist.rb:4
    And I have a working directory                                                                                                      # projects/tuist/features/step_definitions/shared/workspace.rb:6
    Then I copy the fixture ios_app_with_templates into the working directory                                                           # projects/tuist/features/step_definitions/shared/fixtures.rb:5
    Then tuist does fetch                                                                                                               # projects/tuist/features/step_definitions/fetch.rb:3
/Users/runner/work/tuist/tuist/.build/release/tuist scaffold custom --path /var/folders/2p/6fxzqc0d64xbxvt_6n0252k40000gn/T/d20230718-2055-gjr131 --name TemplateProject

pid 2093 exit 1
    Then tuist scaffolds a custom template named TemplateProject                                                                        # projects/tuist/features/step_definitions/scaffold.rb:3
      /Users/runner/work/tuist/tuist/.build/release/tuist scaffold custom --path /var/folders/2p/6fxzqc0d64xbxvt_6n0252k40000gn/T/d20230718-2055-gjr131 --name TemplateProject
      /var/folders/2p/6fxzqc0d64xbxvt_6n0252k40000gn/T/d20230718-2055-gjr131/Tuist/ProjectDescriptionHelpers/Platform.swift:5:9: error: switch must be exhaustive
              switch self {
              ^
      /var/folders/2p/6fxzqc0d64xbxvt_6n0252k40000gn/T/d20230718-2055-gjr131/Tuist/ProjectDescriptionHelpers/Platform.swift:5:9: note: add missing case: '.visionOS'
              switch self {
              ^
      Error: The 'swiftc' command exited with error code 1
```

**Comment by MontakOleg** [comment]
Fix is trivial, so I will add it to this PR. Let me know if you prefer to make another PR for it.

**Review by danyf90 — APPROVED** [review]

**Comment by MontakOleg** [comment]
@fortmarek @pepicrft hi guys, could you have a look?

**Review by fortmarek — APPROVED** [review]
Thanks a lot for this change, LGTM :shipit:

**Pull request merged**
