### PR TITLE
Add local tuist plugin to `tuist init` generated project

### PR DESCRIPTION
**Pull request by leszko11**
Resolves https://github.com/tuist/tuist/issues/2996

### Short description 📝

Hi folks!
I've been discovering plugins/tasks functionality recently and I found this issue. Is this enough to resolve @fortmarek requirement?
> provide a "foo" task by default in the project generated by that command

### How to test the changes locally 🧐

- run `tuist init` command in empty directory

### Checklist ✅

- [x] The code architecture and patterns are consistent with the rest of the codebase.
- [x] The changes have been tested following the [documented guidelines](https://docs.tuist.io/contributors/testing-strategy/).
- [ ] The PR includes the label `changelog:added`, `changelog:fixed`, or `changelog:changed`, whenever it should be included in the “Added”, “Fixed” or “Changed” section of the CHANGELOG. Note: when included in the CHANGELOG, the title of the PR will be used as entry, please make sure it is clear and suitable.
- [ ] In case the PR introduces changes that affect users, the documentation has been updated.
- [ ] In case the PR introduces changes that affect how the cache artifact is generated starting from the `TuistGraph.Target`, the `Constants.cacheVersion` has been updated.

### CODE REVIEW

**Review by fortmarek — COMMENTED** [review]
Thanks for the contribution @leszko11!

This should, indeed, be enough, but you can you add `Templates/**` [here](https://github.com/tuist/tuist/blob/main/.github/workflows/tuist.yml#L8), so we run the acceptance tests to get higher confidence this does not break anything (although it shouldn't)?

**Review by fortmarek — APPROVED** [review]
I would maybe suggest adding also some code for `ProjectDescriptionHelpers` in a plugin. Until we support local tasks, you won't be able to trigger `tuist my-cli` successfully until you make a release from that folder.

But it's already good-to-go imho, so will leave it up to you 🙂

**Comment by leszko11** [comment]
Will do!

**Review by danyf90 — CHANGES_REQUESTED** [review]
I wouldn't expect a local plugin to be usually defined together with the tuist project, so I would rather have a parameter to distinguish when we want a plugin instead of a project (e.g. `tuist init --template plugin`)

WDYT? cc @fortmarek

**Comment by fortmarek** [comment]
> I wouldn't expect a local plugin to be usually defined together with the tuist project, so I would rather have a parameter to distinguish when we want a plugin instead of a project (e.g. tuist init --template plugin)

I agree with having a dedicated plugin, although the current solution is a nice way of surfacing the feature. I don't have a strong opinion whether to have it in a dedicated template only or in the default project _and_ in a dedicated template.

**Comment by danyf90** [comment]
> current solution

makes sense 👍

**Review by danyf90 — APPROVED** [review]

**Review by fortmarek — APPROVED** [review]
Looks good 🚀

**Pull request merged**
