### PR TITLE
Update the documentation to show that `--project-only` needs a Boolean parameter

### PR DESCRIPTION
**Pull request by DavidBrunow**
### Short description 📝

Updates some documentation that I came across while testing out Tuist.

### CODE REVIEW

**Comment by pepibumur** [comment]
Hi @DavidBrunow, thanks for bringing this up! I checked the implementation, and `true` shouldn't be necessary. When you pass the argument `--project-only` it should read it as a flag indicating that you want it to be true. Doesn't it work for you?

**Comment by DavidBrunow** [comment]
I’ve been experimenting more with Tuist and I’ve noticed that I see different behavior if I run Tuist from Xcode than if I run it from the zsh command line. From Xcode I do not need the ‘true’ but from the zsh command line I do.

I think I’m running a basic stock zsh in the latest Catalina beta so I don’t think there is anything special about my system. Are you running zsh or bash?

**Comment by pepibumur** [comment]
> I think I’m running a basic stock zsh in the latest Catalina beta so I don’t think there is anything special about my system. Are you running zsh or bash?

I'm using zsh.

**Comment by DavidBrunow** [comment]
Odd -- I cannot recreate the issue now. Going to try a little more to get back to whatever state I was in when I saw the issue.

**Comment by DavidBrunow** [comment]
Figured it out -- I was able to reproduce by setting the local Tuist version to 1.7.1 and clearing the SPM cache in `~/.tuist`.

Closing since I don't see this in newer versions.

**Pull request closed without merging**
