### PR TITLE
Remove sudo requirement from install & uninstall scripts

### PR DESCRIPTION
**Pull request by luispadron**
Resolves https://github.com/tuist/tuist/issues/2806
Request for comments document (if applies):

### Short description 📝

This PR removes the need to require sudo access. This is problematic in contexts where TTY is not available to enter password (such as in CI/CD). This also makes it more clear that the install script isn't doing anything crazy on someones machine that would require sudo.

### Checklist ✅

- [x] The code architecture and patterns are consistent with the rest of the codebase.
- [x] The changes have been tested following the [documented guidelines](https://docs.tuist.io/contributors/testing-strategy/).
- [x] The `CHANGELOG.md` has been updated to reflect the changes. In case of a breaking change, it's been flagged as such.
- [x] In case the PR introduces changes that affect users, the documentation has been updated.

### CODE REVIEW

**Comment by fortmarek** [comment]
Do we know why `sudo` was there in the first place?

**Comment by luispadron** [comment]
@fortmarek Im not entirely sure! @pepibumur would you have more context?

**Review by fortmarek — APPROVED** [review]
I'm OK with this being merged but I would very much curious why it was there in the first place cc @pepibumur

**Review by pepibumur — APPROVED** [review]

**Comment by pepibumur** [comment]
> @fortmarek Im not entirely sure! @pepibumur would you have more context?

@luispadron I remember having issues when running the installation scripts in M1. It'd be great if the scripts could be tested in that environment. If they work I think it's ok to merge this PR.

**Comment by RLovelett** [comment]
This is a bit of a blocker for some to even _use_ Tuist. For instance, in our environment `sudo` is not something we have access to on our managed computers. I worked around this by running the steps of the install script manually.

Also, perhaps adopting a [`$HOME/.local`](https://www.freedesktop.org/software/systemd/man/file-hierarchy.html#Home%20Directory) is also a good fallback if `/usr/bin/local` is not writable by the current user.

**Comment by fortmarek** [comment]
> This is a bit of a blocker for some to even use Tuist. For instance, in our environment sudo is not something we have access to on our managed computers. I worked around this by running the steps of the install script manually.

This is unfortunate! I agree it'd be much better if we got around using `sudo`.

> Also, perhaps adopting a $HOME/.local is also a good fallback if /usr/bin/local is not writable by the current user. I'm less sure I think this is a good general solution. It works for me but I'm not sure it works for everyone.

yeah, I'm not sure how often `/usr/bin/local` is not writable by the user? User could also run the whole install command with `sudo` to get around that, afaict. We could add some error handling checking the access rights for that directory and then showing error with helpful information if it's actually not writable.

Before merging this, we need someone to test this on M1. @luispadron is currently on vacation, but I believe he should return back soon-ish, so we can move forward with this afterwards.

**Comment by pepibumur** [comment]
> Before merging this, we need someone to test this on M1. @luispadron is currently on vacation, but I believe he should return back soon-ish, so we can move forward with this afterwards.

I can test this one on M1 and merge it if everything works as expected.

**Comment by pepibumur** [comment]
I confirm this works successfully on M1 so I'll go ahead and merge the PR.

**Comment by AllDmeat** [comment]
Looks like sudo is required once again. Our CI is broken right now.

Screenshot 2023-01-31 at 15 21 08

**Pull request merged**
