### PR TITLE
Disable tests when pushing on main

### PR DESCRIPTION
**Pull request by danyf90**
You can't merge if tests don't pass on the PR, so running tests on main just steals CI resources from the other PRs.
Also, even if they would fail nobody would probably notice :D

### CODE REVIEW

**Comment by fortmarek** [comment]
> You can't merge if tests don't pass on the PR, so running tests on main just steals CI resources from the other PRs.
Also, even if they would fail nobody would probably notice :D

I think it's worth having tests on `main` since we don't require branches to be up-to-date when merging. So, an issue can actually only come to light on `main` even though the tests in the original branch have passed. I'd be against merging this PR, although I agree freeing up resources for PR runs would have been nice.

**Comment by shahzadmajeed** [comment]
Just curious. We run every commit on main or is it a nightly build?

**Comment by danyf90** [comment]
> Just curious. We run every commit on main or is it a nightly build?

Every commit 👍

**Comment by danyf90** [comment]
> > You can't merge if tests don't pass on the PR, so running tests on main just steals CI resources from the other PRs.
> > Also, even if they would fail nobody would probably notice :D
> 
> I think it's worth having tests on `main` since we don't require branches to be up-to-date when merging. So, an issue can actually only come to light on `main` even though the tests in the original branch have passed. I'd be against merging this PR, although I agree freeing up resources for PR runs would have been nice.

I know it's not completely useless, but I still think they don't bring much value.
Given the volume of PR is low now, let's keep them enabled and reevaluate when CI time becomes a bigger problem

**Pull request closed without merging**
