### PR TITLE
Drop support for Xcode 12.5 and macOS 10.15

### PR DESCRIPTION
**Pull request by adellibovi**
Resolves https://github.com/tuist/tuist/issues/YYY
Request for comments document (if applies):

### Short description 📝

> Describe here the purpose of your PR.

### How to test the changes locally 🧐

> Include a set of steps for the reviewer to test the changes locally.

### Checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase.
- [ ] The changes have been tested following the [documented guidelines](https://docs.tuist.io/contributors/testing-strategy/).
- [ ] The `CHANGELOG.md` has been updated to reflect the changes. In case of a breaking change, it's been flagged as such.
- [ ] In case the PR introduces changes that affect users, the documentation has been updated.
- [ ] In case the PR introduces changes that affect how the cache artifact is generated starting from the `TuistGraph.Target`, the `Constants.cacheVersion` has been updated.

### CODE REVIEW

**Review by fortmarek — COMMENTED** [review]
Changes look good! Why are we not targeting the 3.0 branch, though? I think we wanted to make the change in the major version since we should be relatively close to releasing it.

**Comment by adellibovi** [comment]
@fortmarek , I will change it back to release/3.0 once that branch is synched with main, otherwise there are just too many changes 🙈

**Review by fortmarek — APPROVED** [review]

**Comment by adellibovi** [comment]
@fortmarek and @danyf90 there is a small breaking change in the API, which should be fine, but I want to highlight it.
In `Sources/ProjectDescription/TargetScript.swift`:
```diff
public enum Script: Codable {
-         case tool(_ path: String, _ args: [String] = [])
-         case scriptPath(_ path: Path, args: [String] = [])
+         case tool(path: String, args: [String])
+         case scriptPath(path: Path, args: [String])
```
This is because of a bug in the Swift compiler where the auto synthesised conformance fails if the associated values are not explicit (fails with a compilation error, it is auto-synthesised but as if it was with explicit name, failing on a not found symbol).
Personally I am fine with it since we will release in 3.0, it aligns the `args` name, where in one case was explicit and in the other not and we can get rid of the manual conformance.
Are you okay with this as well? If so I will mention in the changelog together with the drop of macOS and Xcode.

**Comment by danyf90** [comment]
@adellibovi I think it's fine, we could even add static helpers later if we think it's needed

**Pull request merged**
