### PR TITLE
Fix depfu on `website`

### LINKED ISSUE #3741: Depfu Error: Depfu is stuck and needs your help
Hello,

⚠️ **We're getting errors with "projects/website - Npm" and have given up after trying several times.**

In most cases that means something is wrong with your current Npm setup and we can't fix it automatically:

##### • Error details:
```
NPM Error: npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/gatsby-plugin-favicon/favicons-webpack-plugin@git+https:/github.com/Creatiwity/favicons-webpack-plugin.git#0872de414061baaad0a2853c77ae75bc38b8bbbf" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /app/.npm/_logs/2021-11-26T16_33_05_317Z-debug.log

```
##### • Error details:
```
NPM Error: npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/gatsby-plugin-favicon/favicons-webpack-plugin@git+https:/github.com/Creatiwity/favicons-webpack-plugin.git#0872de414061baaad0a2853c77ae75bc38b8bbbf" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /app/.npm/_logs/2021-11-26T00_48_44_508Z-debug.log

```
##### • Error details:
```
NPM Error: npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/gatsby-plugin-favicon/favicons-webpack-plugin@git+https:/github.com/Creatiwity/favicons-webpack-plugin.git#0872de414061baaad0a2853c77ae75bc38b8bbbf" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /app/.npm/_logs/2021-11-24T22_28_15_193Z-debug.log

```

After you've fixed the problem, please activate this project again in the [Depfu Dashboard](https://depfu.com/repos/github/tuist/tuist?project_id=31315).

👉 **We will not send you further PRs until this is fixed and the repo is activated again**.

If you need help or this looks like an error on our side, please [send us an email](mailto:hi@depfu.com?subject=Error+on+tuist/tuist).

### PR DESCRIPTION
**Pull request by ezraberch**
Resolves #3741

This is an attempt to get `depfu` working on the `website` project again.

I have temporarily changed depfu for `website` to point to this branch, and reenabled it.

### CODE REVIEW

**Comment by pepicrft** [comment]
Thanks a lot for tackling this one @ezraberch. It seems that CI is not happy about the removal of the dependency.

**Comment by ezraberch** [comment]
I don't think that's it. If you look at the first commit, which just removed the dependency but kept the old lockfile, that test passed.

Basically, the dependencies have gotten outdated enough that they can no longer be resolved. (And there's some stuff which really needs to be updated anyway; see the output of `npm audit`). So the next step is to try to update everything to the latest version and see what breaks.

**Comment by pepicrft** [comment]
Thanks for the clarification @ezraberch 🙏🏼. Just realized the PR is still a draft and that there's some pending work left. Let me know if you need a hand with this one.

**Comment by ezraberch** [comment]
@pepicrft Is there some reason `website` uses both `yarn` and `npm` package managers?

**Comment by pepicrft** [comment]
> @pepicrft Is there some reason website uses both yarn and npm package managers?

We used to use Yarn but eventually migrated to NPM. Any Yarn-related files are leftovers that you can get rid of.

**Comment by ezraberch** [comment]
> We used to use Yarn but eventually migrated to NPM. Any Yarn-related files are leftovers that you can get rid of.

`fourier build web` currently uses yarn. The CI resolves dependencies using `npm` then builds using `yarn` (via `fourier`).

**Comment by pepicrft** [comment]
> fourier build web currently uses yarn. The CI resolves dependencies using npm then builds using yarn (via fourier).

In that case, we need to update `fourier` to use NPM instead of Yarn.

**Review by pepicrft — APPROVED** [review]

**Comment by pepicrft** [comment]
Is there anything missing @ezraberch? Otherwise I think we can go ahead and merge.

**Comment by ezraberch** [comment]
I think it's done now. Some notes:
1. Most dependencies have been updated to the latest version.
2. Some dependencies haven't been updated to declare support for Gatsby 4, so the `--legacy-peer-deps` option is necessary for now.
3. `npm audit` still complains about some security issues in indirect dependencies. I'm unsure if this is something we should be worrying about.
4. Updating `tailwindcss` to v3 breaks formatting, so it remains at v2 for now.
5. It's probably a good idea to let `depfu` submit PRs for out-of-spec upgrades.

**Comment by pepicrft** [comment]
Thanks a lot, @ezraberch for the heads up

> Some dependencies haven't been updated to declare support for Gatsby 4, so the --legacy-peer-deps option is necessary for now.

Let's keep an eye on those and update them when they have support for Gatsby 4

> npm audit still complains about some security issues in indirect dependencies. I'm unsure if this is something we should be worrying about.

I think it's safe because those dependencies are used to statically generate sites in environments where there are no sensitive data.

> Updating tailwindcss to v3 breaks layout, so it remains at v2 for now.

Let's keep it pinned to v3. With the upcoming iteration of the website we'll move away from Tailwind so there's no need to worry about this.

> It's probably a good idea to let depfu submit PRs for out-of-spec updates.

Let me adjust this :P

**Pull request merged**
