### PR TITLE
Add Newline to End of Generated Resource Accessor Files

### PR DESCRIPTION
**Pull request by Jake-Prickett**
### Short description 📝
When running `tuist generate`, changes consistently appear in the git diff (even after staging and committing) in the Bundle extension generated by tuist not due to the post generated file not having a new line at the end. Even after staging this line, it still continuously appears. We've been puzzled by this one since our complete migration to Tuist! 🎉 

This resolves the issue for us, but if someone else has a different solution for this problem that doesn't require a code change, I can close this PR 😄 

### Checklist ✅

- [x] The code architecture and patterns are consistent with the rest of the codebase.
- [x] The changes have been tested following the [documented guidelines](https://docs.tuist.io/contributors/testing-strategy/).
- [ ] The `CHANGELOG.md` has been updated to reflect the changes. In case of a breaking change, it's been flagged as such.
- [ ] In case the PR introduces changes that affect users, the documentation has been updated.

### CODE REVIEW

**Comment by Jake-Prickett** [comment]
This morning I was able to dive a bit deeper and discovered the following... 

We leverage SwiftFormat which adds a newline at the end of a file ([linebreakAtEndOfFile](https://github.com/nicklockwood/SwiftFormat/blob/master/Rules.md#linebreakatendoffile)). Although the `Bundle+Target.swift` file has markers to enable/disable linters and formatters, SwiftFormat will still add the new line when ran due to it being applied after the `// swiftformat:enable all`.

This PR adds a newline after the `// swiftformat:enable all` marker to be consistent with other generated files and minimize the diff after a generation if you have the rule enabled for your project.

**Review by fortmarek — APPROVED** [review]
Haha, good catch @Jake-Prickett! Let's merge this once [this](https://github.com/tuist/tuist/pull/2898) PR is merged that should fix the broken lint checks on `main`. Sorry for the inconvenience about this!

**Comment by Jake-Prickett** [comment]
Thanks @fortmarek! Up to date and ready 👍

**Comment by fortmarek** [comment]
There actually seem to be some issues with formatting Swift files - could you run `./fourier format swift --fix`?

**Review by pepibumur — APPROVED** [review]

**Review by laxmorek — APPROVED** [review]

**Pull request merged**
