### PR TITLE
Support custom scheme with pre/post action

### LINKED ISSUE #195: Scheme PreAction and PostAction
**Is your feature request related to a problem? Please describe.**
In our project, we have several schemes and each scheme has different pre-action/post-action script.

**Describe the solution you'd like**
Support define actions for schemes, similar to `TargetAction`

### PR DESCRIPTION
**Pull request by dangthaison91**
This will resolve #195 and #199 

### Solution 📦
This PR allow user:
- Custom their Scheme and Tuist can generate more than 1 scheme for each target
- If there is no Scheme manifest for a target, auto-generate scheme for each target (keep current behavior)
- Add pre/post action for Build/Test/Archive Action

Usage:
``` swift
let TuistTarget = "Tuist-Demo"
let TuistTest = "Tuist-DemoTest"

let AppTarget = Target(name: TuistTarget,
                    platform: .iOS,
                    product: .app,
                    bundleId: "io.tuist.Tuist-Demo",
                    infoPlist: "Tuist-Demo/Info.plist",
                    sources: "",
                    resources: ["Tuist-Demo/**/*.{xib}", "Tuist-Demo/**/*.{xcassets}"],
                    dependencies: [])

let TestTarget = Target(name: TuistTest,
                  platform: .iOS,
                  product: .unitTests,
                  bundleId: "io.tuist.Tests",
                  infoPlist: "Tuist-DemoTests/Info.plist",
                  sources: "",
                  dependencies: [.target(name: TuistTarget)],
                  settings: Settings(base: ["TEST_HOST": "$(BUNDLE_LOADER)"]))

let DevScheme = Scheme(name: TuistTarget,
                       shared: true,
                       buildAction: BuildAction(targets: [TuistTarget, TuistTest],
                                                preActions: [SchemeAction(title: "Dev", scriptText: "$ Dev script", target: TuistTarget)]),
                       testAction: TestAction(targets: [TuistTest]),
                       runAction: RunAction(executable: TuistTarget))

let ProductionScheme = Scheme(name: TuistTarget,
                              shared: true,
                              buildAction: BuildAction(targets: [TuistTarget, TuistTest],
                                                       preActions: [SchemeAction(title: "Production", scriptText: "$ Production script", target: TuistTarget)]),
                              runAction: RunAction(executable: TuistTarget))

let project = Project(name: "Tuist-Demo",
                      up: [],
                      targets: [AppTarget, TestTarget],
                      schemes: [DevScheme, ProductionTarget])
```

### Implementation 👩‍💻👨‍💻

- [x] Update SchemeGenerator
- [ ] Update Tests
- [ ] Update Changelog

### CODE REVIEW

**Comment by pepibumur** [comment]
This PR is looking good @dangthaison91. I'd only add an extra bullet point to your list, write some documentation [on this repository](https://github.com/tuist/documentation) to explain how to define schemes and why you might need them.
Thanks for bringing up this great contribution.

**Comment by pepibumur** [comment]
By the way, I invited you as a contributor so you no longer need to work from a fork. It'll make things easier for you.

**Comment by kwridan** [comment]
Hi @dangthaison91 - I have made a few updates to master (#237) which sadly introduced some conflicts to your change. I've just pushed an update to #241 that should hopefully make resolving the conflicts a bit easier. 

On master the conversions between `ProjectDescription` (manifests) to `TuistKit` models now takes place in `GeneratorModelLoader`. This decoupling will allow us to move generator related code to the generator library (#205).

Let me know if you need help resolving those conflicts.

**Comment by dangthaison91** [comment]
Thanks @kwridan , very busy with company project right now, I will spend time to rebase it later and ask you if I need help.

**Pull request closed without merging**
