### PR TITLE
Add support for watchOS extension to have WidgetKit extension dependencies

### PR DESCRIPTION
**Pull request by griches**
### Short description 📝

- WatchOS extension targets can now include WidgetKit extension targets (as of Xcode 14)
- WidgetKit extension targets are regular app extension targets
- Tuist already supports embedding app extensions, the only change needed to support it for watchOS extension was to update the linter logic to allow this dependency combination
- The fixture was extended to demo a watchOS WidgetKit extension

Notes:

- WidgetKit extension targets require the following info plist keys
```
<dict>
	<key>NSExtension</key>
	<dict>
		<key>NSExtensionPointIdentifier</key>
		<string>com.apple.widgetkit-extension</string>
	</dict>
</dict>
```

### How to test the changes locally 🧐

- Generate the watch application fixture

```
swift build
swift run tuist generate --path projects/tuist/fixtures/ios_app_with_watchapp2
```

- Verify the project generates successfully without any lint errors
- Inspect the generated project and verify the WidgetKit extension for the watch extension is created correctly

### Contributor checklist ✅

- [x] The code has been linted using `run ./fourier lint tuist --fix`
- [x] The change is tested via unit testing or acceptance testing, or both
- [x] The title of the PR is formulated in a way that is usable as a changelog entry
- [x] In case the PR introduces changes that affect users, the documentation has been updated

### Reviewer checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase
- [ ] Reviewer has checked that, if needed, the PR includes the label `changelog:added`, `changelog:fixed`, or `changelog:changed`, and the title is usable as a changelog entry

### CODE REVIEW

**Review by danyf90 — APPROVED** [review]

**Review by kwridan — APPROVED** [review]
Thanks for adding this and updating the fixtures @griches 👍 

I didn't realise this combination was possible, thought it was only the newer Xcode 14 watch app style targets.

**Comment by kwridan** [comment]
```
 /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20230418-2681-ochm8b/App.xcodeproj: error: WidgetKit is not  available when building for watchOS Simulator. (in target 'WatchAppWidgetExtension' from project 'App')
```

Ouch, I forgot we are still running Xcode 13 on CI 🤐 - ref: #5029  

Suggestion is perhaps to include another Application target that has the watchExtension2 > widgetKit dependency, that would allow us to manually verify it but won't be CI'd

**Comment by griches** [comment]
> manually

So I can remove this fixture update, and include a project that you will verify manually in Xcode 14? Where in the file structure should this project live?

**Comment by danyf90** [comment]
@allcontributors add @griches for code

**Pull request merged**
