### PR TITLE
Package and upload Tuist on every commit build

### PR DESCRIPTION
**Pull request by pepibumur**
### Short description 📝
The goal of this PR is to make it easier to try the Tuist version associated with a branch, PR, or commit. We achieve that by storing a compiled release build for each commit of the project.

### Solution 📦
This PR adds a new Rake task, `package_commit` that builds Tuist for release, zips it and uploads it to Google Cloud Storage.

In a follow-up PR, I'll modify the `tuist local` command to pull the packaged build from GCS, instead of compiling it locally.

### CODE REVIEW

**Comment by ollieatkinson** [comment]
Does that mean we wouldn't use GitHub releases for anything? At the moment it's nice that I'm able to point to forks of tuist and test them out - if they are all on gcloud would we would loose that?

**Comment by pepibumur** [comment]
> Does that mean we wouldn't use GitHub releases for anything? 

We'll continue to use GitHub releases for tagged commits. 

> At the moment it's nice that I'm able to point to forks of tuist and test them out - if they are all on gcloud would we would loose that?

No, what this allows is doing `tuist local my-branch`  without having to compile the source code. The command will get the latest commit using the GitHub's AP,I and pull the compiled artifacts from gcloud.

**Comment by ollieatkinson** [comment]
Awesome! Looks good @pepibumur

**Comment by ollieatkinson** [comment]
CI is failing:

> Caused by:
Google::Apis::ClientError: invalid: Disallowed unicode characters present in object name ''tuist-3fec0773a55869949ad73b73f0f13c500656beb6

**Comment by pepibumur** [comment]
Yes, I think the way we are obtaining the commit sha introduces non-supported characters.

**Pull request merged**
