### PR TITLE
Disable project scheme explicitly

### PR DESCRIPTION
**Pull request by olejnjak**
Request for comments document (if applies): #3394 

### Short description 📝

I think it is shame not to generate project scheme when user defines own schemes (thus wants to use `disableAutogeneratedSchemes` in `Config`) as that scheme can be pretty useful. This PR makes this explicit by introducing new generation option `disableProjectScheme`. I was also thinking about adding associated value to `disableAutogeneratedSchemes` but I think that used approach helps to keep things simple although it is a change to current behavior.

### Checklist ✅

- [x] The code architecture and patterns are consistent with the rest of the codebase.
- [x] The changes have been tested following the [documented guidelines](https://docs.tuist.io/contributors/testing-strategy/).
- [x] The `CHANGELOG.md` has been updated to reflect the changes. In case of a breaking change, it's been flagged as such.
- [x] In case the PR introduces changes that affect users, the documentation has been updated.

### CODE REVIEW

**Comment by adellibovi** [comment]
I am not sure about the naming,
I would expect the `disableAutogeneratedSchemes` to still not generate ANY schemes.
Maybe we could deprecate this option and go for a: `generateSchemes(.all)`/`generateSchemes(.onlyWorkspace)` (or similar).
Can you describe when you would find this useful? It would help figuring out the best API 😄

**Comment by olejnjak** [comment]
If you define custom schemes it is still quite useful to have the option to run all workspace tests even from Xcode.

**Comment by adellibovi** [comment]
Thanks @olejnjak! ☺️ What do you think about the suggestion then? We could also deprecate and suggest renaming to the new case.
cc: @pepibumur it would be good to have your view as well.

**Comment by olejnjak** [comment]
I am not sure, I think that the `generateSchemes(...)`  option would be quite tricky as the default (with no `Config` or `GenerationOptions`) is all so maybe adding associated value to `disableAutogeneratedSchemes` might have more sense.

**Comment by fortmarek** [comment]
I think we can take this opportunity to make this disable option more flexible by moving it to `Project.generationOptions`. You could then disable autogeneration of schemes on a project-by-project basis. 

I understand the need for `disableAutogeneratedSchemes` but maybe we can just keep the generation of the project scheme on by default? Do we know of any teams that have a need to disable this one? If this turned out to be an issue, we could add disabling of a project scheme to `Config.swift` (as that one takes into account the whole workspace, I think `Project.generationOptions` might not be the appropriate location).

If we wanted to do this, though, it'd be nice to include this in the upcoming 2.0 release.

What do you think?

**Comment by olejnjak** [comment]
Well generating project scheme regardless of `Config` might make sense as it would feel consistent with what `tuist test` does 🤔

**Comment by pepibumur** [comment]
Hey @olejnjak.
Since this is an important decision for the project, would you mind following the RFC process and creating a discussion in the forum using [this template](https://github.com/tuist/tuist/discussions/2189). Make sure you capture the motivation, include several options for tackling this problem (with the tradeoffs), and your decision. As the project mature, having an initial discussion helps ensure that the proposal aligns with the direction of the tool and its principle.

Until that discussion takes place, let's keep this PR open.

**Comment by danyf90** [comment]
Converting to draft as under discussion here: https://github.com/tuist/tuist/discussions/3394

**Pull request closed without merging**
