### PR TITLE
Fix DumpServiceTests

### PR DESCRIPTION
**Pull request by pepicrft**
### Short description 📝
A test in that file is causing the test suite to fail. This is my attempt to debug it through CI (because I can't reproduce it locally) and fix it.

### CODE REVIEW

**Review by danyf90 — APPROVED** [review]

**Comment by pepicrft** [comment]
ny luck @fortmarek ?

**Comment by fortmarek** [comment]
Not really, I was not able to reproduce locally, so I tried some shots in the dark but unsuccessfully so far 😞 I have no idea why it could fail on remote and not locally.

**Comment by fortmarek** [comment]
I don't expect my current changes to really fix this but I have moved the current `DumpServiceTests` to `DumpServiceIntegrationTests` since that's what they were (we are testing the full integration with the `ManifestLoader`)

**Comment by fortmarek** [comment]
This has weirdly passed. Let's monitor this and see if it's because the test is flaky or if it's actually solved.

**Pull request merged**
