### PR TITLE
[2.0] Remove up

### PR DESCRIPTION
**Pull request by pepibumur**
### Short description 📝
I'm removing the `Setup.swift` manifest and the `tuist up` command *(breaking change)* as part of the 2.0 version effort. Here are the reasons:

- It doesn’t leverage the graph in any way and that makes it feel outside of Tuist’s domain.
- It’s something teams can implement easily with scripting (bash, Ruby…) by simply having an `up.rb` or `up.sh` script at the root of the repository that developers can call.
- Issues coming from the underlying commands make people think they are Tuist bugs when they are not. Therefore we end up with GitHub issues it’s not our responsibility to fix.

### Checklist ✅

- [x] The code architecture and patterns are consistent with the rest of the codebase.
- [x] The changes have been tested following the [documented guidelines](https://docs.tuist.io/contributors/testing-strategy/).
- [x] The `CHANGELOG.md` has been updated to reflect the changes. In case of a breaking change, it's been flagged as such.
- [x] In case the PR introduces changes that affect users, the documentation has been updated.

### CODE REVIEW

**Review by fortmarek — COMMENTED** [review]
I'm +1 on this decision overall but I am wondering if we maybe want to do a migration guide detailing how to get around things we have deleted/changed?

I also think that maybe we should strive for plugins 2.0 to be a part of tuist 2.0. We have already deleted a couple of commands before and I feel like this would be a great opportunity to migrate folks to start using our tuist tasks instead of delegating the functionality to bash scripts.

**Comment by pepibumur** [comment]
I agree with providing a migration guideline. I plan to do that as part of this PR before merging.

I also agree with this being a shareable task in the future. However, I don't think rushing the evolution of plugins for 2.0 is a good idea. That idea requires a lot of thinking and iterations until we feel confortable with the APIs and the user experience. 

I think we should cut in features to gain focus and reduce maintenance. Of course, providing migration paths. Release 2.0, and plan an iteration of plugins for 3.0.

**Review by laxmorek — COMMENTED** [review]
`Tuist / up acceptance tests with Xcode 12.5.1 (pull_request)` can be removed.

Im for this removal. My only concern here is that according to our [stats](https://stats.tuist.io) the `tuist up` command is highly used.

**Comment by pepibumur** [comment]
Yeah, those need to be removed. Regarding the usage, users built workflows upon it, which means is something useful, but being useful doesn't mean it should be part of Tuist. I'll provide users with an alternative that they can adopt instead, and once we iterate the plugins system to use a process-based approach, we'll encourage users to follow that instead.

**Pull request merged**
