### PR TITLE
feat: skipTargets for cache

### PR DESCRIPTION
**Pull request by apps4everyone**
### Short description 📝

feat: skipTargets for cache

### Checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase.
- [ ] The changes have been tested following the [documented guidelines](https://docs.tuist.io/contributors/testing-strategy/).
- [ ] The `CHANGELOG.md` has been updated to reflect the changes. In case of a breaking change, it's been flagged as such.
- [ ] In case the PR introduces changes that affect users, the documentation has been updated.

### CODE REVIEW

**Comment by apps4everyone** [comment]
@fortmarek maybe you can help me with the failing test, thx

**Comment by fortmarek** [comment]
> maybe you can help me with the failing test, thx 

Could you describe a little bit further what is failing and what the current output is?

**Comment by apps4everyone** [comment]
> > maybe you can help me with the failing test, thx
> 
> Could you describe a little bit further what is failing and what the current output is?

the result printed in the test is not as expected:
https://github.com/tuist/tuist/pull/3053/files#diff-3465ad110afa1b5ed514bb5b40ada1c076dc80652327b3f9aac8cb947f4b6e76R260-R272

**Comment by fortmarek** [comment]
> the result printed in the test is not as expected

and what's the current output?

**Comment by apps4everyone** [comment]
> > the result printed in the test is not as expected
> 
> and what's the current output?

XCTAssertTrue failed - The output:
===========
Hashing cacheable targets
Building cacheable targets
Building cacheable targets: baz, 1 out of 1
All cacheable targets have been cached successfully as xcframeworks
Checking if /Users/stefanfessler/.tuist exists... true
Checking if /Users/stefanfessler/.tuist/Versions exists... true
Creating folder at path /var/folders/nm/bvjzvxf93wnc_k5m7cjpblkm0000gn/T/TemporaryDirectory.CPFDH1/bar.framework
Creating folder at path /var/folders/nm/bvjzvxf93wnc_k5m7cjpblkm0000gn/T/TemporaryDirectory.CPFDH1/foo.framework
Creating folder at path /var/folders/nm/bvjzvxf93wnc_k5m7cjpblkm0000gn/T/TemporaryDirectory.CPFDH1/baz.framework
Deleting item at path /var/folders/nm/bvjzvxf93wnc_k5m7cjpblkm0000gn/T/TemporaryDirectory.BSEc5J
Checking if /var/folders/nm/bvjzvxf93wnc_k5m7cjpblkm0000gn/T/TemporaryDirectory.BSEc5J exists... true

Doesn't contain the expected:
===========
Hashing cacheable targets
Building cacheable targets
Building cacheable targets: bar, 1 out of 1
All cacheable targets have been cached successfully as xcframeworks


XCTAssertEqual failed: ("Target(name: "baz", platform: TuistGraph.Platform.iOS, product: application, bundleId: "io.tuist.baz", productName: "baz", deploymentTarget: Optional(TuistGraph.DeploymentTarget.iOS("13.1", TuistGraph.DeploymentDevice(rawValue: 3))), infoPlist: nil, entitlements: nil, settings: Optional(TuistGraph.Settings(base: [:], configurations: [:], defaultSettings: TuistGraph.DefaultSettings.recommended(excluding: Set([])))), dependencies: [], sources: [], resources: [], copyFiles: [], headers: nil, coreDataModels: [], actions: [], environment: [:], launchArguments: [], filesGroup: TuistGraph.ProjectGroup.group(name: "Project"), scripts: [], playgrounds: [], prune: false)") is not equal to ("Target(name: "bar", platform: TuistGraph.Platform.iOS, product: application, bundleId: "io.tuist.bar", productName: "bar", deploymentTarget: Optional(TuistGraph.DeploymentTarget.iOS("13.1", TuistGraph.DeploymentDevice(rawValue: 3))), infoPlist: nil, entitlements: nil, settings: Optional(TuistGraph.Settings(base: [:], configurations: [:], defaultSettings: TuistGraph.DefaultSettings.recommended(excluding: Set([])))), dependencies: [], sources: [], resources: [], copyFiles: [], headers: nil, coreDataModels: [], actions: [], environment: [:], launchArguments: [], filesGroup: TuistGraph.ProjectGroup.group(name: "Project"), scripts: [], playgrounds: [], prune: false)")

**Comment by apps4everyone** [comment]
> > > the result printed in the test is not as expected
> > 
> > 
> > and what's the current output?
> 
> # XCTAssertTrue failed - The output:
> Hashing cacheable targets
> Building cacheable targets
> Building cacheable targets: baz, 1 out of 1
> All cacheable targets have been cached successfully as xcframeworks
> Checking if /Users/stefanfessler/.tuist exists... true
> Checking if /Users/stefanfessler/.tuist/Versions exists... true
> Creating folder at path /var/folders/nm/bvjzvxf93wnc_k5m7cjpblkm0000gn/T/TemporaryDirectory.CPFDH1/bar.framework
> Creating folder at path /var/folders/nm/bvjzvxf93wnc_k5m7cjpblkm0000gn/T/TemporaryDirectory.CPFDH1/foo.framework
> Creating folder at path /var/folders/nm/bvjzvxf93wnc_k5m7cjpblkm0000gn/T/TemporaryDirectory.CPFDH1/baz.framework
> Deleting item at path /var/folders/nm/bvjzvxf93wnc_k5m7cjpblkm0000gn/T/TemporaryDirectory.BSEc5J
> Checking if /var/folders/nm/bvjzvxf93wnc_k5m7cjpblkm0000gn/T/TemporaryDirectory.BSEc5J exists... true
> 
> # Doesn't contain the expected:
> Hashing cacheable targets
> Building cacheable targets
> Building cacheable targets: bar, 1 out of 1
> All cacheable targets have been cached successfully as xcframeworks
> 
> XCTAssertEqual failed: ("Target(name: "baz", platform: TuistGraph.Platform.iOS, product: application, bundleId: "io.tuist.baz", productName: "baz", deploymentTarget: Optional(TuistGraph.DeploymentTarget.iOS("13.1", TuistGraph.DeploymentDevice(rawValue: 3))), infoPlist: nil, entitlements: nil, settings: Optional(TuistGraph.Settings(base: [:], configurations: [:], defaultSettings: TuistGraph.DefaultSettings.recommended(excluding: Set([])))), dependencies: [], sources: [], resources: [], copyFiles: [], headers: nil, coreDataModels: [], actions: [], environment: [:], launchArguments: [], filesGroup: TuistGraph.ProjectGroup.group(name: "Project"), scripts: [], playgrounds: [], prune: false)") is not equal to ("Target(name: "bar", platform: TuistGraph.Platform.iOS, product: application, bundleId: "io.tuist.bar", productName: "bar", deploymentTarget: Optional(TuistGraph.DeploymentTarget.iOS("13.1", TuistGraph.DeploymentDevice(rawValue: 3))), infoPlist: nil, entitlements: nil, settings: Optional(TuistGraph.Settings(base: [:], configurations: [:], defaultSettings: TuistGraph.DefaultSettings.recommended(excluding: Set([])))), dependencies: [], sources: [], resources: [], copyFiles: [], headers: nil, coreDataModels: [], actions: [], environment: [:], launchArguments: [], filesGroup: TuistGraph.ProjectGroup.group(name: "Project"), scripts: [], playgrounds: [], prune: false)")

@fortmarek any ideas here? thx

**Pull request closed without merging**
