### PR TITLE
Fix code coverage not gathered for project with enabled code coverage when running `tuist test`

### LINKED ISSUE #2182: No test coverage whit option enableCodeCoverage and running tuist test
**Describe the bug**
Lack of coverage when using the **option** **.enableCodeCoverage** on the test targets

**To Reproduce**

1. Create a directory **example** and go to this path
2. Init a new Tuist project` tuist init --platform ios`
3. `tuist edit` and enable `.enableCodeCoverage` on the project options
4. Run `tuist test`
5. Review the test coverage reports, there is no coverage info

**Expected behavior**
**xcresult** should have coverage report

**Screenshots**
image

**Desktop (please complete the following information):**

- OS: macOS
- Version 11.1 

**Additional context**
I think the issue is that when the `.enableCodeCoverage` option is enable, it sets the autogenerate schemes with coverage enable for the target itself. If you run the test on a specific non test scheme, example **ExampleUI** or **ExampleKit** then the coverage is collected.

**tuist test** run the test targets, which they have enable codeCoverage but has set the target to collect to it self

image

I think (I could be wrong, I've many time without making iOS development) that the target define on **Targets** should be **ExampleUI** instead of **ExampleUITests**

### LINKED ISSUE #2186: Choose a path for the test xcresult when running tuist test
## Need/problem

Some code analysis tools, for example SonarQube/Sonarcloud ask you to convert the files xcresult to their format before send them to the server for analysis.

## Motivation

xcresult files and stored under xcode DerivedData which on a CI server this directory changes all the time. If we could set a path where to export the results, could be easer for the developer to them extract them and do whatever we need with them, like when the command `xcodebuild` is run, we can setup an argument  **derivedDataPath**

We could probably do something with the  **find** command on the CI, but I think it's not ideal

## Detailed design

When running `tuist test` we should have an argument that accepts a path for the logs, I'm not sure if it could be worth for any other tuist command

# Drawbacks

Why should we *not* do this? Please consider:

Non comes to my head

## Alternatives

We could probably do something with the  **find** command on the CI, but I think it's not ideal

# Adoption strategy

If we implement this proposal, how will existing Tuist developers adopt it? Is
this a breaking change?

Is not a breaking change, they will just need to update how they collect logs/coverage data

# How we teach this

Docs should be updated to reflect the new argument

# Unresolved questions

None

### PR DESCRIPTION
**Pull request by adellibovi**
Resolves #2182
Request for comments document (if applies):

### Short description 📝

Hi, as mentioned in #2182, currently running `tuist test` when having code coverage enabled for the project do not correctly gather code coverage.
To try it out:
* Enable code coverage to fixture: ios_workspace_with_microfeature_architecture
* `tuist generate`
* `tuist test`
* Open xcresult in DerivedData\ProjectHash\Logs\Test

### Checklist ✅

- [x] The code architecture and patterns are consistent with the rest of the codebase.
- [x] The changes have been tested following the [documented guidelines](https://tuist.io/docs/contribution/testing-strategy/).
- [x] The `CHANGELOG.md` has been updated to reflect the changes. In case of a breaking change, it's been flagged as such.
- [x] In case the PR introduces changes that affect users, the documentation has been updated.

### CODE REVIEW

**Comment by fortmarek** [comment]
Hi @adellibovi!

could you specify what `tuist` version you are using?

For the current release `tuist test` does not actually work at all 😞 - the fixes are [here](https://github.com/tuist/tuist/pull/2422).

Under the hood, `tuist test` now runs `Project` scheme - for which the code coverage you have actually [fixed](https://github.com/tuist/tuist/pull/2493) already (thanks!)

So, from what I understand this change is not necessary.

You have also stated that this PR will fix [#2186](https://github.com/tuist/tuist/issues/2186) - is that the case, though? This does not solve the fact that the test results are saved into a derived data path. We should indeed provide a way to specify where the results will be saved which is related to [this](https://github.com/tuist/tuist/issues/2392).

**Comment by adellibovi** [comment]
@fortmarek oops, wrong mention of issue, I meant #2182, updated in the description too 😄 

Regarding the version, I believe I tried with a branch up-to-date from main, and was still getting the tests run targets one by one 🤔
Will try again just to be sure. About the change it may still make sense for users who run wants to run `tuist test FrameworkTests` or in general for other targets which now limits the code coverage to just their target and not the affected ones (the description of the issue would need to be changed though).

**Comment by fortmarek** [comment]
ah, ok, I see

Following up on the discussion from the issue:

> Shouldn't the default behaviour be that if we enable code coverage we gather coverage for all targets?

I don't have a strong opinion on this but if I run `XXXTests`, I'd expect to get coverage only for `XXX` - as the situation currently is.

A more delicate fix of the original issue would be something like this:

`let codeCoverageTargets = codeCoverage ? testableTargets + [targetReference] : []`

Because the issue is that we add code coverage only for the target itself but we should actually collect code coverage for the targets we want to test.

**Comment by adellibovi** [comment]
Adding a comment for other reviewers, while having a chat offline with @fortmarek we also noticed that is worth mentioning that the default behavior of Xcode when enabling Code Coverage is to enable for all targets (as this PR)

**Comment by fortmarek** [comment]
@kwridan do you have any thoughts on this? I think we can follow the Xcode's behavior and keep the PR as-is but it would be great to get the third opinion in here

**Comment by kwridan** [comment]
Both approaches have merit. Perhaps keeping the Xcode behaviour makes sense. 

I can imagine when running UI tests or integration tests you may want to see the coverage for all the dependent modules too. 

I guess if that isn't desired running the tests on the individual modules to see their coverage is still available. 

For example running AppUITests vs NetworkingTests

AppUITests may include coverage or App, Networking, ...

Vs NetworkingTests will include coverage of Networking (and its dependencies if has any)

As a final measure, worth remembering users can create custom schemes and tailor it to their specific needs, so here it's a matter of picking a default behaviour we think applies best to most cases. 

Hope this helps 🙂

**Comment by adellibovi** [comment]
@kwridan and @fortmarek not sure what we decided 😆
I understood we are more towards going with Xcode approach and therefor keeping the PR as is?

In any case, I rebased this PR and changed the changelog, as the fix for `tuist test` is already fixed, this PR now mention that, when code coverage is enabled, targets such as `TestMyFramework` gather coverage for all affected targets instead of `TestMyFramework` only.

If I misunderstood, please clarify it for me so I can make the appropriate changes 😃 🙏

**Review by fortmarek — APPROVED** [review]
I'm ok with keeping Xcode default behavior, approved ✅

**Review by kwridan — APPROVED** [review]

**Pull request merged**
