### PR TITLE
Add ability to pass specified environment keys when calling Tuist.graph(at:)

### PR DESCRIPTION
**Pull request by batuhansk**
Resolves https://github.com/tuist/tuist/issues/5125

### Short description 📝

This PR adds ability to pass environment keys when we call `Tuist.graph(at:)` method.

### How to test the changes locally 🧐

Create a `Tuist` plugin that uses `Tuist.graph(at:)` internally, and call this plugin through the `tuist` scheme and pass some environment variables, then print out the `ProcessInfo.processInfo.environment` to see whether these environment keys passed to the relevant process.

### Contributor checklist ✅

- [x] The code has been linted using run `./fourier lint tuist --fix`
- [x] The change is tested via unit testing or acceptance testing, or both
- [x] The title of the PR is formulated in a way that is usable as a changelog entry
- [x] In case the PR introduces changes that affect users, the documentation has been updated

### Reviewer checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase
- [ ] Reviewer has checked that, if needed, the PR includes the label `changelog:added`, `changelog:fixed`, or `changelog:changed`, and the title is usable as a changelog entry

### CODE REVIEW

**Comment by danyf90** [comment]
@batuhansk Could you please fix linting? 🙏

**Comment by batuhansk** [comment]
> @batuhansk Could you please fix linting? 🙏

Done 🤙🏼

**Review by danyf90 — APPROVED** [review]

**Comment by batuhansk** [comment]
Hey @fortmarek  👋🏼 
If everything seems fine with you, can we publish this development?

**Comment by batuhansk** [comment]
@danyf90 @fortmarek I've investigated the failing tests, but figured out that tests are also failing in `main` branch too. Is this expected behavior?

**Review by fortmarek — APPROVED** [review]
What tests are failing? At least now, `main` seems to be green 🤔

**Comment by batuhansk** [comment]
> What tests are failing? At least now, `main` seems to be green 🤔 


It seems green now, seems fixed. It was about last week

**Comment by batuhansk** [comment]
> What tests are failing? At least now, `main` seems to be green 🤔

Seems fixed. Ready to merge 🚀

**Comment by batuhansk** [comment]
@danyf90 If everything seems OK, can we merge into the `main`?

**Comment by danyf90** [comment]
@allcontributos add @batuhansk for code

**Comment by danyf90** [comment]
@allcontributors add @batuhansk for code

**Comment by batuhansk** [comment]
Hey @danyf90 👋🏼 Can we also update the [ProjectAutomation](https://github.com/tuist/ProjectAutomation) mirror?

**Pull request merged**
