### PR TITLE
Add support for `real`  value in InfoPlist

### LINKED ISSUE #3355: Plist values dosen't have support for floating value.
There is Plist value called `Number`, which looks like this `<real>0.8</real>`. It supports even floating number, showing in the example. this is missing in Tuist, you can only use `.integer()` which is only Int.

Here is an example.

```swift
<dict>
	<key>UNNotificationExtensionCategory</key>
	<array>
		<string>product</string>
	</array>
	<key>UNNotificationExtensionDefaultContentHidden</key>
	<true/>
	<key>UNNotificationExtensionInitialContentSizeRatio</key>
	<real>0.8</real>
</dict>
```

Screen Shot 2021-08-26 at 12 58 43

### PR DESCRIPTION
**Pull request by MarvinNazari**
Resolves #3355

### Short description 📝

This PR adds support for having `real` in InfoPlist which is a floating number.

### Checklist ✅

- [x] The code architecture and patterns are consistent with the rest of the codebase.
- [x] The changes have been tested following the [documented guidelines](https://docs.tuist.io/contributors/testing-strategy/).
- [x] The `CHANGELOG.md` has been updated to reflect the changes. In case of a breaking change, it's been flagged as such.
- [x] In case the PR introduces changes that affect users, the documentation has been updated.

### CODE REVIEW

**Review by danyf90 — APPROVED** [review]
@fortmarek @pepibumur 

This is technically breaking. For example it would break in case a Project or a Plugin are switching on the Value enum.
Should we ship it in 2.0?

**Comment by pepibumur** [comment]
> This is technically breaking. For example it would break in case a Project or a Plugin are switching on the Value enum.
Should we ship it in 2.0?

Why is it breaking?

**Comment by fortmarek** [comment]
> Why is it breaking?

If you have a switch on `InfoPlist.Value` and you don't use `default` case, it will error since the switch would not be exhaustive. However, I am not sure how many people do that. I think we can maybe keep the branch as-is?

**Review by fortmarek — COMMENTED** [review]
Hey @MarvinNazari!

I think this is mostly good to go.
I'd just add a documentation of this [here](https://github.com/tuist/tuist/blob/main/projects/docs/docs/manifests/project.md#infoplistvalue) and add a changelog.

Thanks a lot for the contribution!

**Comment by danyf90** [comment]
Hey @MarvinNazari 👋 
It would be great to be able to merge it. Do you need any help with the missing part mentioned by Marek? 🙏

**Comment by MarvinNazari** [comment]
@fortmarek & @danyf90,
Changelog and documentation is updated now.

**Review by fortmarek — APPROVED** [review]

**Comment by fortmarek** [comment]
@all-contributors add @MarvinNazari for code

**Review by danyf90 — APPROVED** [review]

**Comment by danyf90** [comment]
Hey @MarvinNazari  could you please align to main to fix the CI problem? 🙏

**Pull request merged**
