### PR TITLE
Automatically generate target dependencies

### PR DESCRIPTION
**Pull request by ezraberch**
### Short description 📝

This PR adds a new `TargetDependency`, `.auto`. If this is present, during generation dependencies will be added to the target based on `import` statements in the source files. For now, only `.target` dependencies are added.

This is a work-in-progress. At this point, I'm especially looking for feedback into how the user will enable this option. I'm leaning towards changing this from a `TargetDependency` to a generation option. Ideally, it will be possible to specify this on both a per-project and per-target basis.

### How to test the changes locally 🧐

`Project.swift` has been changed to use this option, so existing tests should verify that things haven't broken. Additionally, I have modified the `ios_app_with_tests` fixture to use it.

### Checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase.
- [ ] The changes have been tested following the [documented guidelines](https://docs.tuist.io/contributors/testing-strategy/).
- [ ] The `CHANGELOG.md` has been updated to reflect the changes. In case of a breaking change, it's been flagged as such.
- [ ] In case the PR introduces changes that affect users, the documentation has been updated.
- [ ] In case the PR introduces changes that affect how the cache artifact is generated starting from the `TuistGraph.Target`, the `Constants.cacheVersion` has been updated.

### CODE REVIEW

**Comment by danyf90** [comment]
The first problem I see with this, is that you can't cache the `Project.swift` anymore, because its "content" basically depends on all the source files, which would greatly impact generation time.

Apart from that, as a personal preference, I find clearer to have my dependencies specified in the Project.swift, rather than importing wrong dependencies by mistake, because one of the source files added an import

**Comment by ezraberch** [comment]
> The first problem I see with this, is that you can't cache the `Project.swift` anymore, because its "content" basically depends on all the source files, which would greatly impact generation time.

That's definitely a concern, but is there a good way to measure how big the impact on generation times is?

> Apart from that, as a personal preference, I find clearer to have my dependencies specified in the Project.swift, rather than importing wrong dependencies by mistake, because one of the source files added an import

That's fine; you can still specify dependencies the old way.

Two advantages of doing things the new way:

1. Much smaller Project.swift files. They'll be even more compact with a project-wide option.
2. It follows the SSOT (Single Source of Truth) design principle. Target dependencies are now defined just by source files (wherever possible), rather than having them needing to be synchronized between source files and Project.swift.

As an example of the benefit of the latter, in the current Project.swift, `TuistCache` has 4 dependencies (Core, Graph, Support, and Cloud). With autogeneration, the Cloud dependency is missing, yet nothing breaks. This suggests that the Cloud dependency is unnecessary.

**Review by kwridan — COMMENTED** [review]
Thanks for proposing this @ezraberch 

I see the appeal of this one for the added convenience, though I do agree with @danyf90 on this one. There are a few other features that may not be compatible with this approach

- Tuist Lint
- Tuist Graph
- Tuist Dump
- _... anything that leverages the Tuist Graph without generation 😞_

We do have better patterns to model this feature (e.g. via mappers), though perhaps it is better suited to be an external stand-alone tool _(possibly using Plugins?)_ that can advise you on missing dependencies. 

At work we've prototyped a similar feature that does the inverse, warns us in case we detect an import to a dependency that isn't declared in our manifest. It's important for us to have a good record of the explicit dependencies to ensure there aren't any unwanted ones _(e.g. cycle dependencies, duplicate static dependencies, or more subjective ones like two independent features depending on each other rather than their public interfaces, etc...)_

> That's definitely a concern, but is there a good way to measure how big the impact on generation times is?

We have a few tools to help out with this
https://docs.tuist.io/contributors/performance-testing

**Comment by luispadron** [comment]
I think this is super neat, but tend to agree that it would be better as a check / lint. We could add it to the lint rules for `tuist lint`.

By doing this as a warning/error we don't lose the caching support

**Comment by danyf90** [comment]
@ezraberch I think the best way to proceed with this is to close this PR and open a discussion to decide what a solution could be, before diving into implementation.
What do you think?

**Comment by ezraberch** [comment]
Sounds good. Continue the discussion at #4041.

**Pull request closed without merging**
