### PR TITLE
Fix code signing issues in test targets

### LINKED ISSUE #3920: `tuist test` fails due to codesigning xcargs
I've been having issues running some specific unit tests in my project that require a test host app. After some investigation, I think I've nailed down what the issue is.

The tests run fine when I run them through Xcode, and when I run them manually using `xcodebuild` in the terminal, but when I use `tuist test` to run the tests, the test host app crashes, and the unit tests fail. `tuist test` is just running an `xcodebuild` command itself in order to run the tests, so I was able to compare the command I was using to the one Tuist generates, and figure out what's causing the issue.

This is the command run by `tuist test`:

```shell
/usr/bin/xcrun \
	xcodebuild \
	test \
	-scheme GSPAuthTests \
	-workspace /Users/Z006TJ7/.tuist/Cache/Projects/32900f8a55d0a971b07cdaad75565aa4/Tuist_Flagship.xcworkspace \
	-sdk iphonesimulator \
	-destination id=0D4CFB5D-84F5-4ED4-8FF2-421590279D6A \
	CODE_SIGN_IDENTITY= \
	CODE_SIGNING_REQUIRED=NO \
	CODE_SIGN_ENTITLEMENTS= \
	CODE_SIGNING_ALLOWED=NO
```

Those last four `CODE_SIGN*` arguments are the ones causing the tests to fail. When I omit those arguments, the test run without issue.

In [`TestService.swift`](https://github.com/tuist/tuist/blob/754bdf0a672a0080cb20071b4a332fa2dd5884ca/Sources/TuistKit/Services/TestService.swift#L225), Tuist is explicitly saying to skip codesigning, which is what causes those arguments to be added to the command.

```swift
_ = try xcodebuildController.test(
    .workspace(graphTraverser.workspace.xcWorkspacePath),
    scheme: scheme.name,
    clean: clean,
    destination: destination,
    derivedDataPath: nil,
    resultBundlePath: resultBundlePath,
    arguments: buildGraphInspector.buildArguments(
        project: buildableTarget.project,
        target: buildableTarget.target,
        configuration: configuration,
        skipSigning: true <---------------------------------
    )
)
```

If I switch that argument to `false`, the generated `xcodebuild` command omits the `CODE_SIGN*` arguments, and the tests run without issue.

I'm not familiar enough to know _why_ this would cause a failure, or why this is hardcoded to skip signing. Is there some way to determine when signing will be required? Is there something in my test target I can change that would address this?

## Steps To Reproduce

I don't really know the specific reasons why this test host app fails due to the signing issues, so I don't have specific steps to reproduce right now. If necessary, I can try to work up an example project.

## Expected Behavior

Tests run successfully.

## Environment

- macOS: 12.1
- Tuist: 2.5.0

## Additional Context

These specific unit tests require a test host, because they are testing Keychain functionality. I'm not sure if that is related to whether or not codesigning is required, but thought it would be worth mentioning.

### PR DESCRIPTION
**Pull request by hisaac**
Resolves #3920

### Short description 📝

When using the `tuist test` command, we are explicitly disabling code signing by passing some extra arguments to the `xcodebuild` command.

One of the arguments passed is `CODE_SIGNING_ALLOWED=NO`. This is fine for most things, but if a test target has a test host that _does_ require code signing, passing this setting crashes the test host when it is run in the simulator.

You can see a more detailed explanation in #3920.

### How to test the changes locally 🧐

Here is a simple example project to test with: [CodeSignExample.zip](https://github.com/tuist/tuist/files/7790579/CodeSignExample.zip)

This project has some tests that require access to a device's Keychain, and as such, require a test host app to be running.

To test this, from the root of the project, run the following shell command:

```shell
xcodebuild \
      test \
      -project CodeSignExample.xcodeproj \
      -scheme CodeSignExample \
      -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.2' \
      CODE_SIGN_IDENTITY= \
      CODE_SIGNING_REQUIRED=NO \
      CODE_SIGN_ENTITLEMENTS=
```

Note that the app is launched in the simulator, and the tests pass.

Next, run the same command, but add the `CODE_SIGNING_ALLOWED=NO` flag:

```shell
xcodebuild \
      test \
      -project CodeSignExample.xcodeproj \
      -scheme CodeSignExample \
      -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.2' \
      CODE_SIGN_IDENTITY= \
      CODE_SIGNING_REQUIRED=NO \
      CODE_SIGN_ENTITLEMENTS= \
      CODE_SIGNING_ALLOWED=NO
```

Note that the app launches, but then crashes, and the tests fail.

I'm still not sure _exactly_ what's going on, but my hunch is like I said above: explicitly disallowing codesigning from the command line passes the behavior to the test host as well, thereby breaking any tests that have a test host that requires codesigning to function.

### Checklist ✅

- [x] The code architecture and patterns are consistent with the rest of the codebase.
- [x] The changes have been tested following the [documented guidelines](https://docs.tuist.io/contributors/testing-strategy/).
- [x] The `CHANGELOG.md` has been updated to reflect the changes. In case of a breaking change, it's been flagged as such.
- [ ] In case the PR introduces changes that affect users, the documentation has been updated.
- [ ] In case the PR introduces changes that affect how the cache artifact is generated starting from the `TuistGraph.Target`, the `Constants.cacheVersion` has been updated.

### CODE REVIEW

**Comment by luispadron** [comment]
Id like to understand why that was originally there, if no tests fail then i'd say this should be merged.

**Review by luispadron — APPROVED** [review]
Could you also see about adding a test to assert this behavior

**Comment by hisaac** [comment]
> Id like to understand why that was originally there, if no tests fail then i'd say this should be merged.

It's a good question, and it took some digging to suss out.

The change was added in #2000, with the goal of speeding up unit test runs. And the specific xcargs used were pulled from [this StackOverflow answer](https://stackoverflow.com/a/39901677/4118208) and the fact that [fastlane does the same thing](https://github.com/fastlane/fastlane/blob/d4a761a2c3ac02766f5aeded92224220e6af8b7b/gym/lib/gym/generators/build_command_generator.rb#L62). [The accepted StackOverflow answer in that same thread](https://stackoverflow.com/a/11647504/4118208) though, doesn't mention the `CODE_SIGNING_ALLOWED=NO` flag, so it seems like it's not required.

**Comment by hisaac** [comment]
> Could you also see about adding a test to assert this behavior

Good call, I'll do that 👍

[ ] Add test to assert `CODE_SIGNING_ALLOWED=NO` is not passed to the `xcodebuild` command for tests

**Comment by luispadron** [comment]
> > Id like to understand why that was originally there, if no tests fail then i'd say this should be merged.
> 
> 
> 
> It's a good question, and it took some digging to suss out.
> 
> 
> 
> The change was added in #2000, with the goal of speeding up unit test runs. And the specific xcargs used were pulled from [this StackOverflow answer](https://stackoverflow.com/a/39901677/4118208) and the fact that [fastlane does the same thing](https://github.com/fastlane/fastlane/blob/d4a761a2c3ac02766f5aeded92224220e6af8b7b/gym/lib/gym/generators/build_command_generator.rb#L62). [The accepted StackOverflow answer in that same thread](https://stackoverflow.com/a/11647504/4118208) though, doesn't mention the `CODE_SIGNING_ALLOWED=NO` flag, so it seems like it's not required.

Nice! Id be curious to see the performance difference, not sure the original PR covered that much. 

In this case I think it makes sense to merge your PR imo.

**Comment by ezraberch** [comment]
With just the identity/required/entitlements arguments, `xcodebuild` is signing even on a clean `tuist init` project. Is there any value in keeping those 3 arguments when you're removing `CODE_SIGNING_ALLOWED`?

**Comment by luispadron** [comment]
> With just the identity/required/entitlements arguments, `xcodebuild` is signing even on a clean `tuist init` project. Is there any value in keeping those 3 arguments when you're removing `CODE_SIGNING_ALLOWED`?

Good point may want to remove those as well

**Review by danyf90 — APPROVED** [review]

**Comment by hisaac** [comment]
> With just the identity/required/entitlements arguments, `xcodebuild` is signing even on a clean `tuist init` project. Is there any value in keeping those 3 arguments when you're removing `CODE_SIGNING_ALLOWED`?

That's a good point. I mistakenly assumed it wasn't signing the test target, but still signed the test host, but it's still signing both when you remove that argument.

Any objections to removing them all, since they don't actually restrict code signing with the `CODE_SIGNING_ALLOWED=NO` arg removed? If being able to skip code signing is important, we could probably try some fancy stuff with modifying the test target's build settings prior to running the tests or something. I'm not sure that would work though.

**Comment by hisaac** [comment]
Or maybe the better move is to leave the `skipSigning` option there so it's available for use — it does correctly skip signing when it's used with the `CODE_SIGNING_ALLOWED=NO` — but just not have test targets use it by default.

**Comment by hisaac** [comment]
Another option — just throwing out ideas — could be to skip signing by default, unless a test target has an App as a dependency. There may be other instances where a test target needs to be signed though, I'm honestly not very familiar with that.

**Comment by luispadron** [comment]
Should this be part of `3.0.0`? It would break the default behavior of not signing but I'm not sure who is depending on that / why.

**Pull request merged**
