### PR TITLE
Feature/completions

### PR DESCRIPTION
**Pull request by fortmarek**
Resolves https://github.com/tuist/tuist/issues/1592

### Short description 📝

Swift argument parser now supports generating completion scripts, so let's support that 🎉 

### Solution 📦

Most work has been done by just updating the argument parser version. There have been some other optimizations made such as adding `completion: .directory` to autocomplete directories for `--path` option etc.

### Implementation 👩‍💻👨‍💻

- [x] Update libraries
- [x] Optimize completion
- [x] Add documentation
- [x] Update changelog

### CODE REVIEW

**Comment by jeroenleenarts** [comment]
I think it looks good.

I am wondering about one thing though. This pull allows for the creation of the completion scripts.

tuist is installed by the `tuistenv` tool. I have not looked into the details of `tuistenv`. But would it be possible to ease the installation of completions by symlinking from the mentioned directories in the documentation file?

The location of the system wide tuist install is well known.

The location of likely completion script locations is mostly well known. Since homebrew is a tool supported by tuist I would expect it to integrate "well" with homebrew. I reckon there might be other tools or well known locations as well we might need to check for linking the completion scripts.

I think it would be great if tuist would do a best effort to get command completion activated in likely end-user scenarios. Also on `tuist update` we would need to update the completion scripting. Only supporting the latest version's completion scripting seems like an acceptable compromise.

**Comment by fortmarek** [comment]
Hey, those are valid concerns, @jeroenleenarts!

> Since homebrew is a tool supported by tuist I would expect it to integrate "well" with homebrew

I think we should focus mainly on the recommended script, I even thought we had dropped homebrew support. But if we still support homebrew (which I am actually unsure of), we should try to handle that as well. 

> The location of likely completion script locations is mostly well known.

"mostly well known" is the key here. But we can, indeed, make our best effort to generate the completion script - but some setups might be more complicated than others. There's some logic that we'll need to implement and I'm just worried about messing up user's environment. Eg. we should add the following to `~/.zshrc` if user uses `zsh` without `oh-my-zsh`: 
```
fpath=(~/.zsh/completion $fpath)
autoload -U compinit
compinit
```

But what if the users have a different way of enabling completions for `~/.zsh`? So, my thinking is that it might be best to try to find standard completion directories and copy our file there, but I am not sure if changing the global dot files could not produce some unwanted results.

But let me make this PR WIP and I'll try to make another iteration and look at what other tools are doing.

**Comment by pepibumur** [comment]
I'm not very familiar about how auto-completion is hooked into the shell, but I don't think `tuistenv` should install the auto-completion config files because the auto-completion is specific to the version of Tuist that gets activated in each directory. What about doing the following:

1. Add a `tuist init -` command.
2. The installation of Tuist extends the user's shell profile to eval the command: `eval "$(swiftenv init -)"`
3. The evaluation of the command would activate the right auto-completion configuration when cd'ing into directories.

Notice how [swiftenv](https://swiftenv.fuller.li/en/latest/installation.html) does it for activating the right version of Swift.

I think that can be part of another PR.

**Comment by fortmarek** [comment]
Unmarking this as a draft then, I'll create a separate issue for automating autocompletion

**Comment by fortmarek** [comment]
It seems like the PR Xcode 11.3.1 build fails, although 11.5 succeeds. It seems as if `Argument parser` itself is not buildable with older Xcodes anymore - I have tried to build it but I keep getting the following segmentation fault: 
`1.	While emitting IR SIL function "@$s14ArgumentParser31AutodetectedGenerateCompletionsV24generateCompletionScriptACSb_tcfC".
 for 'init(generateCompletionScript:)' (at /Users/marekfort/Downloads/swift-argument-parser/Sources/ArgumentParser/Parsing/CommandParser.swift:240:8)`

We can try to fix `ArgumentParser` support for older Xcodes, but as Xcode 12 is right around the corner, maybe we can think about dropping support for Xcode 11.3.1. Could you remind me, @pepibumur, what's the reason we still have to support it? (if I recall correctly, it's about `.swiftinterface` file, but couldn't find the specifics).

**Comment by pepibumur** [comment]
> We can try to fix ArgumentParser support for older Xcodes, but as Xcode 12 is right around the corner, maybe we can think about dropping support for Xcode 11.3.1. Could you remind me, @pepibumur, what's the reason we still have to support it? (if I recall correctly, it's about .swiftinterface file, but couldn't find the specifics).

It's hard to tell because we don't have analytics, but I think there might be some users using Xcode 11.3.1 still. The last time this discussion came up a few months ago @kwridan mentioned that they were still using it on CI.

**Comment by fortmarek** [comment]
What is the status at your current team, @kwridan? We can try to migrate to 11.4 at least if 11.5 is unreasonable (will need to check if it builds on 11.4). Of course, I can investigate it further, but since we have to migrate sooner or later, it'd make sense to me to make the jump now.

**Comment by pepibumur** [comment]
> What is the status at your current team, @kwridan? We can try to migrate to 11.4 at least if 11.5 is unreasonable (will need to check if it builds on 11.4). Of course, I can investigate it further, but since we have to migrate sooner or later, it'd make sense to me to make the jump now.

@fortmarek I pushed a change depressing 11.3.1 & Xcode 11.4. I also updated the CHANGELOG to include the deprecation and mark it as breaking. We need to make sure we mention on the release blog post that we are deprecating those versions of Xcode.

**Pull request merged**
