### PR TITLE
Add --strict to 'lint code' command

### LINKED ISSUE #2421: Linting with Tuist returns wrong exit code, always returns 0
**Describe the bug**
Use Swiftlint and setup a config in `Tuist/.swiftlint.yml`. If you have violations you should receive an exit code that is non-zero. However, it seems like the return code is always 0. 

**To Reproduce**

1. Setup Swiftlint with a config file
2. Have no violations and run `tuist lint code` and get `Done linting! Found 0 violations, 0 serious in 94 files.`, return code is 0 (can be seen by using `echo $?`)
3. Create some violations and run `tuist lint code` and get `Done linting! Found 4 violations, 0 serious in 94 files.`, return code is 0 (can be seen by using `echo $?`)

**Expected behavior**
A failing case should return e.g. 1 as return code.

**Desktop (please complete the following information):**

- OS: macOS
- Version: 1.31.0

** Context**
Trying to use this command instead of using a standalone swiftlint installation in my CI.

### PR DESCRIPTION
**Pull request by joshdholtz**
Resolves https://github.com/tuist/tuist/issues/YYY
Request for comments document (if applies):

### Short description 📝

Resolves #2421

- Adds new `--strict` flag to `tuist lint code`

#### Tested By

```sh
swift run tuist lint code --path ../MyApp
echo $? # returns 0
```

```sh
swift run tuist lint code --path ../MyApp --strict
echo $? # returns 1
```

### Checklist ✅

- [x] The code architecture and patterns are consistent with the rest of the codebase.
- [x] The changes have been tested following the [documented guidelines](https://tuist.io/docs/contribution/testing-strategy/).
- [x] The `CHANGELOG.md` has been updated to reflect the changes. In case of a breaking change, it's been flagged as such.
- [ ] In case the PR introduces changes that affect users, the documentation has been updated.

### CODE REVIEW

**Review by fortmarek — COMMENTED** [review]
This is a welcome addition, thanks @joshdholtz!

The code is well-aligned with the rest of the codebase.

I'd just make two additions:
- Add the flag to `linking.mdx` in the documentation
- I'd write a new acceptance tests in `lint-code.feature` => we try to always have user-facing new features tested end-to-end. 

There's `app_with_framework_where_framework_failing_swiftlint` you can edit and the acceptance test is in `lint-code.feature`. There's already a test with `Then tuist lints code of target with name "App" and passes`, so I'd just introduce a warning to `App` and add a new line containing `Then tuist strict lints code of target with name "App" and passes` (you can add the definition in `lint-code.rb`).

You can also read more about our acceptance tests [here](https://tuist.io/docs/contribution/testing-strategy/) (you can run the tests with `./bin/fourier test tuist acceptance features/lint-code.feature`)

**Comment by pepibumur** [comment]
@all-contributors add @joshdholtz for code

**Review by pepibumur — APPROVED** [review]
Besides @fortmarek comments, it looks great!

**Review by laxmorek — APPROVED** [review]
I would never have thought that I would be doing a code review to creator of Fastlane. The Josh himself. :P 

PR looks good and as Pedro wrote please take a look on @fortmarek comments.

**Comment by fortmarek** [comment]
@pepibumur was this merged by accident?

**Comment by joshdholtz** [comment]
Would you like me to create a followup PR that adds the tests and docs? 😊

**Comment by fortmarek** [comment]
That'd be great @joshdholtz, sorry for this back-and-forth 🙇

**Comment by joshdholtz** [comment]
Np np! Happy to up my PR count to 2 😉

**Pull request merged**
