### PR TITLE
Change product name lint severity to warning

### PR DESCRIPTION
**Pull request by adellibovi**
Resolves https://github.com/tuist/tuist/issues/2745
Request for comments document (if applies):

### Short description 📝

I changed the severity to warning as suggested in #2745, ~~I also allowed support for (.) dot characters. In case there was a good reason to avoid those I can revert and only include the error to warning change.~~

### Checklist ✅

- [x] The code architecture and patterns are consistent with the rest of the codebase.
- [x] The changes have been tested following the [documented guidelines](https://docs.tuist.io/contributors/testing-strategy/).
- [x] The `CHANGELOG.md` has been updated to reflect the changes. In case of a breaking change, it's been flagged as such.
- [x] In case the PR introduces changes that affect users, the documentation has been updated.

### CODE REVIEW

**Review by kwridan — COMMENTED** [review]
Thanks for submitting this @adellibovi

Locally testing it seems that indeed Xcode is happy to accept target and product names with the `.` character, however maps it slightly differently in different cases.

For example a target `Foo.Bar` and `Foo.BarTests`

- For bundle IDs it automatically replaces the `.` with a `-`

Screenshot 2021-05-31 at 07 23 23

- Even though the product name is `Foo.Bar`, when importing it in code, you'll need to use `import Foo_Bar`

Screenshot 2021-05-31 at 07 32 12


```swift
import XCTest
@testable import Foo_Bar

class Foo_BarTests: XCTestCase {
 // ...
}
```

Given that it can lead to some inconsistencies I'm leaning towards not including it, did you have more insights into cases where it may be needed?

**Review by kwridan — APPROVED** [review]

**Comment by adellibovi** [comment]
Thanks @kwridan, that seems like a valid reason to not exclude from the lint rule.
I had some products (mainly resources bundles) that includes the dot and I was not importing them (therefor not having the . - conversion).
Anyway having the lint severity to warning is good enough ☺️
PR updated!

**Comment by ollieatkinson** [comment]
When the product identifier is included through cx99identifier xcodebuild automatically swaps some invalid characters - if you use the defaults things will be ok, however if you deviate (e.g manually specify) you may run into problems

**Review by ollieatkinson — APPROVED** [review]
A warning seems good here, since its not always breaking

**Pull request merged**
