### PR TITLE
Fix XCConfig path for swift package dependencies

### PR DESCRIPTION
**Pull request by shahzadmajeed**
Resolves https://github.com/tuist/tuist/issues/4443
Request for comments document (if applies):

### Short description 📝

Swift package dependencies were not picking XCConfigurations because of wrong path generated during `fetch` phase.

### How to test the changes locally 🧐

1. Use `ios_app_with_multi_configs` fixture project which contains a local swift package and try to use existing configuration in `ConfigurationFiles` 
2. Run `tuist fetch`
3. Run `tuist generate`
4. Generated project should have `LocalSwiftPackage` project which should be using XCConfigurations from `ConfigurationFiles` path

### Checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase.
- [ ] The changes have been tested following the [documented guidelines](https://docs.tuist.io/contributors/testing-strategy/).
- [ ] The PR includes the label `changelog:added`, `changelog:fixed`, or `changelog:changed`, whenever it should be included in the “Added”, “Fixed” or “Changed” section of the CHANGELOG. Note: when included in the CHANGELOG, the title of the PR will be used as entry, please make sure it is clear and suitable.
- [ ] In case the PR introduces changes that affect users, the documentation has been updated.
- [ ] In case the PR introduces changes that affect how the cache artifact is generated starting from the `TuistGraph.Target`, the `Constants.cacheVersion` has been updated.

### CODE REVIEW

**Review by danyf90 — CHANGES_REQUESTED** [review]
Thanks! 🚀 

As this is a fix for SPM mapping, could you please add the changes to the `app_with_spm_dependencies` fixture instead? 🙏

**Review by danyf90 — APPROVED** [review]
Does the fixture change actually tests the fix (i.e. does the fixture test fails without the fix)?

**Comment by shahzadmajeed** [comment]
> 

Is there a unit test for fixture or are you referring to manual testing? If manual testing, then yes, the fixture fails without the fix and you can see the generated `LocalSwiftPackage` using specified XCConfigurations when used the fix (via fourier in current branch)

**Comment by shahzadmajeed** [comment]
> > Is there a unit test for fixture or are you referring to manual testing? If manual testing, then yes, the fixture fails without the fix and you can see the generated `LocalSwiftPackage` using specified XCConfigurations when used the fix (via fourier in current branch)
> 
> Yes there are acceptance tests that are run in CI. You can run it locally using Fourier. For the exact command check the `dependencies` check you can find among the GitHub checks

Oh right, it seems like they all passed. I can try to run them locally as well next time

**Comment by danyf90** [comment]
> > Yes there are acceptance tests that are run in CI. You can run it locally using Fourier. For the exact command check the `dependencies` check you can find among the GitHub checks
> 
> 
> 
> Oh right, it seems like they all passed. I can try to run them locally as well next time

My point is, are they testing the new change? I.e. do they fail if you comment out the fix?

**Pull request merged**
