### PR TITLE
 Copy path for XCFrameworks to folders to support multiple Package.swift files for each Package in `/Vendor`

### PR DESCRIPTION
**Pull request by apps4everyone**
### Short description 📝

For an existing project all external dependencies have to be in a specific folder `/Vendor` because they are binary files inside SPM definitions to replace external url based dependencies with one settings flag. 

This is solved by an optional `copyPath` (renamed from installationPath):

Zrzut ekranu 2021-05-4 o 17 39 47

Bool switch:

Screenshot 2021-05-04 at 17 28 56

SPM Package with binary in Vendor folder:

Screenshot 2021-05-04 at 17 26 18

Some have multiple targets and therefore more than one XCFramework, this is solved by `names`:

Screenshot 2021-05-04 at 17 41 06

### Checklist ✅

- [x] The code architecture and patterns are consistent with the rest of the codebase.
- [x] The changes have been tested following the [documented guidelines](https://docs.tuist.io/contributors/testing-strategy/).
- [ ] The `CHANGELOG.md` has been updated to reflect the changes. In case of a breaking change, it's been flagged as such.
- [ ] In case the PR introduces changes that affect users, the documentation has been updated.

### CODE REVIEW

**Comment by laxmorek** [comment]
Hey @apps4everyone 👋

First of all thank you for your contribution to the tuist. It is always awesome to see new ideas and get to know different points of view.

If I understand correctly your use case you want to make post installation action that copy result of `tuist dependencies x` into a given path. Please correct me if I am wrong. 

I would like to leave my doubts here. Extending `Dependencies.swift` with this kind of logic may increase complexity of future development. I afraid a situation when dependencies will be saved in a few places (your changes allow to save dependency A at one path and dependency B at other). I understand that changes introduced in your PR works today but today's implementation of `tuist dependencies x` is nothing more than dummy layer built on the top of dependency managers. 

I think the upcoming `Task.swift` functionality seems to me to meet your needs better. Before it will be implemented I'd suggest to write own `rake`/`fastlane`/`script` that copy files you need. 

Alternatively if we want to extend `Dependencies.swift` with `installationPath` Id suggest adding this new property to `Dependencies` struct instead of `CarthageDependencies.Dependency`. Thanks to this, we will have guarantees there will be always only one path for dependencies but the developers will be able to define it.  

I would also like to hear @pepibumur and @fortmarek opinions. Maybe my doubts here maybe my doubts are exaggerated. I am open for a discussion here.

**Comment by apps4everyone** [comment]
> Hey @apps4everyone 👋
> 
> First of all thank you for your contribution to the tuist. It is always awesome to see new ideas and get to know different points of view.
> 
> If I understand correctly your use case you want to make post installation action that copy result of `tuist dependencies x` into a given path. Please correct me if I am wrong.
> 
> I would like to leave my doubts here. Extending `Dependencies.swift` with this kind of logic may increase complexity of future development. I afraid a situation when dependencies will be saved in a few places (your changes allow to save dependency A at one path and dependency B at other). I understand that changes introduced in your PR works today but today's implementation of `tuist dependencies x` is nothing more than dummy layer built on the top of dependency managers.
> 
> I think the upcoming `Task.swift` functionality seems to me to meet your needs better. Before it will be implemented I'd suggest to write own `rake`/`fastlane`/`script` that copy files you need.
> 
> Alternatively if we want to extend `Dependencies.swift` with `installationPath` Id suggest adding this new property to `Dependencies` struct instead of `CarthageDependencies.Dependency`. Thanks to this, we will have guarantees there will be always only one path for dependencies but the developers will be able to define it.
> 
> I would also like to hear @pepibumur and @fortmarek opinions. Maybe my doubts here maybe my doubts are exaggerated. I am open for a discussion here.

hey, thx for the first feedback, the root problem for me is SPM not able to use relative paths like this in for binaryTarget:

```swift
import PackageDescription

let package = Package(
    name: "Dependencies",
    products: [
        .library(
            name: "Alamofire",
            targets: ["Alamofire"]
        )
    ],
    targets: [
        .binaryTarget(name: "Alamofire", path:"./../Tuist/Dependencies/Carthage/Alamofire.xcframework")
    ]
)
```

or package:

```swift
// Using 'path', we can depend on a local package that's
// located at a given path relative to our package's folder:
.package(path: "../Alamofire")
```

**Comment by fortmarek** [comment]
> hey, thx for the first feedback, the root problem for me is SPM not able to use relative paths like this in for binaryTarget:

if it's only for this reason, would not making a symlink suffice here?

**Comment by apps4everyone** [comment]
> > hey, thx for the first feedback, the root problem for me is SPM not able to use relative paths like this in for binaryTarget:
> 
> if it's only for this reason, would not making a symlink suffice here?

Maybe, but the symlinks I can't create from `Dependencies.swift`. So I have to create them manfully (or with shel sprint) and not on CI commit on changes in `Dependencies.swift` (e.g. is someone is adding a new package then annually the symlink has to be created). But maybe this is too much. Wanted to avoid a shel sprint and wanted to solve this by contributing to Tuist. But it looks like no one is interested in this...

**Comment by apps4everyone** [comment]
don't know why this is failing: `Checks / Lint code with Xcode 12`

**Comment by fortmarek** [comment]
> But it looks like no one is interested in this...

I would not say that no one is interested in this but we have to try to keep the API surface as small as possible to make the tool comprehensible to others - that's why we first to try to see if there is a different solution that allows you to solve your problem without extending the API.

> Maybe, but the symlinks I can't create from Dependencies.swift. So I have to create them manfully (or with shel script) and not on CI commit on changes in Dependencies.swift (e.g. is someone is adding a new package then annually the symlink has to be created). But maybe this is too much. Wanted to avoid a shel script and wanted to solve this by contributing to Tuist. 

I think you can create a symlink for the whole `Dependencies` directory and then you would not need to add any new symlinks if you add a dependency. Would that solve your issue?

**Comment by pepibumur** [comment]
👋🏼 joining the discussion. What I'm seeing in what's proposed in this PR is that we are coupling Tuist to a specific project setup, and that's not a good idea for the project long-term. I'd try to answer **why a package is depending on a binary generated by `tuist dependencies`**? `tuist dependencies` has not been designed for developers to use it beyond their project definitions. It's possible there's a use case we are not seeing and we should consider, but before we do that, we need to understand the need. 
I'd also suggest starting from an issue. Saying no to the code proposed on a PR is not good for contributors that put effort into it, and us, because we'd like your contributions to land on the project.

**Comment by apps4everyone** [comment]
> > But it looks like no one is interested in this...
> 
> I would not say that no one is interested in this but we have to try to keep the API surface as small as possible to make the tool comprehensible to others - that's why we first to try to see if there is a different solution that allows you to solve your problem without extending the API.
> 
> > Maybe, but the symlinks I can't create from Dependencies.swift. So I have to create them manfully (or with shel script) and not on CI commit on changes in Dependencies.swift (e.g. is someone is adding a new package then annually the symlink has to be created). But maybe this is too much. Wanted to avoid a shel script and wanted to solve this by contributing to Tuist.
> 
> I think you can create a symlink for the whole `Dependencies` directory and then you would not need to add any new symlinks if you add a dependency. Would that solve your issue?

could we define the path like in `let config = Config(cache: .cache(path: .relativeToRoot("Cache"))]))` and an optional flag to use subfolders to have like:
`path: .relativeToRoot("Vendor"), useSubfolders: true`
 `/Vendor/AppCenter`
 `/Vendor/Alamofire`
 ...

**Pull request closed without merging**
