### PR TITLE
Support for `mlmodelc` resources

### PR DESCRIPTION
**Pull request by mikchmie**
Resolves https://github.com/tuist/tuist/issues/4322#issuecomment-1095453159
Request for comments document (if applies):
If there's a test suite that I should extend with test case for this directory extension, please let me know.

### Short description 📝

Fix the way compiled ML models (`*.mlmodelc` directories) are treated. Currently Tuist tries to add their contents to copy resources build phase (unnecessarily) and fails with message:

> Trying to add a file at path /[...]/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/stripe-ios/StripeCardScan/StripeCardScan/Resources/CompiledModels/SSDOcr.mlmodelc/analytics/coremldata.bin to a build phase that hasn't been added to the project.

while they should be treated as opaque, sealed packages (like `xcassets`).

### How to test the changes locally 🧐

1. Download test project from linked issue
2. Remove `.tuist_version` file
3. `tuist fetch`
4. `tuist generate`
5. `tuist test`

### Checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase.
- [ ] The changes have been tested following the [documented guidelines](https://docs.tuist.io/contributors/testing-strategy/).
- [ ] The PR includes the label `changelog:added`, `changelog:fixed`, or `changelog:changed`, whenever it should be included in the “Added”, “Fixed” or “Changed” section of the CHANGELOG. Note: when included in the CHANGELOG, the title of the PR will be used as entry, please make sure it is clear and suitable.
- [ ] In case the PR introduces changes that affect users, the documentation has been updated.
- [ ] In case the PR introduces changes that affect how the cache artifact is generated starting from the `TuistGraph.Target`, the `Constants.cacheVersion` has been updated.

### CODE REVIEW

**Review by danyf90 — APPROVED** [review]

**Comment by danyf90** [comment]
Thanks @mikchmie! 🙏
Can you add such kind of resource to one of the fixtures? 🙏
Maybe just adding that dependency to app_with_spm_dependencies should be enough

**Comment by mikchmie** [comment]
> Can you add such kind of resource to one of the fixtures? 🙏

Sure

> Maybe just adding that dependency to app_with_spm_dependencies should be enough

The funny thing is... it's already there. But the problem surfaces only if one of these conditions is met:
a) You run `tuist generate` and `StripeCardScan` target is linked to a user-defined targets;
b) You run `tuist test`.

@danyf90 Maybe you know why the `test` command parses unused external targets, while `generate` and `build` don't?

**Comment by danyf90** [comment]
Yep that's a problem of tuist test. To replicate the issue you can just add the problematic target as a dependency of the project I guess

**Comment by mikchmie** [comment]
> you can just add the problematic target as a dependency of the project

Yup, just did 🙂

**Comment by danyf90** [comment]
@mikchmie could you please run `./fourier lint tuist --fix` to fix linting? 🙏

**Pull request merged**
