### PR TITLE
Tuist Macro Improvements

### PR DESCRIPTION
**Pull request by waltflanagan**
### Short description 📝

Add `ProjectDescription.TargetDependency.macro`  as a more explicit dependency declaration (vs `.target() or .project()`)
We had a need to differentiate between macro dependencies and regular `.target` dependencies in our own implementation and this distinction seemed valuable from a usability perspective as well.  In the end it resolves to an XcodeGraph.TargetDependency in the same way as before and is mostly and end-user facing change.  using `.target` or `.project` to link to a macro would still work but `.macro` feels more explicit and helps keep macros and frameworks colocated in the same project.   Feedback very welcome on this part of the PR.

Updates a fixture with an example macro implementation using Tuist declarations.

> Describe here the purpose of your PR.

Change is tested with the fixture update.

### Contributor checklist ✅

- [x] The code has been linted using run `mise run lint-fix`
- [x] The change is tested via unit testing or acceptance testing, or both
- [x] The title of the PR is formulated in a way that is usable as a changelog entry
- [x] In case the PR introduces changes that affect users, the documentation has been updated

### Reviewer checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase
- [ ] Reviewer has checked that, if needed, the PR includes the label `changelog:added`, `changelog:fixed`, or `changelog:changed`, and the title is usable as a changelog entry

### CODE REVIEW

**Comment by pepicrft** [comment]
> We had a need to differentiate between macro dependencies and regular .target dependencies in our own implementation and this distinction seemed valuable from a usability perspective as well. In the end it resolves to an XcodeGraph.TargetDependency

Would you mind expanding on the need for that differentiation?

**Comment by waltflanagan** [comment]
@pepicrft we have a `Module` layer on top of tuist primitives that helps us manage explicit dependencies by converting transient implicit dependencies into explicit dependency references.  we need to have some way of identifying the *kind* of dependency at the `ProjectDescription` level beyond just `.product` or `.target` as those lack any info about the product type.  

We can easily accomplish that in other ways with but this addition felt helpful from the perspective of usability of defining macros and frameworks that depend on them.  Since we have a macro kind in [GraphDependencyReference](https://github.com/tuist/tuist/blob/895684b48c118f033d487283ee8522eccc209a8e/Sources/TuistCore/Graph/GraphDependencyReference.swift#L21) it felt useful to match that distinction in `ProjectDescription` and `ProjectAutomation` so that the "this is a macro" information isn't lost.

**Comment by pepicrft** [comment]
> @pepicrft we have a Module layer on top of tuist primitives that helps us manage explicit dependencies by converting transient implicit dependencies into explicit dependency references. we need to have some way of identifying the kind of dependency at the ProjectDescription level beyond just .product or .target as those lack any info about the product type.

I see what you mean. I think it also makes sense from the perspective of validation. If you have an iOS framework that depends on a macOS executable, is that a mistake? Is that a macro? We would be able to tell by looking at the executable's sources, but we can better consider it a mistake and recommend being explicit about the macro dependency type.

I'm onboard with that

**Comment by waltflanagan** [comment]
I'm going to remove the tests definition for now since that more seems like a new thing we need to have proper support for that's not coupled to the initial goals of the PR.

**Review by danieleformichelli — APPROVED** [review]

**Review by danieleformichelli — APPROVED** [review]

**Pull request merged**
