### PR TITLE
Treat CoreData files as resources for static/dynamic bundle generation

### PR DESCRIPTION
**Pull request by thedavidharris**
### Short description 📝

Although the generation of code to access `Bundle.module` exists for resources, it does not get generated for other types of "resources" that also get accessed via bundles, like CoreData.

### Checklist ✅

- [x] The code architecture and patterns are consistent with the rest of the codebase.
- [x] A developer other than the author has verified that the changes work as expected.
- [x] The changes have been tested following the [documented guidelines](https://tuist.io/docs/contribution/testing-strategy/).
- [x] The `CHANGELOG.md` has been updated to reflect the changes. In case of a breaking change, it's been flagged as such.
- [x] In case the PR introduces changes that affect users, the documentation has been updated.

A future note: there might be some opportunities for alignment with how Swift Package Manager handles resources: https://github.com/apple/swift-package-manager/blob/ea0b31edaaae8ca82a7a92ce6b02940b6cbc9f1f/Sources/XCBuildSupport/PIF.swift#L1066 for example

### CODE REVIEW

**Review by kwridan — COMMENTED** [review]
Thanks for the addition @thedavidharris - the changes look good 👍 

Are core data models treated as resources or sources? Looking at the code in [BuildPhaseGenerate](https://github.com/tuist/tuist/blob/main/Sources/TuistGenerator/Generator/BuildPhaseGenerator.swift#L208) it looks like we're including them as sources _(tuist used to treat them as resources, but that was later changed to sources due to the issue https://github.com/tuist/tuist/issues/1539)_

**Comment by thedavidharris** [comment]
@kwridan It's both, they are "resources" in the sense that you look up the momd file by bundle, but need to be added as sources as there's a compilation aspect (`xcrun momc` I believe)

**Comment by kwridan** [comment]
Thanks for clarifying @thedavidharris, I suspect the generation logic for core data is lacking / missing some more cases. With the change, the generated `Resources` bundle target will end up having an executable in the final built product which I believe is invalid for iOS applications (App Store may reject the binary https://github.com/tuist/tuist/issues/1360)

It's helpful to test this out in a fixture - the closest one I could find is `ios_app_with_coredata`

Made a small tweak to it to include a static framework:

```swift
let project = Project(name: "App",
                      targets: [
                        Target(name: "App",
                               platform: .iOS,
                               product: .app,
                               bundleId: "io.tuist.app",
                               infoPlist: "Info.plist",
                               sources: ["Sources/**"],
                               coreDataModels: [
                                 CoreDataModel("CoreData/Users.xcdatamodeld", currentVersion: "1")
                               ]),
                        Target(name: "MyFramework",
                             platform: .iOS,
                             product: .staticFramework,
                             bundleId: "io.tuist.framework",
                             infoPlist: .default,
                             sources: ["Sources/Model.swift"],
                             coreDataModels: [
                               CoreDataModel("CoreData/Users.xcdatamodeld", currentVersion: "1")
                             ])
                      ])
```

The project generates successfully, but now the bundle includes a source file which once built will result in a `.bundle` with an executable :/

Screenshot 2021-01-26 at 18 51 44

I wonder if in this scenario, we need to add core data models the resource phase instead of the sources phase? it's a bit awkward, the compilation happens in the Static framework, but the models are included in the Bundle target ... is that even valid? 🤔

**Comment by thedavidharris** [comment]
@kwridan makes sense, I can test out that fixture as this is definitely a new case (and one that isn't discussed much on the internet)

**Comment by thedavidharris** [comment]
Added a fixture on this. It's a bit more involved than I assumed (also converted this to draft which it should've been, as it needs some verification). 

Largely, this does correctly allow you to now instantiate the Core Data stack using `Bundle.module`, but actually using that object I'm running into some trouble (as can be seen if you generate that fixture). Will have to poke around more.

**Comment by thedavidharris** [comment]
I've pushed a working fixture on this: it does still add the xcdatamodel to Compile Sources for the Resources bundle, but can confirm this works if you manually drag it to resources (and that gets rid of the executable in the bundle) so should be good to fix that next.

Notably, this does make some changes in how the xcdatamodel name needs to be prefixed

**Comment by kwridan** [comment]
Awesome, thanks for the thorough investigation @thedavidharris ! 

I can take a look at the changes needed to get it to the resources build phase for `.bundle` targets. I believe we'll need to condition it such that if `target.supportsSources` -> sources build phase, otherwise -> resources build phase.

**Comment by thedavidharris** [comment]
Thanks @kwridan ! Think this looks ready now.

**Review by kwridan — APPROVED** [review]

**Pull request merged**
