### PR TITLE
fix: rename macOS app build

### PR DESCRIPTION
**Pull request by TahaTesser**
Resolves https://github.com/tuist/tuist/issues/6801

### Short description 📝

When download Tuist macOS app i got lost finding the app in the downloads then realized it's just named "app.dmg" and not "Tuist.dmg" or something relatable.

This renames the Tuist macOS app from "app.dmg" to "Tuist.dmg".

### Contributor checklist ✅

- [ ] The code has been linted using run `mise run lint-fix`
- [ ] The change is tested via unit testing or acceptance testing, or both
- [x] The title of the PR is formulated in a way that is usable as a changelog entry
- [ ] In case the PR introduces changes that affect users, the documentation has been updated

### Reviewer checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase
- [ ] Reviewer has checked that, if needed, the PR includes the label `changelog:added`, `changelog:fixed`, or `changelog:changed`, and the title is usable as a changelog entry

### CODE REVIEW

**Review by danieleformichelli — APPROVED** [review]

**Review by fortmarek — APPROVED** [review]
ahh, good catch! This is definitely better, thanks 💜

**Comment by fortmarek** [comment]
@TahaTesser I updated the PR to make the `conventional-pr` check pass

**Comment by TahaTesser** [comment]
> This renames the Tuist macOS app from "app.dmg" to "Tuist.dmg".

Just added a commit message based on the analyzer error.

**Comment by fortmarek** [comment]
> Just added a commit message based on the analyzer error.

Same 😆 

LGTM once the CI passes 🙌

**Pull request merged**
