### PR TITLE
Graphviz

### PR DESCRIPTION
**Pull request by engali94**
### Short description 📝

>  Extended `GraphGenerator` to generate `png` images instead of `.dot` files.

### Solution 📦

> By utilizing [GraphViz](https://github.com/SwiftDocOrg/GraphViz), now the `tuist graph` command generates images in `.png` format. This can be even extended further as `GraphViz` supports many other formats.

### Implementation 👩‍💻👨‍💻

- [x] Refactored `GraphToDotGraphMapper` by integrating  `GraphViz` and dropped out the old `DotGraph` implementation.
- [x] Automated the `graphviz` tool installation process, instead of manually installing it.
- [x] Refactored `GraphToDotGraphMapperTests` and `GraphServiceTests`.
- [x] Updated `graph` command documentations.

### CODE REVIEW

**Comment by andreacipriani** [comment]
@engali94 For all the formatting changes, see: https://tuistapp.slack.com/archives/CCXC295QS/p1596550273394400

**Comment by engali94** [comment]
Congrats @andreacipriani 🎉 you came with a better implementation so I will close this PR  also as @kwridan mentioned I think you need to change from `.render(using: .circo, to: .png)` to `.render(using: .dot, to: .png)` to get more compact graph.

**Comment by andreacipriani** [comment]
Hey @engali94; it was actually my bad, I didn't see that you already opened a PR for this. Sorry about that!
Let's go for the best of the two implementations, I'm bringing some really good stuff from this PR and we'll co-author it!

**Comment by andreacipriani** [comment]
@kwridan Thanks for the tip, I'll go for `dot` instead of `circo`, although I've noticed that `dot` doesn't behave really well when you have > 30 nodes

**Pull request closed without merging**
