### PR TITLE
[WIP] Add imparted settings

### PR DESCRIPTION
**Pull request by adellibovi**
Resolves https://github.com/tuist/tuist/issues/YYY
Request for comments document (if applies):

### Short description 📝

There are certain settings (imparted settings), in certain conditions which needs to be inherited from direct and indirect clients of a dependency.
This is the same approach which SPM is using, and makes SPM frameworks like Realm compile correctly.

It's still a WIP, this works already, but I want to have more time to have a thought if there is a better way.

### How to test the changes locally 🧐

> Include a set of steps for the reviewer to test the changes locally.

### Checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase.
- [ ] The changes have been tested following the [documented guidelines](https://docs.tuist.io/contributors/testing-strategy/).
- [ ] The `CHANGELOG.md` has been updated to reflect the changes. In case of a breaking change, it's been flagged as such.
- [ ] In case the PR introduces changes that affect users, the documentation has been updated.
- [ ] In case the PR introduces changes that affect how the cache artifact is generated starting from the `TuistGraph.Target`, the `Constants.cacheVersion` has been updated.

### CODE REVIEW

**Comment by kwridan** [comment]
Thanks for looking into this @adellibovi 

I wonder if we're seeing those errors due to not generating Realm correctly - inspecting locally I see we don't add any of the headers to the generated project - thus the built Realm frameworks maybe incomplete and require further settings in upstream projects to workaround it 🤐

Screenshot 2022-01-17 at 08 16 40

For example, the attempting to build the `RealmCore` Target on its own fails due the missing define _(which exists in one of those missing headers)_

```
realm-core/src/realm/version.cpp:35:5: error: non-void function 'get_extra' should return a value [-Wreturn-type]
    return REALM_VERSION_EXTRA;
    ^
```

**Comment by danyf90** [comment]
@kwridan are you using Tuist from main? The `define` problems should have been solved [in this PR](https://github.com/tuist/tuist/pull/3995)

**Comment by adellibovi** [comment]
@danyf90 was faster on the reply hehe

> @kwridan are you using Tuist from main? The `define` problems should have been solved [in this PR](https://github.com/tuist/tuist/pull/3995)

@kwridan, regarding the header phase, it seems to me (I may be wrong) that is correct that we do not generate the header phase as we have a module map (or at least that's what spm is doing). Also, I checked the PIF Project generation in SPM, which is what Xcode (and XCBuild) uses under the hoods when "adding and building" a package, and the generated PIF Project has this concept of imparted settings: https://github.com/apple/swift-package-manager/blob/df5cce61242613edad2ca956612db296516d26c8/Sources/XCBuildSupport/PIFBuilder.swift#L602

I would be also happy to pursue the header phase approach, though I am not sure what the consequences could be. 🤔  Any idea?

**Comment by danyf90** [comment]
I remember that "blindly" adding headers to the header phase could create problems with some packages (e.g. `nanopb` if I remember correctly), so we tried to mimic SPM as much as possible.

Also, I think that the more we mimic SPM, the less likely is that we encounter edge cases

**Comment by kwridan** [comment]
Thanks for the clarification @danyf90 and @adellibovi 

> I checked the PIF Project generation in SPM, which is what Xcode (and XCBuild) uses under the hoods when "adding and building" a package, and the generated PIF Project has this concept of imparted settings: https://github.com/apple/swift-package-manager/blob/df5cce61242613edad2ca956612db296516d26c8/Sources/XCBuildSupport/PIFBuilder.swift#L602

TIL - wasn't aware of PIF 😅

> I remember that "blindly" adding headers to the header phase could create problems with some packages (e.g. nanopb if I remember correctly), so we tried to mimic SPM as much as possible.

Indeed it would require distinguishing public / private / project headers - which from what I can see there isn't a way to describe in package manifests, or at least isn't the case for [`realm-core`](https://github.com/realm/realm-core/blob/master/Package.swift).

This is a bit unfortunate, it means the built frameworks aren't well formed due to this limitation 😞 - by well formed here I mean, a built `.framework` bundle that includes the structure:

```
MyFramework.framework
├── Headers
│   ├── MyFramework.h
│   └── MyFrameworkPublicComponentA.h
├── Info.plist
├── Modules
│   └── module.modulemap
├── MyFramework
└── _CodeSignature
    └── CodeResources
```

Which has the benefit of allowing consumers of the framework to depend on it without further settings / configuration as its' headers / resources are all bundled within it.

I guess in SPM it's not necessarily dealing with frameworks per-se whereas Tuist is trying to produce native Xcode framework targets. I'm curious does this impair the ability to cache those dependencies? From my understanding, caching in Tuist complies dependencies and produces pre-built frameworks for consumption. Would those not suffer from the same issues?

**Comment by danyf90** [comment]
> I guess in SPM it's not necessarily dealing with frameworks per-se whereas Tuist is trying to produce native Xcode framework targets. I'm curious does this impair the ability to cache those dependencies? From my understanding, caching in Tuist complies dependencies and produces pre-built frameworks for consumption. Would those not suffer from the same issues?

I think the point is that even if you are using the compiled framework, for the way the project is generated the rest of the project can still read some information from the local `Tuist/Dependencies` folder. For example, with our current logic the modulemap files are not embedded into the framework and are loaded "locally", even for cached targets

**Comment by danyf90** [comment]
Keep it open 🚀

**Comment by danyf90** [comment]
Keep this open, I'll try to work on that soon 🙏

**Comment by denizdogan** [comment]
@danyf90 Sorry, has this been fixed?

**Comment by danyf90** [comment]
> @danyf90 Sorry, has this been fixed?

Nope, I'll try to have a look if I find time, but keeping the PR open with no one looking ad it wasn't useful:D

**Comment by thebarndog** [comment]
@danyf90 is there anything we the community can do to help this along?

**Comment by danyf90** [comment]
Hey @thebarndog , you can find more information here: https://github.com/tuist/tuist/issues/4688#issuecomment-1240297681

If you need any further help, feel free to write me on Slack

**Pull request closed without merging**
