### PR TITLE
Add support for runPostActionsOnFailure in BuildActions

### PR DESCRIPTION
**Pull request by FranzBusch**
### Short description 📝

Xcode supports to run post-build actions even if the build itself fails. This is useful when you want to collect data for build time analysis etc. I added support in `XcodeProj` in this [PR](https://github.com/tuist/XcodeProj/pull/603) and now I want to add it to Tuist.

### Checklist ✅

- [x] The code architecture and patterns are consistent with the rest of the codebase.
- [ ] The changes have been tested following the [documented guidelines](https://tuist.io/docs/contribution/testing-strategy/).
- [x] The `CHANGELOG.md` has been updated to reflect the changes. In case of a breaking change, it's been flagged as such.
- [x] In case the PR introduces changes that affect users, the documentation has been updated.

### CODE REVIEW

**Review by kwridan — APPROVED** [review]
Thanks for adding this @FranzBusch 

Would be great to update the changelog and the docs to make this new option more discoverable

https://github.com/tuist/tuist/blob/main/projects/website/markdown/docs/usage/project-description.mdx#build-action

**Comment by FranzBusch** [comment]
@pepibumur Where should I add the documentation for the new docs site?

**Review by pepibumur — APPROVED** [review]
@FranzBusch [this is the place](https://github.com/tuist/tuist/blob/main/projects/docs/docs/manifests/project.md). After adding the documentation and resolving the conflict we can merge the PR.

**Comment by pepibumur** [comment]
I'll add the documentation in `main` :)

**Comment by FranzBusch** [comment]
Thanks @pepibumur for picking this up! :)

**Pull request merged**
