### PR TITLE
Drop support for Xcode 11.x

### PR DESCRIPTION
**Pull request by pepibumur**
### Short description 📝
Considering Apple nudges developers to stay on the latest versions of Xcode and that Xcode 11.7 is around 6 months old, I'm dropping the support for Xcode 11 from Tuist.

### CODE REVIEW

**Review by luispadron — APPROVED** [review]
Curious: Do we know how many users will be affected?

**Review by laxmorek — APPROVED** [review]
Maybe it would be smart to start testing version `12.5` to be prepared when beta ends? 🤔

**Review by fortmarek — COMMENTED** [review]
Could you also update `TapestryConfig.swift` and `release.yml`? Otherwise, I can do that with next release, too 🙂

**Comment by pepibumur** [comment]
> Curious: Do we know how many users will be affected?

According to [stats](https://stats.tuist.io), around an 8% of users are still using Swift 5.2, which is the Swift version that comes with Xcode 11.7.

> Maybe it would be smart to start testing version 12.5 to be prepared when beta ends? 🤔

I'd wait a bit. Usually, a new version of Xcode doesn't break Tuist, so I wouldn't worry about it too much at this point.

> Could you also update TapestryConfig.swift and release.yml? Otherwise, I can do that with next release, too 🙂

Right, I missed this one. I'll update it.

**Pull request merged**
