### PR TITLE
Exclude `next` folder from Tuist Xcode proj

### PR DESCRIPTION
**Pull request by andreacipriani**
### Short description 📝

I thought [excluding folders](http://kostiakoval.github.io/posts/exclude-folders-new-feature-in-swift-package-manager) was a possibility, but apparently it's [not](https://forums.swift.org/t/hiding-ignoring-directories-from-xcode-when-opening-swift-packages/35431/2).
Then I'll suggest continuing with the workaround of adding a `Package.swift` to ignore some folders, and do that for `next`.

### CODE REVIEW

**Review by pepibumur — APPROVED** [review]
Thanks for adding this @andreacipriani

**Comment by andreacipriani** [comment]
Oh, it seems all CI actions based on Next are failing now, will have a look

**Review by RomainBoulay — APPROVED** [review]
👏

**Comment by andreacipriani** [comment]
Any idea why CI would complain about  ```swiftenv: version `5.2.5' (set by /opt/build/repo/.swift-version) is not installed```
That's the same version we declare on the main `Package.swift` 🤔 
@pepibumur

**Pull request merged**
