### PR TITLE
Add system extension product type support

### PR DESCRIPTION
**Pull request by petrukha-ivan**
### Short description 📝

- Added `systemExtension` product type, also updated graph linter
- Updated `BuildPhaseGenerator` to automatically generate embedding script, also added unit tests
- Created `macos_app_with_system_extension` fixture project

[System Extension](https://developer.apple.com/system-extensions/) is a product type to extend the functionality of macOS without requiring kernel-level access. This product type cannot be run as a standalone product but can be embedded into macOS application.

### How to test the changes locally 🧐

- `tuist generate` on `macos_app_with_system_extension` fixture project

### Contributor checklist ✅

- [x] The code has been linted using run `./fourier lint tuist --fix`
- [x] The change is tested via unit testing or acceptance testing, or both
- [x] The title of the PR is formulated in a way that is usable as a changelog entry
- [x] In case the PR introduces changes that affect users, the documentation has been updated

### Reviewer checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase
- [ ] Reviewer has checked that, if needed, the PR includes the label `changelog:added`, `changelog:fixed`, or `changelog:changed`, and the title is usable as a changelog entry

### CODE REVIEW

**Review by danyf90 — APPROVED** [review]

**Comment by danyf90** [comment]
@allcontributors add @petrukha-ivan for code

**Review by kwridan — APPROVED** [review]
Nice work @petrukha-ivan 👍 

Thank you for including a fixture  🙏 was helpful in letting me test this out.

One minor addition would be to update

https://github.com/tuist/tuist/blob/main/Sources/TuistGenerator/Linter/StaticProductsGraphLinter.swift#L172

to skip warning incase the extension and the app link the same static products, in this case I believe it should be ok as they are independent products.

**Review by danyf90 — CHANGES_REQUESTED** [review]
Mark as requiring changes to address Kas feedback about linter 🙏

**Comment by petrukha-ivan** [comment]
@kwridan thank you for noticing this warning! You're right, it can safely link the same static products as apps as they are an independent products 👍

**Pull request merged**
