### PR TITLE
Don't generate empty copy phases

### PR DESCRIPTION
**Pull request by kalkwarf**
(reopening [1822] from a branch)

Resolves https://github.com/tuist/tuist/issues/1181

### Short description 📝

Copy phases with no file lists seem inappropriate. Don't generate them.

### Solution 📦

Using the guidance in [1181], I modified `LinkGenerator.generateLinks` to skip steps if the input list is empty.

### Implementation 👩‍💻👨‍💻

- I created a fixture that creates a resource bundle
- I wrote a test that ensures there are no copy files phases when there are no frameworks or libraries
- I fixed the code so the test passed
- I manually ran the code over the fixture, and visually confirmed the result

image

### CODE REVIEW

**Comment by kalkwarf** [comment]
There was a little bit of discussion in Slack about this: https://tuistapp.slack.com/archives/CTB0DBVD2/p1601576411022400 and the attached thread.

**Comment by kwridan** [comment]
Thanks for re-submitting this @kalkwarf 

I believe the issue we're seeing here is due to an internal inconsistency on how Swift package dependencies are handled vs all other dependencies.

When Swift package dependencies are added: 
https://github.com/tuist/tuist/blob/master/Sources/TuistGenerator/Generator/LinkGenerator.swift#L463

It assumes a frameworks build phase has already been created and appends the Swift package dependencies to it. As such, if we have a scenario where a project only depends on a Swift Package, with the changes here, the frameworks build phase would not exist and the addition of Swift packages would fail due to the missing build phase. 

We're attempting to consolidate how Swift package dependencies are added in https://github.com/tuist/tuist/pull/1831 but there's still a few gotchas we're working through.

**Comment by olejnjak** [comment]
Hi @kwridan, 

is there any update SPM dependencies handling since? I have run into an issue when I have a framework that links only SPM dependencies, it is uncompilable. The cause is empty _Embed frameworks_ build phase, if it is removed it compiles without any issues. Also creating framework target using Xcode doesn't create the empty _Embed frameworks_ build phase and also, if last embedded framework is removed in General tab, the build phase is removed...

It is easily reproducible by this [Project.swift](https://gist.github.com/olejnjak/467d34475f49a6310549f4a306f7fa8a)

**Comment by kwridan** [comment]
Thanks for flagging this @olejnjak, good catch - does the project build ok if there is an Embed dependency (e.g. if you depended on a dynamic framework?)

This PR should help address the issue you mentioned as it will no longer generate an empty embed phase, @kalkwarf if you're still up for it, what I would suggest is possibly:

- Update this PR to always keep the linking phase
  - This will resolve the issue we currently have with linking Swift Packages due to how its wired today

Sadly #1831 is proving to be quite tricky to figure our the correct linking/embedding behaviour.

**Comment by olejnjak** [comment]
> Thanks for flagging this @olejnjak, good catch - does the project build ok if there is an Embed dependency (e.g. if you depended on a dynamic framework?)

Good point, it doesn't if generated by tuist. If created by Xcode it just works (I tried adding framework by Carthage).

**Comment by kwridan** [comment]
Thanks for checking @olejnjak,  with Carthage frameworks, those are prebuilt frameworks which Tuist doesn't include in the Embed build phase (it has a dedicated script phase that copies and thins the frameworks) as such would also result in an empty build phase.

**Comment by olejnjak** [comment]
Well as I was trying with `.framework` target I could not think about any target that will be actually embeded, will try with classic `.app` target and report back.

**Comment by kalkwarf** [comment]
Bumping to keep alive. I plan to get back to this soon.

**Pull request closed without merging**
