### PR TITLE
Add `preActions` and `postActions` to `RunAction` and `ProfileAction`

### PR DESCRIPTION
**Pull request by hisaac**
This PR was generated from a question in the Tuist Slack here: https://tuistapp.slack.com/archives/CTB0DBVD2/p1638098676119800

### Short description 📝

In one of my projects, I use a custom pre-action on one of my scheme's Run action. When attempting to migrate said project to Tuist, I noticed that Tuist does not support adding pre-actions or post-actions to `RunAction`, as well as `ProfileAction` and `AnalyzeAction`.

This PR is to add pre-actions and post-actions to `RunAction` and `ProfileAction`. (I learned while working on this that Xcode does not support pre-actions and post-actions on Analyze actions, so I'm leaving that one as-is.)

### Checklist ✅

- [x] The code architecture and patterns are consistent with the rest of the codebase.
- [ ] The changes have been tested following the [documented guidelines](https://docs.tuist.io/contributors/testing-strategy/).
- [x] The `CHANGELOG.md` has been updated to reflect the changes. In case of a breaking change, it's been flagged as such.
- [x] In case the PR introduces changes that affect users, the documentation has been updated.
- [x] In case the PR introduces changes that affect how the cache artifact is generated starting from the `TuistGraph.Target`, the `Constants.cacheVersion` has been updated.

### CODE REVIEW

**Review by kwridan — COMMENTED** [review]
Thanks for submitting this @hisaac 

I believe the missing connection is updating the [`SchemeDescriptorGenerator`](https://github.com/tuist/tuist/blob/main/Sources/TuistGenerator/Generator/SchemeDescriptorsGenerator.swift) which is responsible for generating the Xcode schemes (descriptors).

**Comment by hisaac** [comment]
Thank you @kwridan! I'll take a look there and see if I can sort it out.

**Review by pepicrft — APPROVED** [review]
This is awesome @hisaac 🚀 🚀 🚀 🚀

**Comment by hisaac** [comment]
This should be ready for final review now. I've tested the changes on one of my projects, and have confirmed that it's working.

**Review by kwridan — APPROVED** [review]
Thanks for contributing this and bringing consistency to the schemes APIs @hisaac 🎉

I've also tested locally with the [`ios_app_with_custom_scheme` fixture](https://github.com/tuist/tuist/tree/main/projects/tuist/fixtures/ios_app_with_custom_scheme)

**Review by fortmarek — APPROVED** [review]
Thanks for the contribution 👏

**Pull request merged**
