### PR TITLE
Allow mlmodel files to be included into source files

### PR DESCRIPTION
**Pull request by SergeyPetrachkov**
### Short description 📝

Now one cannot use MLKit and generate projects correctly because mlmodel files are being filtered out of targets. By adding the extension to the allow-list this patch fixes the issue and projects that use mlmodels can now be generated and built correctly.

### Checklist ✅

- [x] The code architecture and patterns are consistent with the rest of the codebase.
- [x] A developer other than the author has verified that the changes work as expected.
- [ ] The changes have been tested following the [documented guidelines](https://tuist.io/docs/contribution/testing-strategy/).
- [ ] The `CHANGELOG.md` has been updated to reflect the changes. In case of a breaking change, it's been flagged as such.
- [ ] In case the PR introduces changes that affect users, the documentation has been updated.

### CODE REVIEW

**Review by kwridan — APPROVED** [review]
Thanks for adding this @SergeyPetrachkov

**Review by pepibumur — APPROVED** [review]

**Comment by SergeyPetrachkov** [comment]
Hi folks, There are some red checks in this PR, but as far as I can see, they are some sort of CI issue, and are not caused by my changes. What are my next steps here?

**Comment by pepibumur** [comment]
Hey @SergeyPetrachkov. Would you mind rebasing from `main`? There were some issues in the default branch that caused all the PRs to be red. We can merge afterward.

**Comment by pepibumur** [comment]
@all-contributors add @SergeyPetrachkov  for code

**Comment by SergeyPetrachkov** [comment]
@pepibumur yeah, sure

**Review by kwridan — COMMENTED** [review]
ouch looks the rebase / update from main may have picked up too many changes :(

**Pull request closed without merging**
