### PR TITLE
[Prototype] Performance Tests on CI

### PR DESCRIPTION
**Pull request by kwridan**
Continuation of #1593 
Part of #820 

### Short description 📝

Swift PM doesn't currently have a way of setting baselines measurements for performance tests making it a bit challenging to get any feedback from performance tests should any regressions occur.

### Solution 📦

Test out manually setting baselines and asserting on them within the test.

### Implementation 👩‍💻👨‍💻

- [x] Add a new workflow step dedicate to performance tests 
  - Runs tests in Release mode
  - Runs tests with _"PerformanceTests"_ in the name
- [x] Add mechanism to manually set baselines and assert on performance tests
- [ ] Examine stability on #1740 after a few runs
- [ ] Create `TuistPerformanceTestCase` to allow addition of more performance tests
- [ ] Update docs

### CODE REVIEW

**Comment by kwridan** [comment]
This seems somewhat reasonable _(differences between runs on different machines is expected)_

on CI:

```
test_generateWorkspace_performance]' measured [Time, seconds] average: 8.228, relative standard deviation: 5.052%, values: [8.074816, 8.840268, 7.916932, 7.615108, 8.262025, 9.095587, 8.089025, 8.034970, 8.031075, 8.318382], performanceMetricID:com.apple.XCTPerformanceMetric_WallClockTime, baselineName: "", baselineAverage: , maxPercentRegression: 10.000%, maxPercentRelativeStandardDeviation: 10.000%, maxRegression: 0.100, maxStandardDeviation: 0.100
```

Locally:

```
Test Case '-[TuistIntegrationTests.TuistGeneratorPerformanceTests test_generateWorkspace_performance]' measured [Time, seconds] average: 7.304, relative standard deviation: 2.265%, values: [7.465768, 7.306243, 7.273764, 7.210985, 7.269405, 7.060807, 7.497760, 7.292517, 7.593268, 7.066687], performanceMetricID:com.apple.XCTPerformanceMetric_WallClockTime, baselineName: "", baselineAverage: , maxPercentRegression: 10.000%, maxPercentRelativeStandardDeviation: 10.000%, maxRegression: 0.100, maxStandardDeviation: 0.100
```

The standard deviation is a bit higher on CI ~ `5%` vs `2%` locally, will re-trigger the job a few more times, the important thing is for this measurement to be stable between different CI nodes.

**Comment by kwridan** [comment]
Ok I think we have our answer - measurements we get from different CI nodes aren't stable  😞

```
[Time, seconds] average: 9.416, relative standard deviation: 19.394%,
```

```
[Time, seconds] average: 8.228, relative standard deviation: 5.052%
```

```
[Time, seconds] average: 7.106, relative standard deviation: 4.421%
```

**Comment by kwridan** [comment]
I've revised the approach here:

- Baselines are no longer hardcoded (as we saw, the measurements aren't stable between CI nodes)
- The baselines are now recorded by checking out a reference branch (e.g. `master`)
- The same tests are then re-run on the current branch (e.g. the PR branch) and compared against the baselines stored from the earlier run

This should hopefully at least offer some self consistency within a single CI node.

**Comment by pepibumur** [comment]
Should we merge this one @kwridan ?

**Comment by kwridan** [comment]
Almost ready, will push a sample branch/pr to test out failure / success paths with those changes. If all checks out, should be good to 🚀 

Follow ups if this goes well:
- Make a new base class `TuistPerformanceTestCase` which takes care of the baseline logic used here, this should allow us to write more performance tests going forward :)

**Comment by kwridan** [comment]
Attempting another round of tests, to help reduce variance I've added a configuration option to control if the elements within the generated models should be shuffled. Let's see how #1740 fairs.

**Comment by kwridan** [comment]
Some good news and some bad news:

With the latest tweaks the standard deviation for each run is now <10% 🎉

Sadly it looks like it could take up to  ~66 mins to run a single performance test 🙄 depending on the CI node where the action runs - I don't think we can feasibly have that run as part of regular CI workflow.

From this PR ~14 mins _(extrapolated ~7 mins x2 - the second run was skipped as the reference branch `main` doesn't have this code as such no baselines and was skipped)_:

Screenshot 2020-11-11 at 08 17 34


From #1740 ~ 66 mins:
Screenshot 2020-11-11 at 08 14 52

**Pull request closed without merging**
