### PR TITLE
Bump minimum required Xcode version to 14.1 for client use and 14.3 for development

### PR DESCRIPTION
**Pull request by thedavidharris**
Resolves https://github.com/tuist/tuist/issues/YYY

### Short description 📝

> Describe here the purpose of your PR.

### How to test the changes locally 🧐

> Include a set of steps for the reviewer to test the changes locally (see [the documentation](https://docs.tuist.io/contributors/testing-strategy) for reference).

### Contributor checklist ✅

- [ ] The code has been linted using run `./fourier lint tuist --fix`
- [ ] The change is tested via unit testing or acceptance testing, or both
- [ ] The title of the PR is formulated in a way that is usable as a changelog entry
- [ ] In case the PR introduces changes that affect users, the documentation has been updated

### Reviewer checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase
- [ ] Reviewer has checked that, if needed, the PR includes the label `changelog:added`, `changelog:fixed`, or `changelog:changed`, and the title is usable as a changelog entry

### CODE REVIEW

**Review by danyf90 — APPROVED** [review]

**Comment by danyf90** [comment]
I see the following error:
```
2023-05-25T15:53:02.0199950Z ld: warning: ignoring file /private/var/folders/4_/s6tlbqz52vgf905c2l3hntcc0000gn/T/d20230525-6643-4aaj4q/Framework2/prebuilt/Mac/Framework2.framework/Framework2, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
```

Maybe we need to rebuild the binaries with an intel macbook? 🤔  Maybe @fortmarek has one?

**Comment by kwridan** [comment]
I've still got an intel MacBook 🤐

Looks like it was `ios_app_with_transitive_framework/Framework2` that needed a re-build on intel? 

[prebuilt.zip](https://github.com/tuist/tuist/files/11592017/prebuilt.zip)

**Review by kwridan — APPROVED** [review]
Awesome thanks for reviving this @thedavidharris

**Comment by kwridan** [comment]
Sanity check, does building Tuist with Xcode 14.3 mean that's the minimum supported version for users running the binary?

**Pull request merged**
