### PR TITLE
Add "tuist migration settings-to-xcconfig" command

### PR DESCRIPTION
**Pull request by pepibumur**
Resolves https://github.com/tuist/tuist/issues/1659

### Short description 📝

As @garvankeeley pointed out in [this issue](https://github.com/tuist/tuist/issues/1659) piping the output from `xcodebuild -showBuildSettings` into an .xcconfig file is not the best approach because the command flattens all the build settings *(target, project, and xcconfig)*. 

Instead of improve the documentation, what I'm doing in this PR is adding a new command to Tuist:

```bash
tuist migration settings-to-xcconfig -p Project.xcodeproj -t MyApp -x MyApp.xcconfig
```

The command will generate the xcconfig file with the settings from the target. If the target is not passed, it exports the build settings from the project.

### Implementation 👩‍💻👨‍💻
- [x] Implement Command, Service, and extraction logic.
- [x] Add integration tests.
- [x] Update documentation

### CODE REVIEW

**Comment by garvankeeley** [comment]
Awesome! This is the output of this (with an added commandline `sort`) and it very clearly shows commonalities and differences in the configuration settings:
https://gist.github.com/garvankeeley/e2d3c643666b114fb1f6c032291ba5b3

For instance settings that would be collapsed to a common one:
```
SWIFT_VERSION[config=Fennec]=5.0
SWIFT_VERSION[config=Fennec_Enterprise]=5.0
SWIFT_VERSION[config=FirefoxBeta]=5.0
SWIFT_VERSION[config=Firefox]=5.0
```
Would become `SWIFT_VERSION=5.0`, and in other cases where there are per-config differences those can be kept as-is.

**Comment by pepibumur** [comment]
> For instance settings that would be collapsed to a common one:

Interesting, was that the oputput of running this command? I'd have expected those to be collapsed into one line, but it seems that the [logic](https://github.com/tuist/tuist/pull/1660/files#diff-44b60ee13a16ec01ce958afd0a9c2b0cR72) that I added is not right. 

Also.. I'll make sure that the settings are sorted when generating the content of the .xcconfig.

**Comment by garvankeeley** [comment]
The [gist](https://gist.github.com/garvankeeley/e2d3c643666b114fb1f6c032291ba5b3) output was for `tuist migration settings-to-xcconfig -p Client.xcodeproj -t Client -x firefox.xcconfig`,  and then `sort`

**Comment by pepibumur** [comment]
> The gist output was for tuist migration settings-to-xcconfig -p Client.xcodeproj -t Client -x firefox.xcconfig, and then sort

@garvankeeley I pushed a fix and some documentation and I'm working now on adding tests.

**Pull request merged**
