### PR TITLE
Generate TuistStrings+Module for correct localisation strings file

### PR DESCRIPTION
**Pull request by leszko11**
Resolves https://github.com/tuist/tuist/issues/4627

### Short description 📝

> Do not rely on defaultKnownRegions property during string resources generation

### How to test the changes locally 🧐

1. Use `ios_app_with_custom_development_region` fixture
2. Notice `fr.lproj` strings has 2 keys, but `en.lproj` has only 1
3. When `fr` is set as `developmentRegion`, `TuistStrings+App.swift` should contain variables for both keys from strings file

### Contributor checklist ✅

- [x] The code has been linted using run `./fourier lint tuist --fix`
- [x] The change is tested via unit testing or acceptance testing, or both
- [x] The title of the PR is formulated in a way that is usable as a changelog entry
- [x] In case the PR introduces changes that affect users, the documentation has been updated

### Reviewer checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase
- [ ] Reviewer has checked that, if needed, the PR includes the label `changelog:added`, `changelog:fixed`, or `changelog:changed`, and the title is usable as a changelog entry

### CODE REVIEW

**Review by danyf90 — APPROVED** [review]

**Comment by marek-heetch** [comment]
🔥

**Comment by leszko11** [comment]
Hey @fortmarek @pepicrft 👋 
#4627 was eligible for [bounty](https://github.com/tuist/tuist/discussions/4982), so document can be updated 🙂
How I can receive this prize?

**Comment by fortmarek** [comment]
Hey @leszko11 👋 

Congrats 🎉  The easiest way is if you can set up Github sponsors and we would spend a one-time payment through that. Otherwise, feel free to ping me on our [Slack](https://join.slack.com/t/tuistapp/shared_invite/zt-1y667mjbk-s2LTRX1YByb9EIITjdLcLw) and we can figure out an alternative if that doesn't work for you 🙂

**Comment by leszko11** [comment]
Done 🙂

https://github.com/sponsors/leszko11

**Comment by fortmarek** [comment]
Sent 🙌 Thanks again for contributing to Tuist 🙂

**Comment by leszko11** [comment]
Thanks!
And see you in next PR 🫡

**Pull request merged**
