### PR TITLE
Carthage xcframeworks setup swift

### LINKED ISSUE #2503: Enable setting a parameter for Carthage in project setup to use xcframework
**Describe the bug**
Given this Cartfile:
```
let setup = Setup([
    .carthage(platforms: [.iOS]),
])
```

When running `tuist up` it runs: 
`/usr/local/bin/carthage bootstrap --project-directory /Users/parse/prog/tuist-mo --platform iOS BinaryDependency Alamofire` 

This however creates some issues with some packages and with the move towards `xcframework` that is going on in the ecosystem now I'd like to request adding support for adding the flag `--use-xcframeworks` flag. So the complete command would become: 

`/usr/local/bin/carthage bootstrap --project-directory /Users/parse/prog/tuist-mo --platform iOS BinaryDependency Alamofire --use-xcframeworks`

Suggestion for options:

```
let setup = Setup([
    .carthage(platforms: [.iOS], useXcframework: true),
])
```

**Expected behavior**
This command will run:
`/usr/local/bin/carthage bootstrap --project-directory /Users/parse/prog/tuist-mo --platform iOS BinaryDependency Alamofire --use-xcframeworks`

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS 
- Version 11.1
- Tuist Version 1.32

**Additional context**
Using Carthage version 0.37.0

### PR DESCRIPTION
**Pull request by laxmorek**
Resolves #2503 

### Short description 📝

This PR adds a parameter for Carthage in `Setup.swift` to decide whether Carthage should produce XCFrameworks or regular frameworks.

### CODE REVIEW

**Comment by laxmorek** [comment]
@parse Would you like to verify if it satisfies your needs? 🙂

**Review by pepibumur — COMMENTED** [review]
Great job @laxmorek

**Review by pepibumur — APPROVED** [review]

**Comment by parse** [comment]
Looks great!

**Review by fortmarek — APPROVED** [review]
Looks great! It'd maybe just make sense to update the documentation, too? (`up.mdx`)

**Comment by laxmorek** [comment]
@fortmarek I updated documentation. Would you like to check it?

**Pull request merged**
