### PR TITLE
fix: Variadic Parameters were applied to the files in the Source folder.

### PR DESCRIPTION
**Pull request by DevVenusK**
Resolves https://github.com/tuist/tuist/issues/YYY

### Short description 📝

Variadic Parameters were applied to the files in the Source folder.

Variadic parameters were applied only to some files, so there was an inconvenience of having to use [] in many methods.

So, it was applied to all methods.

To comply with the DRY principle, the existing method was used.

### How to test the changes locally 🧐

> Include a set of steps for the reviewer to test the changes locally (see [the documentation](https://docs.tuist.io/contributors/testing-strategy) for reference).

### Contributor checklist ✅

- [ ] The code has been linted using run `./fourier lint tuist --fix`
- [ ] The change is tested via unit testing or acceptance testing, or both
- [ ] The title of the PR is formulated in a way that is usable as a changelog entry
- [ ] In case the PR introduces changes that affect users, the documentation has been updated

### Reviewer checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase
- [ ] Contributors have checked that, if needed, the PR includes the label `changelog:added`, `changelog:fixed`, or `changelog:changed`, and the title is usable as a changelog entry

### CODE REVIEW

**Comment by danyf90** [comment]
I would rather keep the API simple, if it's just for saving a `[]` around the parameter sometime

**Comment by DevVenusK** [comment]
@danyf90 good idea. However, I wanted to give existing users a choice. I thought that if I replaced all of them with Variadic Parameters, there would be too many things to modify.

So, do you agree to delete the existing methods and replace them with Variadic Parameters?

**Comment by danyf90** [comment]
> @danyf90 good idea. However, I wanted to give existing users a choice. I thought that if I replaced all of them with Variadic Parameters, there would be too many things to modify.
> 
> So, do you agree to delete the existing methods and replace them with Variadic Parameters?

I would keep everything as it is, but let's see what @fortmarek and @kwridan think

**Comment by kwridan** [comment]
Hi @DevVenusK 

Thank you for flagging some of the inconsistencies. It can be subjective which of the two approaches (variadic or arrays) are better suited to the different APIs, it might be more suited to some than others rather than necessarily applying to all. 

I agree with @danyf90 to keep the API as is for now rather than replace it as this would be a breaking change. It's something to consider for a future major update if necessary.

**Pull request closed without merging**
