### PR TITLE
Feat: Add ProjectDescription resultBuilder syntax

### PR DESCRIPTION
**Pull request by luispadron**
Related #3906 

## Overview

This is an experiment into using `@resultBuilder` to simplify the Tuist `ProjectDescription` API used to make manifests.

An example `Project.swift` may look like:

```swift
let project = Project(name: "MyProject") {
    Target(
        name: "TargetA",
        platform: .iOS,
        product: .framework,
        bundleId: "com.tuist.Target"
    )

    Scheme(name: "SchemeA")
        .build {
            Target(
                name: "TargetB",
                platform: .iOS,
                product: .framework,
                bundleId: "com.tuist.Target"
            )
        }
        .test {
            Target(
                name: "TestTarget",
                platform: .iOS,
                product: .unitTests,
                bundleId: "com.tuist.Target"
            )
        }
}
```

Any equivalent `Project.swift` using the current API may look like:

```swift
let projectCurrent = Project(
    name: "MyProject",
    targets: [
        Target(
            name: "TargetA",
            platform: .iOS,
            product: .framework,
            bundleId: "com.tuist.Target"
        ),
        Target(
            name: "TargetB",
            platform: .iOS,
            product: .framework,
            bundleId: "com.tuist.Target"
        ),
        Target(
            name: "TestTarget",
            platform: .iOS,
            product: .unitTests,
            bundleId: "com.tuist.Target"
        )
    ],
    schemes: [
        Scheme(
            name: "SchemeA",
            buildAction: .buildAction(targets: ["TargetB"]),
            testAction: .targets([.init(target: "TestTarget")])
        )
    ]
)
```

The result builder syntax makes it easier to create `Scheme`s by allowing developers to create a normal `Target` within the `Scheme` and having it be inserted into the `Project.targets` list.

This API could be added in conjunction to the current API as it uses `extensions` and defines different types under-the-hood to not modify the existing public API. It can be a **non-breaking** change.

## Reasons for

- Makes it easier and more readable (IMO) to define the scheme / target relationship
- Allows finer control for what a "golden path" usage of Tuist looks like

## Reasons against

Below are some reasons against adding this API:

- Two APIs to maintain
- Two APIs to teach
- Defining special extensions and overloads in order to provide a clearer builder syntax requires duplicating a lot of the current API via different types
- Duplication of the API can lead to unexpected behavior if we don't ensure the types values are synced when mapping to & from
- [Discussion of a similar concept for SPM](https://forums.swift.org/t/declarative-package-description-for-swiftpm-using-function-builders/28699)

## Open questions

- What happens if two schemes require one target?
- Do we expose all of the API?
- Should users be encouraged to create their own `ProjectItem`s in order to modify the project?

## Conclusion

We should decide whether we want to add this. Personally I think if we can design a nice, clear and concise API for users (especially new users) then it may make sense to add this in addition to the existing API.

## Checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase.
- [ ] The changes have been tested following the [documented guidelines](https://docs.tuist.io/contributors/testing-strategy/).
- [ ] The `CHANGELOG.md` has been updated to reflect the changes. In case of a breaking change, it's been flagged as such.
- [ ] In case the PR introduces changes that affect users, the documentation has been updated.
- [ ] In case the PR introduces changes that affect how the cache artifact is generated starting from the `TuistGraph.Target`, the `Constants.cacheVersion` has been updated.

### CODE REVIEW

**Comment by danyf90** [comment]
Nice! 🚀 

I have a doubt what happens/ what should I do if I have some targets that I want to add to more than one scheme?
For example we have many features and each feature has its tests and scheme, and then we have an "AllTests" scheme which contains all the test targets

**Comment by luispadron** [comment]
> Nice! 🚀
> 
> I have a doubt what happens/ what should I do if I have some targets that I want to add to more than one scheme? For example we have many features and each feature has its tests and scheme, and then we have an "AllTests" scheme which contains all the test targets

One of my open questions as well. `Target` is equatable so we can just duplicate them into the other scheme but that would get verbose quickly. You could also just create the target above the project

```swift
let target = ...
let Project {
  SchemeA { target }
  SchemeB { target }
}
```

**Comment by ezraberch** [comment]
We could allow the use of `Target("targetName")` (without the need to repeat any other parameters) for all uses after the first. But for something like an "AllTests" scheme, we should support something like this:

```swift
Scheme("AllTests") {
    Target.allTargets.filter {$0.product == .unitTests}
}
```

**Comment by luispadron** [comment]
> We could allow the use of `Target("targetName")` (without the need to repeat any other parameters) for all uses after the first. But for something like an "AllTests" scheme, we should support something like this:
> 
> 
> 
> ```swift
> 
> Scheme("AllTests") {
> 
>     Target.allTargets.filter {$0.product == .unitTests}
> 
> }
> 
> ```

I like the idea of aliasing TargetReference!

I believe your second example should currently work in the pr. 

P.S I edited your comment (and undid the edit) on accident trying to reply

**Pull request closed without merging**
