### PR TITLE
feat: Cache continue on error opt in -e attribute

### PR DESCRIPTION
**Pull request by apps4everyone**
### Short description 📝

Cache continue on error opt in with -e.

### Checklist ✅

- [x] The code architecture and patterns are consistent with the rest of the codebase.
- [x] The changes have been tested following the [documented guidelines](https://docs.tuist.io/contributors/testing-strategy/).
- [x] The `CHANGELOG.md` has been updated to reflect the changes. In case of a breaking change, it's been flagged as such.
- [x] In case the PR introduces changes that affect users, the documentation has been updated.

### CODE REVIEW

**Comment by apps4everyone** [comment]
@fortmarek would it be possible to have this opt in -e in the next release? thx
If customers are complaining we could deprecate again with 2.0...

**Comment by fortmarek** [comment]
@apps4everyone would something like `tuist cache --skip TargetOne TargetTwo` option help you? I think it's better than skipping errors altogether.

**Comment by apps4everyone** [comment]
> @apps4everyone would something like `tuist cache --skip TargetOne TargetTwo` option help you? I think it's better than skipping errors altogether.

yes, in my case only one target is not working. But what if one target has an error and is not compiled? On CI tests you can also set the option to continue with tests even if one fails. This is also something like a dev tool to see where are errors.

If one target throws an error? Is the cache not valid or only the target with the error only is build from source on when you use the cache? Just to understand why you so against the optional error? 
thx for explaining...

**Comment by fortmarek** [comment]
> On CI tests you can also set the option to continue with tests even if one fails.

Yes, but a test fail is a well-contained thing where assertion went wrong. But in this case we have basically no idea why something went wrong and therefore cannot make any assurances about the final cache.

> Is the cache not valid or only the target with the error only is build from source on when you use the cache?

Other cached targets might depend on it and if it errored and we'd just "not care", those targets would be invalid. This is why I propose a skip feature where we would skip the whole subtree of that target (aka skip any targets that depend on the target being skipped). This is the only way how we can ensure everything works correctly. Of course, if your whole project depends on this skipped target, nothing would be cached.

**Comment by apps4everyone** [comment]
opened this new PR, but can't get the rest right...
https://github.com/tuist/tuist/pull/3053/files#diff-3465ad110afa1b5ed514bb5b40ada1c076dc80652327b3f9aac8cb947f4b6e76R262

**Pull request closed without merging**
