### PR TITLE
Add xcmappingmodel to the list of valid source extensions

### PR DESCRIPTION
**Pull request by andreacipriani**
Resolves https://github.com/tuist/tuist/issues/910

### Short description 📝

Core Data mapping models - .xcmappingmodel files - were not included in the Compile Sources Build phase from Tuist. The PR adds the support for them.

### Solution 📦

Add the `xcmappingmodel` format in the `validSourceExtensions` of a `Target`

### Manual testing

Tested on sample project 

https://github.com/andreacipriani/tuist-mapping-model
Screenshot 2020-01-20 at 22 08 11

### CODE REVIEW

**Comment by kwridan** [comment]
Hi @andreacipriani - thanks for submitting this. 

Mind placing your example in `fixtures` so that we always have a reference to try out? It will be really useful to have a CoreData fixture as I suspect there may be other fixes / tweaks needed to support it.

**Comment by andreacipriani** [comment]
Hey @kwridan, sure I'll ad a Fixture with two core data models and a mapping model.
Should I also mention something in the Changelog? CI reminded me

**Comment by pepibumur** [comment]
> Hey @kwridan, sure I'll ad a Fixture with two core data models and a mapping model.
Should I also mention something in the Changelog? CI reminded me

Yes, a CHANGELOG update is necessary so that we mention it when we write the update blog post.  You can read about acceptance tests [here](https://tuist.io/docs/contribution/testing-strategy/#acceptance-tests)

**Comment by andreacipriani** [comment]
@kwridan  Uploaded a fixture
@pepibumur Add an entry in the Changelog

**Comment by pepibumur** [comment]
@andreacipriani one more minor thing. Would you mind adding the fixture to this README explaining what the fixture is for https://github.com/tuist/tuist/blob/master/fixtures/README.md?

**Comment by andreacipriani** [comment]
@pepibumur  fixtures/README updated!

**Pull request merged**
