### PR TITLE
Support visionOS from the default asset templates to synthesize resources

### LINKED ISSUE #5962: VisionOS support for asset resource synthesizers
### What problem or need do you have?

When using Tuist to build an app with asset files, they do not generate properly for a VisionOS application

### Potential solution

I will provide a PR for this shortly, but I believe the template files need to be edited to include vision support in lines that are checking for specific OS's like this:
#if os(iOS) || os(tvOS) || os(watchOS) should be #if os(iOS) || os(tvOS) || os(watchOS) || vision(OS)

Potentil fix: #5963 

### macOS version

14.3

### Tuist version

4.3.2

### Xcode version

15.2

### PR DESCRIPTION
**Pull request by Ethan-IS**
Resolves #5962 

### Short description 📝

Add check for VisionOS in the Asset template

### How to test the changes locally 🧐

> Include a set of steps for the reviewer to test the changes locally (see [the documentation](https://docs.tuist.io/contributors/testing-strategy) for reference).

### Contributor checklist ✅

- [x] The code has been linted using run `mise run lint:fix`
- [ ] The change is tested via unit testing or acceptance testing, or both
- [x] The title of the PR is formulated in a way that is usable as a changelog entry
- [x] In case the PR introduces changes that affect users, the documentation has been updated

### Reviewer checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase
- [ ] Reviewer has checked that, if needed, the PR includes the label `changelog:added`, `changelog:fixed`, or `changelog:changed`, and the title is usable as a changelog entry

### CODE REVIEW

**Review by danyf90 — APPROVED** [review]

**Comment by Ethan-IS** [comment]
@danyf90 
There seems to be a build issue with version 4.3.1, can you check it out?

**Comment by pepicrft** [comment]
A faulty release in combination with GitHub Actions cache caused the builds to fail. It seems to be working now.

**Comment by Ethan-IS** [comment]
@pepicrft Thank you!

**Comment by Ethan-IS** [comment]
@danyf90 
I rebased it, but can you double check?
If you're not comfortable with the commit line, I'll try to PR it again.

**Comment by son-changwoo** [comment]
@pepicrft My PR has been merged. Can you add a contributor?

**Comment by Ethan-IS** [comment]
@pepicrft My PR has been merged. Can you add a contributor?

**Comment by danieleformichelli** [comment]
@allcontributor add @Ethan-IS for code

**Comment by danieleformichelli** [comment]
@allcontributors add @Ethan-IS for code

**Pull request merged**
