### PR TITLE
Add attachDebugger parameter to TestAction.testPlans(...)

### PR DESCRIPTION
**Pull request by Andrea-Scuderi**
Resolves https://github.com/tuist/tuist/issues/4424
Request for comments document (if applies):

### Short description 📝

> Add attachDebugger parameter to TestAction.testPlans(...)

This will allow to disable the debugger during Unit and UI tests

```
Scheme(
                name: "\(name)UITests",
                shared: true,
                buildAction:  .buildAction(
                    targets: ["\(name)", "\(name)UITests"]
                ),
                testAction: .testPlans(
                    [.relativeToRoot("TestPlan/\(name)UITests.xctestplan")],
                    configuration: .debug,
                    attachDebugger: false,
                    preActions: [],
                    postActions: []
                )
)
```

> The parameter `attachDebugger` will be defaulted to `true` to allow backward compatibility.

```
Scheme(
                name: "\(name)UITests",
                shared: true,
                buildAction:  .buildAction(
                    targets: ["\(name)", "\(name)UITests"]
                ),
                testAction: .testPlans(
                    [.relativeToRoot("TestPlan/\(name)UITests.xctestplan")],
                    configuration: .debug,
                    preActions: [],
                    postActions: []
                )
)
```

The previous code will behave as before.

### How to test the changes locally 🧐

> Include a set of steps for the reviewer to test the changes locally.

A demo project has been provide [here](https://github.com/Andrea-Scuderi/DemoTuist)

### Checklist ✅

- [x] The code architecture and patterns are consistent with the rest of the codebase.
- [x] The changes have been tested following the [documented guidelines](https://docs.tuist.io/contributors/testing-strategy/).
- [x] The PR includes the label `changelog:added`, `changelog:fixed`, or `changelog:changed`, whenever it should be included in the “Added”, “Fixed” or “Changed” section of the CHANGELOG. Note: when included in the CHANGELOG, the title of the PR will be used as entry, please make sure it is clear and suitable.
- [ ] In case the PR introduces changes that affect users, the documentation has been updated.
- [ ] In case the PR introduces changes that affect how the cache artifact is generated starting from the `TuistGraph.Target`, the `Constants.cacheVersion` has been updated.

### CODE REVIEW

**Review by kwridan — APPROVED** [review]
Thank you for contributing this @Andrea-Scuderi 🎉

**Comment by kwridan** [comment]
@allcontributors add @Andrea-Scuderi for code

**Comment by albertodebortoli** [comment]
Thank you very much @Andrea-Scuderi for raising this.
Andrea and I noticed we need this at Just Eat Takeaway.com as we rely on Test Plans and we need to keep "Debug Executable" turned off when running the CI pipelines.

**Review by fortmarek — APPROVED** [review]
Thanks for adding this, looks good!

**Comment by albertodebortoli** [comment]
Hey @fortmarek thank you so much for merging this. We are really interested in this change, can you please give an ETA on when this will be released?

**Comment by fortmarek** [comment]
Hey @albertodebortoli, we should make a new release later this week (will try to make it sooner, rather than later 🙌 )

**Pull request merged**
