### PR TITLE
Remove dead code related to CocoaPods support

### PR DESCRIPTION
**Pull request by danyf90**
Resolves https://github.com/tuist/tuist/issues/YYY
Request for comments document (if applies):

### Short description 📝

> Describe here the purpose of your PR.

### How to test the changes locally 🧐

> Include a set of steps for the reviewer to test the changes locally.

### Checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase.
- [ ] The changes have been tested following the [documented guidelines](https://docs.tuist.io/contributors/testing-strategy/).
- [ ] The PR includes the label `changelog:added`, `changelog:fixed`, or `changelog:changed`, whenever it should be included in the “Added”, “Fixed” or “Changed” section of the CHANGELOG. Note: when included in the CHANGELOG, the title of the PR will be used as entry, please make sure it is clear and suitable.
- [ ] In case the PR introduces changes that affect users, the documentation has been updated.
- [ ] In case the PR introduces changes that affect how the cache artifact is generated starting from the `TuistGraph.Target`, the `Constants.cacheVersion` has been updated.

### CODE REVIEW

**Review by fortmarek — APPROVED** [review]
Thanks @danyf90 for the PR.

Just to clarify for any possible future readers: we have made the decision not to support Cocoapods in `Dependencies.swift` due to the contributors' limited time, the increase in issues and support we'd have to provide, and the general fact that the whole iOS community is slowly moving away from Cocoapods.

I'd say we are still open to Cocoapods support if there is someone out there who can take over the implementation and the subsequent support. For now, we're gonna keep supporting Carthage and SPM only in `Dependencies.swift`.

**Comment by okaverin** [comment]
Too bad there's so much contradicting information regarding Cocoapods… When you consider Tuist for a project that at the moment still heavily relies on CP, it's really hard to understand what your options are, and what is going to happen next. Now it finally seems clear that CP support is dead and not coming back. But for example, [this announcement](https://twitter.com/tuistio/status/1476936732624900100) was made not so long ago, right?…

**Comment by fortmarek** [comment]
> Now it finally seems clear that CP support is dead and not coming back

CP support is not dead per se - you can still freely use Cocoapods with tuist. You _will_ miss out on some features, primarily caching, but there's still lots to gain from using CP + tuist.

> But for example, [this announcement](https://twitter.com/tuistio/status/1476936732624900100) was made not so long ago, right?

That is true, but since then we have made the hard decision not to spend countless hours on that due to our limited time capabilities since most of us spend our free time on this project. As I mentioned, if there is someone from the community with enough time to develop the feature and support it after it's done, we'll be more than happy to help them along the way.

If you have additional questions/concerns @okaverin, feel free to share.

**Comment by okaverin** [comment]
@fortmarek Thank you for the clarification!

**Pull request merged**
