### PR TITLE
Improve `tuist init` command

### PR DESCRIPTION
**Pull request by woin2ee**
Resolves https://github.com/tuist/tuist/issues/6354

### Short description 📝

The purpose of this PR is that we follow the default behaviors of Xcode by accepting minor suggestions from https://github.com/tuist/tuist/issues/6354

**Suggestion 1.** Use the original value of `--name` attribute to the project name when run `tuist init` command.
In the past, the value was used by camelized. To align with Xcode, the literal value of `--name` attribute is used to project name. Also, bundle identifier, file(class) name are specified very similar way to how Xcode does it.

_Note:_ When you specify the project name with unusual name such as containing white spaces, tuist displays a warning: `Invalid product name ‘test project’. This string must contain only alphanumeric (A-Z,a-z,0-9), period (.), hyphen (-), and underscore (_) characters.` But considering `init` success and log level, I thought it was a separate issue. However, it's just personal opinion, if we need improving conditions of this linting, please let me know so I can improve it.

**Suggestion 2.** Do not contain `LaunchScreen.storyboard` file in the generated project.
Remove the file and add `UILaunchScreen` key to `info.plist` to align with Xcode.

### How to test the changes locally 🧐

1. Run `tuist init` command with particular name(even weird one) for each os.
2. Check project name, bundle ID, name of classes and files and that the `LaunchScreen.storyboard` removed, `UILaunchScreen` key added.

### Contributor checklist ✅

- [x] The code has been linted using run `mise run lint:fix`
- [x] The change is tested via unit testing or acceptance testing, or both
- [x] The title of the PR is formulated in a way that is usable as a changelog entry
- [x] In case the PR introduces changes that affect users, the documentation has been updated

### Reviewer checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase
- [ ] Reviewer has checked that, if needed, the PR includes the label `changelog:added`, `changelog:fixed`, or `changelog:changed`, and the title is usable as a changelog entry

### CODE REVIEW

**Review by fortmarek — APPROVED** [review]
Amazing PR 👏 The unit tests seem to be failing due to `TuistGraph.Template` having been moved to `TuistCore` module. After that's fixed, we can merge 🙂

**Review by danieleformichelli — APPROVED** [review]

**Comment by fortmarek** [comment]
The current CI failure seems unrelated to your changes, but let's try to fix it here. Can you add a dependency on `TuistLoaderTesting` [here](https://github.com/tuist/tuist/blob/main/Tuist/ProjectDescriptionHelpers/Module.swift#L560). It seems to be missing based on [this](https://codemagic.io/app/65ca555c190cfbe9f5dd792f/build/667009348d9f918904d2c77b#step:6:348:0) error message.

**Comment by fortmarek** [comment]
Merging! Sent some thank you for your continuous work as well 🙂

**Comment by woin2ee** [comment]
Thank you so much, I'm really happy to contribute tuist! 😉

**Pull request merged**
