### PR TITLE
Add `DescriptorGenerator` performance test

### PR DESCRIPTION
**Pull request by kwridan**
Part of #820 

### Short description 📝

Measuring performance of `tuist` as a whole can be achieved via `rake benchmark` however assessing / measuring performance of some of the components (e.g. `DescriptorGenerator`) can be hard to assess during refactors.

### Solution 📦

Add a performance `XCTest` for `DescriptorGenerator`.

### Implementation 👩‍💻👨‍💻

- [x] Add test model generator - to generate large graphs with test data
- [x] Write performance test
- [x] Leverage test model generator within `StableStructureIntegrationTests` as that too requires generating a large graph with test project, targets and dependencies 

### Test Plan 🛠

- Run `TuistGeneratorPerformanceTests`

### Note 📝

It appears there isn't a way to store baselines measurements for Swift PM projects - the feature is currently only available in Xcode - does anyone have any suggestions on how we can store baselines?

### CODE REVIEW

**Comment by pepibumur** [comment]
> It appears there isn't a way to store baselines measurements for Swift PM projects - the feature is currently only available in Xcode - does anyone have any suggestions on how we can store baselines?

I'm not very familiar with performance baselines in Xcode. Does Xcode expect them to be in some specific directory?

**Comment by kwridan** [comment]
Sadly so:

```
tuist.xcodeproj/xcshareddata/xcbaselines/tuist\:\:TuistIntegrationTests.xcbaseline/C94268FD-275C-43E7-93AB-B39CE81AD786.plist 
```

Ouch 😞, I need to find a better way to integrate this test - I just noticed all the unit test jobs shot up significantly in time :( 

this PR:

Screen Shot 2020-07-29 at 6 17 23 PM

Other PRs:

Screen Shot 2020-07-29 at 6 17 56 PM

**Comment by pepibumur** [comment]
@kwridan checking-in on this one. What do you think should be the next steps for this?

**Comment by kwridan** [comment]
I've made it such that the test only runs when in release mode to limit impact on existing tests.

As a follow up I can experiment with manually adding an explicit assert for a measurement and tolerance value (I suspect we'll get some variance on CI, but worth a try)

**Comment by kwridan** [comment]
I've submitted a separate draft PR to test out running performance tests on CI - either way hopefully this PR in its own can be safe to land once CI is ✅ as It no longer impacts existing workflows and introduces the test we can locally run in release mode (if we remember to 😛)

**Pull request merged**
